/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountConfiguration
 */
export interface AccountConfiguration {
    /**
     * 
     * @type {string}
     * @memberof AccountConfiguration
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountConfiguration
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AccountConfiguration
     */
    value?: boolean;
}

/**
 * Check if a given object implements the AccountConfiguration interface.
 */
export function instanceOfAccountConfiguration(value: object): value is AccountConfiguration {
    return true;
}

export function AccountConfigurationFromJSON(json: any): AccountConfiguration {
    return AccountConfigurationFromJSONTyped(json, false);
}

export function AccountConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function AccountConfigurationToJSON(json: any): AccountConfiguration {
    return AccountConfigurationToJSONTyped(json, false);
}

export function AccountConfigurationToJSONTyped(value?: AccountConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'type': value['type'],
        'value': value['value'],
    };
}

