/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountStatusResponse } from './AccountStatusResponse';
import {
    AccountStatusResponseFromJSON,
    AccountStatusResponseFromJSONTyped,
    AccountStatusResponseToJSON,
    AccountStatusResponseToJSONTyped,
} from './AccountStatusResponse';

/**
 * 
 * @export
 * @interface AccountStatusBulkResponse
 */
export interface AccountStatusBulkResponse {
    /**
     * 
     * @type {Array<AccountStatusResponse>}
     * @memberof AccountStatusBulkResponse
     */
    accounts?: Array<AccountStatusResponse>;
    /**
     * 
     * @type {number}
     * @memberof AccountStatusBulkResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountStatusBulkResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountStatusBulkResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the AccountStatusBulkResponse interface.
 */
export function instanceOfAccountStatusBulkResponse(value: object): value is AccountStatusBulkResponse {
    return true;
}

export function AccountStatusBulkResponseFromJSON(json: any): AccountStatusBulkResponse {
    return AccountStatusBulkResponseFromJSONTyped(json, false);
}

export function AccountStatusBulkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStatusBulkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(AccountStatusResponseFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function AccountStatusBulkResponseToJSON(json: any): AccountStatusBulkResponse {
    return AccountStatusBulkResponseToJSONTyped(json, false);
}

export function AccountStatusBulkResponseToJSONTyped(value?: AccountStatusBulkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(AccountStatusResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

