/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccreditedInvestorInformation
 */
export interface AccreditedInvestorInformation {
    /**
     * 
     * @type {boolean}
     * @memberof AccreditedInvestorInformation
     */
    q1?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccreditedInvestorInformation
     */
    q2?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccreditedInvestorInformation
     */
    q3?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccreditedInvestorInformation
     */
    q4?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccreditedInvestorInformation
     */
    q5?: boolean;
}

/**
 * Check if a given object implements the AccreditedInvestorInformation interface.
 */
export function instanceOfAccreditedInvestorInformation(value: object): value is AccreditedInvestorInformation {
    return true;
}

export function AccreditedInvestorInformationFromJSON(json: any): AccreditedInvestorInformation {
    return AccreditedInvestorInformationFromJSONTyped(json, false);
}

export function AccreditedInvestorInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccreditedInvestorInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'q1': json['q1'] == null ? undefined : json['q1'],
        'q2': json['q2'] == null ? undefined : json['q2'],
        'q3': json['q3'] == null ? undefined : json['q3'],
        'q4': json['q4'] == null ? undefined : json['q4'],
        'q5': json['q5'] == null ? undefined : json['q5'],
    };
}

export function AccreditedInvestorInformationToJSON(json: any): AccreditedInvestorInformation {
    return AccreditedInvestorInformationToJSONTyped(json, false);
}

export function AccreditedInvestorInformationToJSONTyped(value?: AccreditedInvestorInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'q1': value['q1'],
        'q2': value['q2'],
        'q3': value['q3'],
        'q4': value['q4'],
        'q5': value['q5'],
    };
}

