/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AchInstructionClientAccountInfo } from './AchInstructionClientAccountInfo';
import {
    AchInstructionClientAccountInfoFromJSON,
    AchInstructionClientAccountInfoFromJSONTyped,
    AchInstructionClientAccountInfoToJSON,
    AchInstructionClientAccountInfoToJSONTyped,
} from './AchInstructionClientAccountInfo';

/**
 * 
 * @export
 * @interface AchInstruction
 */
export interface AchInstruction {
    /**
     * 
     * @type {string}
     * @memberof AchInstruction
     */
    accountId: string;
    /**
     * 
     * @type {AchInstructionAchTypeEnum}
     * @memberof AchInstruction
     */
    achType: AchInstructionAchTypeEnum;
    /**
     * 
     * @type {AchInstructionBankInstructionCodeEnum}
     * @memberof AchInstruction
     */
    bankInstructionCode: AchInstructionBankInstructionCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof AchInstruction
     */
    bankInstructionName: string;
    /**
     * 
     * @type {AchInstructionClientAccountInfo}
     * @memberof AchInstruction
     */
    clientAccountInfo: AchInstructionClientAccountInfo;
    /**
     * 
     * @type {number}
     * @memberof AchInstruction
     */
    clientInstructionId: number;
    /**
     * 
     * @type {string}
     * @memberof AchInstruction
     */
    currency: string;
}


/**
 * @export
 */
export const AchInstructionAchTypeEnum = {
    Debit: 'DEBIT',
    Credit: 'CREDIT',
    DebitCredit: 'DEBIT_CREDIT'
} as const;
export type AchInstructionAchTypeEnum = typeof AchInstructionAchTypeEnum[keyof typeof AchInstructionAchTypeEnum];

/**
 * @export
 */
export const AchInstructionBankInstructionCodeEnum = {
    Caach: 'CAACH',
    Usach: 'USACH'
} as const;
export type AchInstructionBankInstructionCodeEnum = typeof AchInstructionBankInstructionCodeEnum[keyof typeof AchInstructionBankInstructionCodeEnum];


/**
 * Check if a given object implements the AchInstruction interface.
 */
export function instanceOfAchInstruction(value: object): value is AchInstruction {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('achType' in value) || value['achType'] === undefined) return false;
    if (!('bankInstructionCode' in value) || value['bankInstructionCode'] === undefined) return false;
    if (!('bankInstructionName' in value) || value['bankInstructionName'] === undefined) return false;
    if (!('clientAccountInfo' in value) || value['clientAccountInfo'] === undefined) return false;
    if (!('clientInstructionId' in value) || value['clientInstructionId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function AchInstructionFromJSON(json: any): AchInstruction {
    return AchInstructionFromJSONTyped(json, false);
}

export function AchInstructionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchInstruction {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'achType': json['achType'],
        'bankInstructionCode': json['bankInstructionCode'],
        'bankInstructionName': json['bankInstructionName'],
        'clientAccountInfo': AchInstructionClientAccountInfoFromJSON(json['clientAccountInfo']),
        'clientInstructionId': json['clientInstructionId'],
        'currency': json['currency'],
    };
}

export function AchInstructionToJSON(json: any): AchInstruction {
    return AchInstructionToJSONTyped(json, false);
}

export function AchInstructionToJSONTyped(value?: AchInstruction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'achType': value['achType'],
        'bankInstructionCode': value['bankInstructionCode'],
        'bankInstructionName': value['bankInstructionName'],
        'clientAccountInfo': AchInstructionClientAccountInfoToJSON(value['clientAccountInfo']),
        'clientInstructionId': value['clientInstructionId'],
        'currency': value['currency'],
    };
}

