/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlertCreationRequestConditionsInner
 */
export interface AlertCreationRequestConditionsInner {
    /**
     * Concatenation of conid and exchange. Formatted as "conid@exchange"
     * @type {string}
     * @memberof AlertCreationRequestConditionsInner
     */
    conidex: string;
    /**
     * Describes how multiple conditions should behave together. Available logic types:
     *   * `a` - AND
     *   * `o` - OR
     *   * `n` - END
     * 
     * @type {AlertCreationRequestConditionsInnerLogicBindEnum}
     * @memberof AlertCreationRequestConditionsInner
     */
    logicBind: AlertCreationRequestConditionsInnerLogicBindEnum;
    /**
     * Indicates whether the trigger should be above or below the given value. (one of: >=, <=, >, <, ==)
     * @type {string}
     * @memberof AlertCreationRequestConditionsInner
     */
    operator: string;
    /**
     * Only needed for some MTA alert condition.
     * @type {string}
     * @memberof AlertCreationRequestConditionsInner
     */
    timeZone?: string;
    /**
     * Pass the string representation of zero, "0"
     * @type {string}
     * @memberof AlertCreationRequestConditionsInner
     */
    triggerMethod: string;
    /**
     * Designate what condition type to use. Note the "MTA" types listed are only supported if iTWSOrdersOnly=1 Available condition types:
     *   * `1` - Price
     *   * `3` - Time
     *   * `4` - Margin
     *   * `5` - Trade
     *   * `6` - Volume
     *   * `7` - MTA Market
     *   * `8` - MTA Postion
     *   * `9` - MTA Account Daily PnL
     * 
     * @type {AlertCreationRequestConditionsInnerTypeEnum}
     * @memberof AlertCreationRequestConditionsInner
     */
    type: AlertCreationRequestConditionsInnerTypeEnum;
    /**
     * Trigger value based on Type.
     * @type {string}
     * @memberof AlertCreationRequestConditionsInner
     */
    value: string;
}


/**
 * @export
 */
export const AlertCreationRequestConditionsInnerLogicBindEnum = {
    A: 'a',
    O: 'o',
    N: 'n'
} as const;
export type AlertCreationRequestConditionsInnerLogicBindEnum = typeof AlertCreationRequestConditionsInnerLogicBindEnum[keyof typeof AlertCreationRequestConditionsInnerLogicBindEnum];

/**
 * @export
 */
export const AlertCreationRequestConditionsInnerTypeEnum = {
    NUMBER_1: 1,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9
} as const;
export type AlertCreationRequestConditionsInnerTypeEnum = typeof AlertCreationRequestConditionsInnerTypeEnum[keyof typeof AlertCreationRequestConditionsInnerTypeEnum];


/**
 * Check if a given object implements the AlertCreationRequestConditionsInner interface.
 */
export function instanceOfAlertCreationRequestConditionsInner(value: object): value is AlertCreationRequestConditionsInner {
    if (!('conidex' in value) || value['conidex'] === undefined) return false;
    if (!('logicBind' in value) || value['logicBind'] === undefined) return false;
    if (!('operator' in value) || value['operator'] === undefined) return false;
    if (!('triggerMethod' in value) || value['triggerMethod'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AlertCreationRequestConditionsInnerFromJSON(json: any): AlertCreationRequestConditionsInner {
    return AlertCreationRequestConditionsInnerFromJSONTyped(json, false);
}

export function AlertCreationRequestConditionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertCreationRequestConditionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'conidex': json['conidex'],
        'logicBind': json['logicBind'],
        'operator': json['operator'],
        'timeZone': json['timeZone'] == null ? undefined : json['timeZone'],
        'triggerMethod': json['triggerMethod'],
        'type': json['type'],
        'value': json['value'],
    };
}

export function AlertCreationRequestConditionsInnerToJSON(json: any): AlertCreationRequestConditionsInner {
    return AlertCreationRequestConditionsInnerToJSONTyped(json, false);
}

export function AlertCreationRequestConditionsInnerToJSONTyped(value?: AlertCreationRequestConditionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conidex': value['conidex'],
        'logicBind': value['logicBind'],
        'operator': value['operator'],
        'timeZone': value['timeZone'],
        'triggerMethod': value['triggerMethod'],
        'type': value['type'],
        'value': value['value'],
    };
}

