/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlertActivationRequest
 */
export interface AlertActivationRequest {
    /**
     * Set whether or not the alert should be active (1) or inactive (0).
     * @type {AlertActivationRequestAlertActiveEnum}
     * @memberof AlertActivationRequest
     */
    alertActive: AlertActivationRequestAlertActiveEnum;
    /**
     * The alert Identifier
     * @type {number}
     * @memberof AlertActivationRequest
     */
    alertId: number;
}


/**
 * @export
 */
export const AlertActivationRequestAlertActiveEnum = {
    NUMBER_1: 1,
    NUMBER_0: 0
} as const;
export type AlertActivationRequestAlertActiveEnum = typeof AlertActivationRequestAlertActiveEnum[keyof typeof AlertActivationRequestAlertActiveEnum];


/**
 * Check if a given object implements the AlertActivationRequest interface.
 */
export function instanceOfAlertActivationRequest(value: object): value is AlertActivationRequest {
    if (!('alertActive' in value) || value['alertActive'] === undefined) return false;
    if (!('alertId' in value) || value['alertId'] === undefined) return false;
    return true;
}

export function AlertActivationRequestFromJSON(json: any): AlertActivationRequest {
    return AlertActivationRequestFromJSONTyped(json, false);
}

export function AlertActivationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertActivationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'alertActive': json['alertActive'],
        'alertId': json['alertId'],
    };
}

export function AlertActivationRequestToJSON(json: any): AlertActivationRequest {
    return AlertActivationRequestToJSONTyped(json, false);
}

export function AlertActivationRequestToJSONTyped(value?: AlertActivationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alertActive': value['alertActive'],
        'alertId': value['alertId'],
    };
}

