/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnswerResponse
 */
export interface AnswerResponse {
    /**
     * 
     * @type {string}
     * @memberof AnswerResponse
     */
    answer?: string;
    /**
     * 
     * @type {number}
     * @memberof AnswerResponse
     */
    answerId?: number;
    /**
     * 
     * @type {number}
     * @memberof AnswerResponse
     */
    dependentAnswerId?: number;
    /**
     * 
     * @type {number}
     * @memberof AnswerResponse
     */
    dependentQuestionId?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnswerResponse
     */
    multiAnswerDetail?: Array<string>;
}

/**
 * Check if a given object implements the AnswerResponse interface.
 */
export function instanceOfAnswerResponse(value: object): value is AnswerResponse {
    return true;
}

export function AnswerResponseFromJSON(json: any): AnswerResponse {
    return AnswerResponseFromJSONTyped(json, false);
}

export function AnswerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'] == null ? undefined : json['answer'],
        'answerId': json['answerId'] == null ? undefined : json['answerId'],
        'dependentAnswerId': json['dependentAnswerId'] == null ? undefined : json['dependentAnswerId'],
        'dependentQuestionId': json['dependentQuestionId'] == null ? undefined : json['dependentQuestionId'],
        'multiAnswerDetail': json['multiAnswerDetail'] == null ? undefined : json['multiAnswerDetail'],
    };
}

export function AnswerResponseToJSON(json: any): AnswerResponse {
    return AnswerResponseToJSONTyped(json, false);
}

export function AnswerResponseToJSONTyped(value?: AnswerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'answerId': value['answerId'],
        'dependentAnswerId': value['dependentAnswerId'],
        'dependentQuestionId': value['dependentQuestionId'],
        'multiAnswerDetail': value['multiAnswerDetail'],
    };
}

