/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmploymentDetails } from './EmploymentDetails';
import {
    EmploymentDetailsFromJSON,
    EmploymentDetailsFromJSONTyped,
    EmploymentDetailsToJSON,
    EmploymentDetailsToJSONTyped,
} from './EmploymentDetails';
import type { IndividualName } from './IndividualName';
import {
    IndividualNameFromJSON,
    IndividualNameFromJSONTyped,
    IndividualNameToJSON,
    IndividualNameToJSONTyped,
} from './IndividualName';
import type { FormW9 } from './FormW9';
import {
    FormW9FromJSON,
    FormW9FromJSONTyped,
    FormW9ToJSON,
    FormW9ToJSONTyped,
} from './FormW9';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { TaxResidency } from './TaxResidency';
import {
    TaxResidencyFromJSON,
    TaxResidencyFromJSONTyped,
    TaxResidencyToJSON,
    TaxResidencyToJSONTyped,
} from './TaxResidency';
import type { FormW8BEN } from './FormW8BEN';
import {
    FormW8BENFromJSON,
    FormW8BENFromJSONTyped,
    FormW8BENToJSON,
    FormW8BENToJSONTyped,
} from './FormW8BEN';
import type { FormCRS } from './FormCRS';
import {
    FormCRSFromJSON,
    FormCRSFromJSONTyped,
    FormCRSToJSON,
    FormCRSToJSONTyped,
} from './FormCRS';
import type { Title } from './Title';
import {
    TitleFromJSON,
    TitleFromJSONTyped,
    TitleToJSON,
    TitleToJSONTyped,
} from './Title';
import type { Identification } from './Identification';
import {
    IdentificationFromJSON,
    IdentificationFromJSONTyped,
    IdentificationToJSON,
    IdentificationToJSONTyped,
} from './Identification';
import type { ResidenceAddress } from './ResidenceAddress';
import {
    ResidenceAddressFromJSON,
    ResidenceAddressFromJSONTyped,
    ResidenceAddressToJSON,
    ResidenceAddressToJSONTyped,
} from './ResidenceAddress';
import type { PhoneInfo } from './PhoneInfo';
import {
    PhoneInfoFromJSON,
    PhoneInfoFromJSONTyped,
    PhoneInfoToJSON,
    PhoneInfoToJSONTyped,
} from './PhoneInfo';
import type { ProhibitedCountryQuestionnaireList } from './ProhibitedCountryQuestionnaireList';
import {
    ProhibitedCountryQuestionnaireListFromJSON,
    ProhibitedCountryQuestionnaireListFromJSONTyped,
    ProhibitedCountryQuestionnaireListToJSON,
    ProhibitedCountryQuestionnaireListToJSONTyped,
} from './ProhibitedCountryQuestionnaireList';

/**
 * 
 * @export
 * @interface AssociatedIndividual
 */
export interface AssociatedIndividual {
    /**
     * 
     * @type {boolean}
     * @memberof AssociatedIndividual
     */
    authorizedPerson?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AssociatedIndividual
     */
    authorizedToSignOnBehalfOfOwner?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AssociatedIndividual
     */
    authorizedTrader?: boolean;
    /**
     * 
     * @type {IndividualName}
     * @memberof AssociatedIndividual
     */
    birthName?: IndividualName;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    cityOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    countryOfBirth?: string;
    /**
     * 
     * @type {FormCRS}
     * @memberof AssociatedIndividual
     */
    crs?: FormCRS;
    /**
     * Date of birth of the applicant. The applicant must be 18 years or older to open an account. <br><ul><li>If the YYY-MM-DD < 18 years error will be triggered and the account will not be created.</li><li>If YYYY-MM-DD < 21 the applicant is restricted to opening a CASH account only.</li><li>UGMA and UTMA accounts are available for minors 18 years of age or younger. An individual or entity who manages an account for a minor until that minor reaches a specific age. Available to US residents only.</li><li>This application must be opened using the front-end application which is available within the IBKR Portal.</li><li>Assets held in a single account managed by a single Custodian user.</li><li>Error will be thrown if dateOfBirth is any value other than YYYY-MM-DD.</li></ul>
     * @type {string}
     * @memberof AssociatedIndividual
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    employeeTitle?: string;
    /**
     * 
     * @type {EmploymentDetails}
     * @memberof AssociatedIndividual
     */
    employmentDetails?: EmploymentDetails;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    employmentType?: string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    externalId?: string;
    /**
     * 
     * @type {AssociatedIndividualGenderEnum}
     * @memberof AssociatedIndividual
     */
    gender?: AssociatedIndividualGenderEnum;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    id?: string;
    /**
     * 
     * @type {Identification}
     * @memberof AssociatedIndividual
     */
    identification?: Identification;
    /**
     * 
     * @type {Address}
     * @memberof AssociatedIndividual
     */
    mailingAddress?: Address;
    /**
     * 
     * @type {AssociatedIndividualMaritalStatusEnum}
     * @memberof AssociatedIndividual
     */
    maritalStatus?: AssociatedIndividualMaritalStatusEnum;
    /**
     * 
     * @type {IndividualName}
     * @memberof AssociatedIndividual
     */
    motherMaidenName?: IndividualName;
    /**
     * 
     * @type {IndividualName}
     * @memberof AssociatedIndividual
     */
    name?: IndividualName;
    /**
     * 
     * @type {IndividualName}
     * @memberof AssociatedIndividual
     */
    nativeName?: IndividualName;
    /**
     * 
     * @type {number}
     * @memberof AssociatedIndividual
     */
    numDependents?: number;
    /**
     * 
     * @type {number}
     * @memberof AssociatedIndividual
     */
    ownershipPercentage?: number;
    /**
     * 
     * @type {Array<PhoneInfo>}
     * @memberof AssociatedIndividual
     */
    phones?: Array<PhoneInfo>;
    /**
     * 
     * @type {boolean}
     * @memberof AssociatedIndividual
     */
    primaryTrustee?: boolean;
    /**
     * 
     * @type {ProhibitedCountryQuestionnaireList}
     * @memberof AssociatedIndividual
     */
    prohibitedCountryQuestionnaire?: ProhibitedCountryQuestionnaireList;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    referenceUsername?: string;
    /**
     * 
     * @type {ResidenceAddress}
     * @memberof AssociatedIndividual
     */
    residenceAddress?: ResidenceAddress;
    /**
     * 
     * @type {boolean}
     * @memberof AssociatedIndividual
     */
    sameMailAddress?: boolean;
    /**
     * 
     * @type {Array<TaxResidency>}
     * @memberof AssociatedIndividual
     */
    taxResidencies?: Array<TaxResidency>;
    /**
     * 
     * @type {Array<Title>}
     * @memberof AssociatedIndividual
     */
    titles?: Array<Title>;
    /**
     * 
     * @type {boolean}
     * @memberof AssociatedIndividual
     */
    translated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AssociatedIndividual
     */
    usTaxResident?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AssociatedIndividual
     */
    userId?: string;
    /**
     * 
     * @type {FormW8BEN}
     * @memberof AssociatedIndividual
     */
    w8Ben?: FormW8BEN;
    /**
     * 
     * @type {FormW9}
     * @memberof AssociatedIndividual
     */
    w9?: FormW9;
}


/**
 * @export
 */
export const AssociatedIndividualGenderEnum = {
    M: 'M',
    F: 'F',
    Male: 'Male',
    Female: 'Female'
} as const;
export type AssociatedIndividualGenderEnum = typeof AssociatedIndividualGenderEnum[keyof typeof AssociatedIndividualGenderEnum];

/**
 * @export
 */
export const AssociatedIndividualMaritalStatusEnum = {
    S: 'S',
    M: 'M',
    W: 'W',
    D: 'D',
    C: 'C'
} as const;
export type AssociatedIndividualMaritalStatusEnum = typeof AssociatedIndividualMaritalStatusEnum[keyof typeof AssociatedIndividualMaritalStatusEnum];


/**
 * Check if a given object implements the AssociatedIndividual interface.
 */
export function instanceOfAssociatedIndividual(value: object): value is AssociatedIndividual {
    return true;
}

export function AssociatedIndividualFromJSON(json: any): AssociatedIndividual {
    return AssociatedIndividualFromJSONTyped(json, false);
}

export function AssociatedIndividualFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssociatedIndividual {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizedPerson': json['authorizedPerson'] == null ? undefined : json['authorizedPerson'],
        'authorizedToSignOnBehalfOfOwner': json['authorizedToSignOnBehalfOfOwner'] == null ? undefined : json['authorizedToSignOnBehalfOfOwner'],
        'authorizedTrader': json['authorizedTrader'] == null ? undefined : json['authorizedTrader'],
        'birthName': json['birthName'] == null ? undefined : IndividualNameFromJSON(json['birthName']),
        'cityOfBirth': json['cityOfBirth'] == null ? undefined : json['cityOfBirth'],
        'countryOfBirth': json['countryOfBirth'] == null ? undefined : json['countryOfBirth'],
        'crs': json['crs'] == null ? undefined : FormCRSFromJSON(json['crs']),
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : json['dateOfBirth'],
        'email': json['email'] == null ? undefined : json['email'],
        'employeeTitle': json['employeeTitle'] == null ? undefined : json['employeeTitle'],
        'employmentDetails': json['employmentDetails'] == null ? undefined : EmploymentDetailsFromJSON(json['employmentDetails']),
        'employmentType': json['employmentType'] == null ? undefined : json['employmentType'],
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'identification': json['identification'] == null ? undefined : IdentificationFromJSON(json['identification']),
        'mailingAddress': json['mailingAddress'] == null ? undefined : AddressFromJSON(json['mailingAddress']),
        'maritalStatus': json['maritalStatus'] == null ? undefined : json['maritalStatus'],
        'motherMaidenName': json['motherMaidenName'] == null ? undefined : IndividualNameFromJSON(json['motherMaidenName']),
        'name': json['name'] == null ? undefined : IndividualNameFromJSON(json['name']),
        'nativeName': json['nativeName'] == null ? undefined : IndividualNameFromJSON(json['nativeName']),
        'numDependents': json['numDependents'] == null ? undefined : json['numDependents'],
        'ownershipPercentage': json['ownershipPercentage'] == null ? undefined : json['ownershipPercentage'],
        'phones': json['phones'] == null ? undefined : ((json['phones'] as Array<any>).map(PhoneInfoFromJSON)),
        'primaryTrustee': json['primaryTrustee'] == null ? undefined : json['primaryTrustee'],
        'prohibitedCountryQuestionnaire': json['prohibitedCountryQuestionnaire'] == null ? undefined : ProhibitedCountryQuestionnaireListFromJSON(json['prohibitedCountryQuestionnaire']),
        'referenceUsername': json['referenceUsername'] == null ? undefined : json['referenceUsername'],
        'residenceAddress': json['residenceAddress'] == null ? undefined : ResidenceAddressFromJSON(json['residenceAddress']),
        'sameMailAddress': json['sameMailAddress'] == null ? undefined : json['sameMailAddress'],
        'taxResidencies': json['taxResidencies'] == null ? undefined : ((json['taxResidencies'] as Array<any>).map(TaxResidencyFromJSON)),
        'titles': json['titles'] == null ? undefined : ((json['titles'] as Array<any>).map(TitleFromJSON)),
        'translated': json['translated'] == null ? undefined : json['translated'],
        'usTaxResident': json['usTaxResident'] == null ? undefined : json['usTaxResident'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'w8Ben': json['w8Ben'] == null ? undefined : FormW8BENFromJSON(json['w8Ben']),
        'w9': json['w9'] == null ? undefined : FormW9FromJSON(json['w9']),
    };
}

export function AssociatedIndividualToJSON(json: any): AssociatedIndividual {
    return AssociatedIndividualToJSONTyped(json, false);
}

export function AssociatedIndividualToJSONTyped(value?: AssociatedIndividual | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorizedPerson': value['authorizedPerson'],
        'authorizedToSignOnBehalfOfOwner': value['authorizedToSignOnBehalfOfOwner'],
        'authorizedTrader': value['authorizedTrader'],
        'birthName': IndividualNameToJSON(value['birthName']),
        'cityOfBirth': value['cityOfBirth'],
        'countryOfBirth': value['countryOfBirth'],
        'crs': FormCRSToJSON(value['crs']),
        'dateOfBirth': value['dateOfBirth'],
        'email': value['email'],
        'employeeTitle': value['employeeTitle'],
        'employmentDetails': EmploymentDetailsToJSON(value['employmentDetails']),
        'employmentType': value['employmentType'],
        'externalId': value['externalId'],
        'gender': value['gender'],
        'id': value['id'],
        'identification': IdentificationToJSON(value['identification']),
        'mailingAddress': AddressToJSON(value['mailingAddress']),
        'maritalStatus': value['maritalStatus'],
        'motherMaidenName': IndividualNameToJSON(value['motherMaidenName']),
        'name': IndividualNameToJSON(value['name']),
        'nativeName': IndividualNameToJSON(value['nativeName']),
        'numDependents': value['numDependents'],
        'ownershipPercentage': value['ownershipPercentage'],
        'phones': value['phones'] == null ? undefined : ((value['phones'] as Array<any>).map(PhoneInfoToJSON)),
        'primaryTrustee': value['primaryTrustee'],
        'prohibitedCountryQuestionnaire': ProhibitedCountryQuestionnaireListToJSON(value['prohibitedCountryQuestionnaire']),
        'referenceUsername': value['referenceUsername'],
        'residenceAddress': ResidenceAddressToJSON(value['residenceAddress']),
        'sameMailAddress': value['sameMailAddress'],
        'taxResidencies': value['taxResidencies'] == null ? undefined : ((value['taxResidencies'] as Array<any>).map(TaxResidencyToJSON)),
        'titles': value['titles'] == null ? undefined : ((value['titles'] as Array<any>).map(TitleToJSON)),
        'translated': value['translated'],
        'usTaxResident': value['usTaxResident'],
        'userId': value['userId'],
        'w8Ben': FormW8BENToJSON(value['w8Ben']),
        'w9': FormW9ToJSON(value['w9']),
    };
}

