/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Base64UrlString
 */
export interface Base64UrlString {
    /**
     * 
     * @type {boolean}
     * @memberof Base64UrlString
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the Base64UrlString interface.
 */
export function instanceOfBase64UrlString(value: object): value is Base64UrlString {
    return true;
}

export function Base64UrlStringFromJSON(json: any): Base64UrlString {
    return Base64UrlStringFromJSONTyped(json, false);
}

export function Base64UrlStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): Base64UrlString {
    if (json == null) {
        return json;
    }
    return {
        
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function Base64UrlStringToJSON(json: any): Base64UrlString {
    return Base64UrlStringToJSONTyped(json, false);
}

export function Base64UrlStringToJSONTyped(value?: Base64UrlString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'empty': value['empty'],
    };
}

