/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BondFiltersResponseBondFiltersInnerOptionsInner
 */
export interface BondFiltersResponseBondFiltersInnerOptionsInner {
    /**
     * In some instances, a text value will be returned, which indicates the standardized value format such as plaintext dates, rather than solely numerical values.
     * @type {string}
     * @memberof BondFiltersResponseBondFiltersInnerOptionsInner
     */
    text?: string;
    /**
     * Returns value directly correlating to the displayText key. This may include exchange, maturity date, issue date, coupon, or currency.
     * @type {string}
     * @memberof BondFiltersResponseBondFiltersInnerOptionsInner
     */
    value: string;
}

/**
 * Check if a given object implements the BondFiltersResponseBondFiltersInnerOptionsInner interface.
 */
export function instanceOfBondFiltersResponseBondFiltersInnerOptionsInner(value: object): value is BondFiltersResponseBondFiltersInnerOptionsInner {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function BondFiltersResponseBondFiltersInnerOptionsInnerFromJSON(json: any): BondFiltersResponseBondFiltersInnerOptionsInner {
    return BondFiltersResponseBondFiltersInnerOptionsInnerFromJSONTyped(json, false);
}

export function BondFiltersResponseBondFiltersInnerOptionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BondFiltersResponseBondFiltersInnerOptionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'value': json['value'],
    };
}

export function BondFiltersResponseBondFiltersInnerOptionsInnerToJSON(json: any): BondFiltersResponseBondFiltersInnerOptionsInner {
    return BondFiltersResponseBondFiltersInnerOptionsInnerToJSONTyped(json, false);
}

export function BondFiltersResponseBondFiltersInnerOptionsInnerToJSONTyped(value?: BondFiltersResponseBondFiltersInnerOptionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'value': value['value'],
    };
}

