/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrokerageSessionStatusServerInfo
 */
export interface BrokerageSessionStatusServerInfo {
    /**
     * IBKR server information. Internal use only.
     * @type {string}
     * @memberof BrokerageSessionStatusServerInfo
     */
    serverName?: string;
    /**
     * IBKR version information. Internal use only.
     * @type {string}
     * @memberof BrokerageSessionStatusServerInfo
     */
    serverVersion?: string;
}

/**
 * Check if a given object implements the BrokerageSessionStatusServerInfo interface.
 */
export function instanceOfBrokerageSessionStatusServerInfo(value: object): value is BrokerageSessionStatusServerInfo {
    return true;
}

export function BrokerageSessionStatusServerInfoFromJSON(json: any): BrokerageSessionStatusServerInfo {
    return BrokerageSessionStatusServerInfoFromJSONTyped(json, false);
}

export function BrokerageSessionStatusServerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrokerageSessionStatusServerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'serverName': json['serverName'] == null ? undefined : json['serverName'],
        'serverVersion': json['serverVersion'] == null ? undefined : json['serverVersion'],
    };
}

export function BrokerageSessionStatusServerInfoToJSON(json: any): BrokerageSessionStatusServerInfo {
    return BrokerageSessionStatusServerInfoToJSONTyped(json, false);
}

export function BrokerageSessionStatusServerInfoToJSONTyped(value?: BrokerageSessionStatusServerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverName': value['serverName'],
        'serverVersion': value['serverVersion'],
    };
}

