/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryTreeResponseCategoriesCategoryId } from './CategoryTreeResponseCategoriesCategoryId';
import {
    CategoryTreeResponseCategoriesCategoryIdFromJSON,
    CategoryTreeResponseCategoriesCategoryIdFromJSONTyped,
    CategoryTreeResponseCategoriesCategoryIdToJSON,
    CategoryTreeResponseCategoriesCategoryIdToJSONTyped,
} from './CategoryTreeResponseCategoriesCategoryId';

/**
 * A JSON object containing all category IDs and their relevant information.
 * @export
 * @interface CategoryTreeResponseCategories
 */
export interface CategoryTreeResponseCategories {
    /**
     * 
     * @type {CategoryTreeResponseCategoriesCategoryId}
     * @memberof CategoryTreeResponseCategories
     */
    categoryId?: CategoryTreeResponseCategoriesCategoryId;
}

/**
 * Check if a given object implements the CategoryTreeResponseCategories interface.
 */
export function instanceOfCategoryTreeResponseCategories(value: object): value is CategoryTreeResponseCategories {
    return true;
}

export function CategoryTreeResponseCategoriesFromJSON(json: any): CategoryTreeResponseCategories {
    return CategoryTreeResponseCategoriesFromJSONTyped(json, false);
}

export function CategoryTreeResponseCategoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTreeResponseCategories {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'] == null ? undefined : CategoryTreeResponseCategoriesCategoryIdFromJSON(json['categoryId']),
    };
}

export function CategoryTreeResponseCategoriesToJSON(json: any): CategoryTreeResponseCategories {
    return CategoryTreeResponseCategoriesToJSONTyped(json, false);
}

export function CategoryTreeResponseCategoriesToJSONTyped(value?: CategoryTreeResponseCategories | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryId': CategoryTreeResponseCategoriesCategoryIdToJSON(value['categoryId']),
    };
}

