/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryTreeResponseCategories } from './CategoryTreeResponseCategories';
import {
    CategoryTreeResponseCategoriesFromJSON,
    CategoryTreeResponseCategoriesFromJSONTyped,
    CategoryTreeResponseCategoriesToJSON,
    CategoryTreeResponseCategoriesToJSONTyped,
} from './CategoryTreeResponseCategories';

/**
 * 
 * @export
 * @interface CategoryTreeResponse
 */
export interface CategoryTreeResponse {
    /**
     * 
     * @type {CategoryTreeResponseCategories}
     * @memberof CategoryTreeResponse
     */
    categories?: CategoryTreeResponseCategories;
}

/**
 * Check if a given object implements the CategoryTreeResponse interface.
 */
export function instanceOfCategoryTreeResponse(value: object): value is CategoryTreeResponse {
    return true;
}

export function CategoryTreeResponseFromJSON(json: any): CategoryTreeResponse {
    return CategoryTreeResponseFromJSONTyped(json, false);
}

export function CategoryTreeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTreeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'categories': json['categories'] == null ? undefined : CategoryTreeResponseCategoriesFromJSON(json['categories']),
    };
}

export function CategoryTreeResponseToJSON(json: any): CategoryTreeResponse {
    return CategoryTreeResponseToJSONTyped(json, false);
}

export function CategoryTreeResponseToJSONTyped(value?: CategoryTreeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categories': CategoryTreeResponseCategoriesToJSON(value['categories']),
    };
}

