/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentSubmission } from './DocumentSubmission';
import {
    DocumentSubmissionFromJSON,
    DocumentSubmissionFromJSONTyped,
    DocumentSubmissionToJSON,
    DocumentSubmissionToJSONTyped,
} from './DocumentSubmission';

/**
 * 
 * @export
 * @interface ChangeMarginType
 */
export interface ChangeMarginType {
    /**
     * 
     * @type {string}
     * @memberof ChangeMarginType
     */
    accountId?: string;
    /**
     * 
     * @type {DocumentSubmission}
     * @memberof ChangeMarginType
     */
    documentSubmission?: DocumentSubmission;
    /**
     * 
     * @type {string}
     * @memberof ChangeMarginType
     */
    newMargin?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeMarginType
     */
    operation?: string;
}

/**
 * Check if a given object implements the ChangeMarginType interface.
 */
export function instanceOfChangeMarginType(value: object): value is ChangeMarginType {
    return true;
}

export function ChangeMarginTypeFromJSON(json: any): ChangeMarginType {
    return ChangeMarginTypeFromJSONTyped(json, false);
}

export function ChangeMarginTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeMarginType {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'documentSubmission': json['documentSubmission'] == null ? undefined : DocumentSubmissionFromJSON(json['documentSubmission']),
        'newMargin': json['newMargin'] == null ? undefined : json['newMargin'],
        'operation': json['operation'] == null ? undefined : json['operation'],
    };
}

export function ChangeMarginTypeToJSON(json: any): ChangeMarginType {
    return ChangeMarginTypeToJSONTyped(json, false);
}

export function ChangeMarginTypeToJSONTyped(value?: ChangeMarginType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'documentSubmission': DocumentSubmissionToJSON(value['documentSubmission']),
        'newMargin': value['newMargin'],
        'operation': value['operation'],
    };
}

