/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientPublicKeySetKeysInnerOneOf1
 */
export interface ClientPublicKeySetKeysInnerOneOf1 {
    /**
     * Algorithm
     * @type {string}
     * @memberof ClientPublicKeySetKeysInnerOneOf1
     */
    alg?: string;
    /**
     * Key ID
     * @type {string}
     * @memberof ClientPublicKeySetKeysInnerOneOf1
     */
    kid?: string;
    /**
     * Key type
     * @type {ClientPublicKeySetKeysInnerOneOf1KtyEnum}
     * @memberof ClientPublicKeySetKeysInnerOneOf1
     */
    kty?: ClientPublicKeySetKeysInnerOneOf1KtyEnum;
    /**
     * Public key use
     * @type {ClientPublicKeySetKeysInnerOneOf1UseEnum}
     * @memberof ClientPublicKeySetKeysInnerOneOf1
     */
    use?: ClientPublicKeySetKeysInnerOneOf1UseEnum;
    /**
     * Elliptic curve
     * @type {string}
     * @memberof ClientPublicKeySetKeysInnerOneOf1
     */
    crv?: string;
    /**
     * X coordinate
     * @type {string}
     * @memberof ClientPublicKeySetKeysInnerOneOf1
     */
    x?: string;
    /**
     * Y coordinate
     * @type {string}
     * @memberof ClientPublicKeySetKeysInnerOneOf1
     */
    y?: string;
}


/**
 * @export
 */
export const ClientPublicKeySetKeysInnerOneOf1KtyEnum = {
    Rsa: 'RSA',
    Ec: 'EC',
    Oct: 'oct'
} as const;
export type ClientPublicKeySetKeysInnerOneOf1KtyEnum = typeof ClientPublicKeySetKeysInnerOneOf1KtyEnum[keyof typeof ClientPublicKeySetKeysInnerOneOf1KtyEnum];

/**
 * @export
 */
export const ClientPublicKeySetKeysInnerOneOf1UseEnum = {
    Sig: 'sig',
    Enc: 'enc'
} as const;
export type ClientPublicKeySetKeysInnerOneOf1UseEnum = typeof ClientPublicKeySetKeysInnerOneOf1UseEnum[keyof typeof ClientPublicKeySetKeysInnerOneOf1UseEnum];


/**
 * Check if a given object implements the ClientPublicKeySetKeysInnerOneOf1 interface.
 */
export function instanceOfClientPublicKeySetKeysInnerOneOf1(value: object): value is ClientPublicKeySetKeysInnerOneOf1 {
    return true;
}

export function ClientPublicKeySetKeysInnerOneOf1FromJSON(json: any): ClientPublicKeySetKeysInnerOneOf1 {
    return ClientPublicKeySetKeysInnerOneOf1FromJSONTyped(json, false);
}

export function ClientPublicKeySetKeysInnerOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientPublicKeySetKeysInnerOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'alg': json['alg'] == null ? undefined : json['alg'],
        'kid': json['kid'] == null ? undefined : json['kid'],
        'kty': json['kty'] == null ? undefined : json['kty'],
        'use': json['use'] == null ? undefined : json['use'],
        'crv': json['crv'] == null ? undefined : json['crv'],
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
    };
}

export function ClientPublicKeySetKeysInnerOneOf1ToJSON(json: any): ClientPublicKeySetKeysInnerOneOf1 {
    return ClientPublicKeySetKeysInnerOneOf1ToJSONTyped(json, false);
}

export function ClientPublicKeySetKeysInnerOneOf1ToJSONTyped(value?: ClientPublicKeySetKeysInnerOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alg': value['alg'],
        'kid': value['kid'],
        'kty': value['kty'],
        'use': value['use'],
        'crv': value['crv'],
        'x': value['x'],
        'y': value['y'],
    };
}

