/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloseMdStreamRequest
 */
export interface CloseMdStreamRequest {
    /**
     * The IB contract ID of the instrument whose market data feed is to be unsubscribed.
     * @type {number}
     * @memberof CloseMdStreamRequest
     */
    conid?: number;
}

/**
 * Check if a given object implements the CloseMdStreamRequest interface.
 */
export function instanceOfCloseMdStreamRequest(value: object): value is CloseMdStreamRequest {
    return true;
}

export function CloseMdStreamRequestFromJSON(json: any): CloseMdStreamRequest {
    return CloseMdStreamRequestFromJSONTyped(json, false);
}

export function CloseMdStreamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseMdStreamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'conid': json['conid'] == null ? undefined : json['conid'],
    };
}

export function CloseMdStreamRequestToJSON(json: any): CloseMdStreamRequest {
    return CloseMdStreamRequestToJSONTyped(json, false);
}

export function CloseMdStreamRequestToJSONTyped(value?: CloseMdStreamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conid': value['conid'],
    };
}

