/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReport } from './ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReport';
import {
    ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReportFromJSON,
    ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReportFromJSONTyped,
    ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReportToJSON,
    ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReportToJSONTyped,
} from './ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReport';
import type { InstructionErrorResultAllOfError } from './InstructionErrorResultAllOfError';
import {
    InstructionErrorResultAllOfErrorFromJSON,
    InstructionErrorResultAllOfErrorFromJSONTyped,
    InstructionErrorResultAllOfErrorToJSON,
    InstructionErrorResultAllOfErrorToJSONTyped,
} from './InstructionErrorResultAllOfError';

/**
 * 
 * @export
 * @interface ComplexAssetTransferPollingResult
 */
export interface ComplexAssetTransferPollingResult {
    /**
     * 
     * @type {number}
     * @memberof ComplexAssetTransferPollingResult
     */
    clientInstructionId: number;
    /**
     * 
     * @type {string}
     * @memberof ComplexAssetTransferPollingResult
     */
    description?: string;
    /**
     * 
     * @type {InstructionErrorResultAllOfError}
     * @memberof ComplexAssetTransferPollingResult
     */
    error?: InstructionErrorResultAllOfError;
    /**
     * 
     * @type {number}
     * @memberof ComplexAssetTransferPollingResult
     */
    ibReferenceId?: number;
    /**
     * 
     * @type {number}
     * @memberof ComplexAssetTransferPollingResult
     */
    instructionId: number;
    /**
     * 
     * @type {ComplexAssetTransferPollingResultInstructionStatusEnum}
     * @memberof ComplexAssetTransferPollingResult
     */
    instructionStatus: ComplexAssetTransferPollingResultInstructionStatusEnum;
    /**
     * 
     * @type {ComplexAssetTransferPollingResultInstructionTypeEnum}
     * @memberof ComplexAssetTransferPollingResult
     */
    instructionType: ComplexAssetTransferPollingResultInstructionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ComplexAssetTransferPollingResult
     */
    clearingState: string;
    /**
     * 
     * @type {Array<ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReport>}
     * @memberof ComplexAssetTransferPollingResult
     */
    consolidatedComplexAssetTransferReport?: Array<ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReport>;
}


/**
 * @export
 */
export const ComplexAssetTransferPollingResultInstructionStatusEnum = {
    Pending: 'PENDING',
    Rejected: 'REJECTED',
    Processed: 'PROCESSED'
} as const;
export type ComplexAssetTransferPollingResultInstructionStatusEnum = typeof ComplexAssetTransferPollingResultInstructionStatusEnum[keyof typeof ComplexAssetTransferPollingResultInstructionStatusEnum];

/**
 * @export
 */
export const ComplexAssetTransferPollingResultInstructionTypeEnum = {
    AchInstruction: 'ACH_INSTRUCTION',
    CancelInstruction: 'CANCEL_INSTRUCTION',
    ComplexAssetTransfer: 'COMPLEX_ASSET_TRANSFER',
    DeleteBankInstruction: 'DELETE_BANK_INSTRUCTION',
    Deposit: 'DEPOSIT',
    Dwac: 'DWAC',
    ExternalPositionTransfer: 'EXTERNAL_POSITION_TRANSFER',
    Fop: 'FOP',
    QueryRecentInstructions: 'QUERY_RECENT_INSTRUCTIONS',
    QueryWithdrawableFunds: 'QUERY_WITHDRAWABLE_FUNDS',
    InternalPositionTransfer: 'INTERNAL_POSITION_TRANSFER',
    InternalCashTransfer: 'INTERNAL_CASH_TRANSFER',
    MicroAmount: 'MICRO_AMOUNT',
    PredefinedDestinationInstruction: 'PREDEFINED_DESTINATION_INSTRUCTION',
    TraditionalBankInstructionVerification: 'TRADITIONAL_BANK_INSTRUCTION_VERIFICATION',
    Withdrawal: 'WITHDRAWAL',
    QueryIraContributions: 'QUERY_IRA_CONTRIBUTIONS',
    EddaInstruction: 'EDDA_INSTRUCTION',
    QueryRecentRecurringEvents: 'QUERY_RECENT_RECURRING_EVENTS',
    QueryRecurringInstructions: 'QUERY_RECURRING_INSTRUCTIONS',
    QueryAccountBalances: 'QUERY_ACCOUNT_BALANCES',
    QueryBankInstruction: 'QUERY_BANK_INSTRUCTION',
    QueryWithdrawableCashEquity: 'QUERY_WITHDRAWABLE_CASH_EQUITY'
} as const;
export type ComplexAssetTransferPollingResultInstructionTypeEnum = typeof ComplexAssetTransferPollingResultInstructionTypeEnum[keyof typeof ComplexAssetTransferPollingResultInstructionTypeEnum];


/**
 * Check if a given object implements the ComplexAssetTransferPollingResult interface.
 */
export function instanceOfComplexAssetTransferPollingResult(value: object): value is ComplexAssetTransferPollingResult {
    if (!('clientInstructionId' in value) || value['clientInstructionId'] === undefined) return false;
    if (!('instructionId' in value) || value['instructionId'] === undefined) return false;
    if (!('instructionStatus' in value) || value['instructionStatus'] === undefined) return false;
    if (!('instructionType' in value) || value['instructionType'] === undefined) return false;
    if (!('clearingState' in value) || value['clearingState'] === undefined) return false;
    return true;
}

export function ComplexAssetTransferPollingResultFromJSON(json: any): ComplexAssetTransferPollingResult {
    return ComplexAssetTransferPollingResultFromJSONTyped(json, false);
}

export function ComplexAssetTransferPollingResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexAssetTransferPollingResult {
    if (json == null) {
        return json;
    }
    return {
        
        'clientInstructionId': json['clientInstructionId'],
        'description': json['description'] == null ? undefined : json['description'],
        'error': json['error'] == null ? undefined : InstructionErrorResultAllOfErrorFromJSON(json['error']),
        'ibReferenceId': json['ibReferenceId'] == null ? undefined : json['ibReferenceId'],
        'instructionId': json['instructionId'],
        'instructionStatus': json['instructionStatus'],
        'instructionType': json['instructionType'],
        'clearingState': json['clearingState'],
        'consolidatedComplexAssetTransferReport': json['consolidatedComplexAssetTransferReport'] == null ? undefined : ((json['consolidatedComplexAssetTransferReport'] as Array<any>).map(ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReportFromJSON)),
    };
}

export function ComplexAssetTransferPollingResultToJSON(json: any): ComplexAssetTransferPollingResult {
    return ComplexAssetTransferPollingResultToJSONTyped(json, false);
}

export function ComplexAssetTransferPollingResultToJSONTyped(value?: ComplexAssetTransferPollingResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientInstructionId': value['clientInstructionId'],
        'description': value['description'],
        'error': InstructionErrorResultAllOfErrorToJSON(value['error']),
        'ibReferenceId': value['ibReferenceId'],
        'instructionId': value['instructionId'],
        'instructionStatus': value['instructionStatus'],
        'instructionType': value['instructionType'],
        'clearingState': value['clearingState'],
        'consolidatedComplexAssetTransferReport': value['consolidatedComplexAssetTransferReport'] == null ? undefined : ((value['consolidatedComplexAssetTransferReport'] as Array<any>).map(ComplexAssetTransferPollingResultAllOfConsolidatedComplexAssetTransferReportToJSON)),
    };
}

