/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractRulesOrderDefaultsLMT
 */
export interface ContractRulesOrderDefaultsLMT {
    /**
     * Indicates a Limit Price default value.
     * @type {string}
     * @memberof ContractRulesOrderDefaultsLMT
     */
    LP?: string;
}

/**
 * Check if a given object implements the ContractRulesOrderDefaultsLMT interface.
 */
export function instanceOfContractRulesOrderDefaultsLMT(value: object): value is ContractRulesOrderDefaultsLMT {
    return true;
}

export function ContractRulesOrderDefaultsLMTFromJSON(json: any): ContractRulesOrderDefaultsLMT {
    return ContractRulesOrderDefaultsLMTFromJSONTyped(json, false);
}

export function ContractRulesOrderDefaultsLMTFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractRulesOrderDefaultsLMT {
    if (json == null) {
        return json;
    }
    return {
        
        'LP': json['LP'] == null ? undefined : json['LP'],
    };
}

export function ContractRulesOrderDefaultsLMTToJSON(json: any): ContractRulesOrderDefaultsLMT {
    return ContractRulesOrderDefaultsLMTToJSONTyped(json, false);
}

export function ContractRulesOrderDefaultsLMTToJSONTyped(value?: ContractRulesOrderDefaultsLMT | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'LP': value['LP'],
    };
}

