/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeliveryOptionsEInner } from './DeliveryOptionsEInner';
import {
    DeliveryOptionsEInnerFromJSON,
    DeliveryOptionsEInnerFromJSONTyped,
    DeliveryOptionsEInnerToJSON,
    DeliveryOptionsEInnerToJSONTyped,
} from './DeliveryOptionsEInner';

/**
 * 
 * @export
 * @interface DeliveryOptions
 */
export interface DeliveryOptions {
    /**
     * Returns an array of device information.
     * @type {Array<DeliveryOptionsEInner>}
     * @memberof DeliveryOptions
     */
    E?: Array<DeliveryOptionsEInner>;
    /**
     * Email option is enabled or not.
     * @type {number}
     * @memberof DeliveryOptions
     */
    M?: number;
}

/**
 * Check if a given object implements the DeliveryOptions interface.
 */
export function instanceOfDeliveryOptions(value: object): value is DeliveryOptions {
    return true;
}

export function DeliveryOptionsFromJSON(json: any): DeliveryOptions {
    return DeliveryOptionsFromJSONTyped(json, false);
}

export function DeliveryOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'E': json['E'] == null ? undefined : ((json['E'] as Array<any>).map(DeliveryOptionsEInnerFromJSON)),
        'M': json['M'] == null ? undefined : json['M'],
    };
}

export function DeliveryOptionsToJSON(json: any): DeliveryOptions {
    return DeliveryOptionsToJSONTyped(json, false);
}

export function DeliveryOptionsToJSONTyped(value?: DeliveryOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'E': value['E'] == null ? undefined : ((value['E'] as Array<any>).map(DeliveryOptionsEInnerToJSON)),
        'M': value['M'],
    };
}

