/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DVPInstruction
 */
export interface DVPInstruction {
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    accountID?: string;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    agentID?: string;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    agentName?: string;
    /**
     * 
     * @type {DVPInstructionAssetClassEnum}
     * @memberof DVPInstruction
     */
    assetClass?: DVPInstructionAssetClassEnum;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    brokerCode?: string;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    dayDoID?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DVPInstruction
     */
    _default?: boolean;
    /**
     * 
     * @type {DVPInstructionExchangeEnum}
     * @memberof DVPInstruction
     */
    exchange?: DVPInstructionExchangeEnum;
    /**
     * 
     * @type {Date}
     * @memberof DVPInstruction
     */
    expiry?: Date;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    externalAccountID?: string;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    firmID?: string;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DVPInstruction
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DVPInstruction
     */
    prepayCommission?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DVPInstruction
     */
    prepayTax?: boolean;
    /**
     * 
     * @type {DVPInstructionRoleEnum}
     * @memberof DVPInstruction
     */
    role?: DVPInstructionRoleEnum;
    /**
     * 
     * @type {DVPInstructionTxGroupCodeEnum}
     * @memberof DVPInstruction
     */
    txGroupCode?: DVPInstructionTxGroupCodeEnum;
    /**
     * 
     * @type {DVPInstructionTypeEnum}
     * @memberof DVPInstruction
     */
    type?: DVPInstructionTypeEnum;
}


/**
 * @export
 */
export const DVPInstructionAssetClassEnum = {
    Bill: 'BILL',
    Bond: 'BOND',
    Cash: 'CASH',
    Cfd: 'CFD',
    Comb: 'COMB',
    Fop: 'FOP',
    Fund: 'FUND',
    Fut: 'FUT',
    Opt: 'OPT',
    Ssf: 'SSF',
    Stk: 'STK',
    War: 'WAR',
    Mrgn: 'MRGN',
    Clp: 'CLP'
} as const;
export type DVPInstructionAssetClassEnum = typeof DVPInstructionAssetClassEnum[keyof typeof DVPInstructionAssetClassEnum];

/**
 * @export
 */
export const DVPInstructionExchangeEnum = {
    Nyse: 'NYSE',
    Amex: 'AMEX',
    Nasdaq: 'NASDAQ',
    Cboe: 'CBOE',
    Ise: 'ISE',
    Box: 'BOX',
    Phlx: 'PHLX',
    Pse: 'PSE'
} as const;
export type DVPInstructionExchangeEnum = typeof DVPInstructionExchangeEnum[keyof typeof DVPInstructionExchangeEnum];

/**
 * @export
 */
export const DVPInstructionRoleEnum = {
    E: 'E',
    C: 'C',
    B: 'B'
} as const;
export type DVPInstructionRoleEnum = typeof DVPInstructionRoleEnum[keyof typeof DVPInstructionRoleEnum];

/**
 * @export
 */
export const DVPInstructionTxGroupCodeEnum = {
    G: 'G',
    Z: 'Z',
    R: 'R',
    N: 'N'
} as const;
export type DVPInstructionTxGroupCodeEnum = typeof DVPInstructionTxGroupCodeEnum[keyof typeof DVPInstructionTxGroupCodeEnum];

/**
 * @export
 */
export const DVPInstructionTypeEnum = {
    Dtcid: 'DTCID',
    Nscc: 'NSCC',
    Cmta: 'CMTA',
    Gus: 'GUS',
    Occssf: 'OCCSSF'
} as const;
export type DVPInstructionTypeEnum = typeof DVPInstructionTypeEnum[keyof typeof DVPInstructionTypeEnum];


/**
 * Check if a given object implements the DVPInstruction interface.
 */
export function instanceOfDVPInstruction(value: object): value is DVPInstruction {
    return true;
}

export function DVPInstructionFromJSON(json: any): DVPInstruction {
    return DVPInstructionFromJSONTyped(json, false);
}

export function DVPInstructionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DVPInstruction {
    if (json == null) {
        return json;
    }
    return {
        
        'accountID': json['accountID'] == null ? undefined : json['accountID'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'agentID': json['agentID'] == null ? undefined : json['agentID'],
        'agentName': json['agentName'] == null ? undefined : json['agentName'],
        'assetClass': json['assetClass'] == null ? undefined : json['assetClass'],
        'brokerCode': json['brokerCode'] == null ? undefined : json['brokerCode'],
        'dayDoID': json['dayDoID'] == null ? undefined : json['dayDoID'],
        '_default': json['default'] == null ? undefined : json['default'],
        'exchange': json['exchange'] == null ? undefined : json['exchange'],
        'expiry': json['expiry'] == null ? undefined : (new Date(json['expiry'])),
        'externalAccountID': json['externalAccountID'] == null ? undefined : json['externalAccountID'],
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'firmID': json['firmID'] == null ? undefined : json['firmID'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'prepayCommission': json['prepayCommission'] == null ? undefined : json['prepayCommission'],
        'prepayTax': json['prepayTax'] == null ? undefined : json['prepayTax'],
        'role': json['role'] == null ? undefined : json['role'],
        'txGroupCode': json['txGroupCode'] == null ? undefined : json['txGroupCode'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function DVPInstructionToJSON(json: any): DVPInstruction {
    return DVPInstructionToJSONTyped(json, false);
}

export function DVPInstructionToJSONTyped(value?: DVPInstruction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountID': value['accountID'],
        'accountName': value['accountName'],
        'agentID': value['agentID'],
        'agentName': value['agentName'],
        'assetClass': value['assetClass'],
        'brokerCode': value['brokerCode'],
        'dayDoID': value['dayDoID'],
        'default': value['_default'],
        'exchange': value['exchange'],
        'expiry': value['expiry'] == null ? value['expiry'] : value['expiry'].toISOString().substring(0,10),
        'externalAccountID': value['externalAccountID'],
        'externalId': value['externalId'],
        'firmID': value['firmID'],
        'id': value['id'],
        'name': value['name'],
        'prepayCommission': value['prepayCommission'],
        'prepayTax': value['prepayTax'],
        'role': value['role'],
        'txGroupCode': value['txGroupCode'],
        'type': value['type'],
    };
}

