/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <ul><li>exchange-bundles - query most up to date list of exchange-bundles for tradingPermissions</li><li>business-and-occupation - list of occupation and employerBusiness for employmentDetails</li><li>employee-track - query most up to date companyId for account. For affiliation details, if company has an existing IBKR Employee Track account</li><li>fin-info-ranges - query most up to date range IDs by currency for annualNetIncome, netWorth, liquidNetWorth</li><li>acats - query most up to date values for brokerId and brokerName. Used if funding via US ACATS extPositionsTransfers</li><li>aton - query most up to date values for brokerId and brokerName. Used if funding via US ACATS extPositionsTransfers</li><li>market-data - query most up to date values for brokerId and brokerName. Used if funding via ATON Canada extPositionsTransfers</li><li>edd-avt - query questions associated with EDD (Enhanced Due Diligence) or AVT (Additional Verification) tasks assigned to an account</li><li>prohibited-country - view list of prohibited countries. Applicants that reside in prohibited country are restricted from opening an account with IBKR. Error will be thrown IF legalResidenceCountry, OR country (included within Residence, mailingAddress and employerAddress, taxResidency node) is a prohibited country</li><li>employee-plans - view EPA that are linked to master account (applicable IF offering SEP IRA accounts)</li><li>questionnaires - obtain list of questionnaires</li><li>security-questions - obtain list of questions supported for IBKR security questions</li><li>quiz-questions - obtain list of questions associated with IBKR knowledge assessment</li><li>wire-instructions - obtain list of wire instructions</li><li>product-country-bundles - obtain list of product country bundles</li></ul>
 * @export
 */
export const EnumerationType = {
    ExchangeBundles: 'exchange-bundles',
    BusinessAndOccupation: 'business-and-occupation',
    EmployeeTrack: 'employee-track',
    FinInfoRanges: 'fin-info-ranges',
    Acats: 'acats',
    Aton: 'aton',
    MarketData: 'market-data',
    EddAvt: 'edd-avt',
    ProhibitedCountry: 'prohibited-country',
    EmployeePlans: 'employee-plans',
    Questionnaires: 'questionnaires',
    SecurityQuestions: 'security-questions',
    QuizQuestions: 'quiz-questions',
    WireInstructions: 'wire-instructions',
    ProductCountryBundles: 'product-country-bundles'
} as const;
export type EnumerationType = typeof EnumerationType[keyof typeof EnumerationType];


export function instanceOfEnumerationType(value: any): boolean {
    for (const key in EnumerationType) {
        if (Object.prototype.hasOwnProperty.call(EnumerationType, key)) {
            if (EnumerationType[key as keyof typeof EnumerationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EnumerationTypeFromJSON(json: any): EnumerationType {
    return EnumerationTypeFromJSONTyped(json, false);
}

export function EnumerationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumerationType {
    return json as EnumerationType;
}

export function EnumerationTypeToJSON(value?: EnumerationType | null): any {
    return value as any;
}

export function EnumerationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): EnumerationType {
    return value as EnumerationType;
}

