/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeAccess
 */
export interface ExchangeAccess {
    /**
     * 
     * @type {ExchangeAccessAssetClassEnum}
     * @memberof ExchangeAccess
     */
    assetClass?: ExchangeAccessAssetClassEnum;
    /**
     * 
     * @type {ExchangeAccessExchangeEnum}
     * @memberof ExchangeAccess
     */
    exchange?: ExchangeAccessExchangeEnum;
}


/**
 * @export
 */
export const ExchangeAccessAssetClassEnum = {
    Bill: 'BILL',
    Bond: 'BOND',
    Cash: 'CASH',
    Cfd: 'CFD',
    Comb: 'COMB',
    Fop: 'FOP',
    Fund: 'FUND',
    Fut: 'FUT',
    Opt: 'OPT',
    Ssf: 'SSF',
    Stk: 'STK',
    War: 'WAR',
    Mrgn: 'MRGN',
    Clp: 'CLP'
} as const;
export type ExchangeAccessAssetClassEnum = typeof ExchangeAccessAssetClassEnum[keyof typeof ExchangeAccessAssetClassEnum];

/**
 * @export
 */
export const ExchangeAccessExchangeEnum = {
    Nyse: 'NYSE',
    Amex: 'AMEX',
    Nasdaq: 'NASDAQ',
    Cboe: 'CBOE',
    Ise: 'ISE',
    Box: 'BOX',
    Phlx: 'PHLX',
    Pse: 'PSE'
} as const;
export type ExchangeAccessExchangeEnum = typeof ExchangeAccessExchangeEnum[keyof typeof ExchangeAccessExchangeEnum];


/**
 * Check if a given object implements the ExchangeAccess interface.
 */
export function instanceOfExchangeAccess(value: object): value is ExchangeAccess {
    return true;
}

export function ExchangeAccessFromJSON(json: any): ExchangeAccess {
    return ExchangeAccessFromJSONTyped(json, false);
}

export function ExchangeAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeAccess {
    if (json == null) {
        return json;
    }
    return {
        
        'assetClass': json['assetClass'] == null ? undefined : json['assetClass'],
        'exchange': json['exchange'] == null ? undefined : json['exchange'],
    };
}

export function ExchangeAccessToJSON(json: any): ExchangeAccess {
    return ExchangeAccessToJSONTyped(json, false);
}

export function ExchangeAccessToJSONTyped(value?: ExchangeAccess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assetClass': value['assetClass'],
        'exchange': value['exchange'],
    };
}

