/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FailedTickleResponse
 */
export interface FailedTickleResponse {
    /**
     * reason why tickle was accepted by not processed
     * @type {string}
     * @memberof FailedTickleResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the FailedTickleResponse interface.
 */
export function instanceOfFailedTickleResponse(value: object): value is FailedTickleResponse {
    return true;
}

export function FailedTickleResponseFromJSON(json: any): FailedTickleResponse {
    return FailedTickleResponseFromJSONTyped(json, false);
}

export function FailedTickleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FailedTickleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function FailedTickleResponseToJSON(json: any): FailedTickleResponse {
    return FailedTickleResponseToJSONTyped(json, false);
}

export function FailedTickleResponseToJSONTyped(value?: FailedTickleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

