/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilePayload
 */
export interface FilePayload {
    /**
     * Includes document encoded in base64.
     * @type {string}
     * @memberof FilePayload
     */
    data: string;
    /**
     * Format of the file.
     * @type {string}
     * @memberof FilePayload
     */
    mimeType: string;
}

/**
 * Check if a given object implements the FilePayload interface.
 */
export function instanceOfFilePayload(value: object): value is FilePayload {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    return true;
}

export function FilePayloadFromJSON(json: any): FilePayload {
    return FilePayloadFromJSONTyped(json, false);
}

export function FilePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'mimeType': json['mimeType'],
    };
}

export function FilePayloadToJSON(json: any): FilePayload {
    return FilePayloadToJSONTyped(json, false);
}

export function FilePayloadToJSONTyped(value?: FilePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'mimeType': value['mimeType'],
    };
}

