/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SourceOfIncomeType } from './SourceOfIncomeType';
import {
    SourceOfIncomeTypeFromJSON,
    SourceOfIncomeTypeFromJSONTyped,
    SourceOfIncomeTypeToJSON,
    SourceOfIncomeTypeToJSONTyped,
} from './SourceOfIncomeType';
import type { AssetExperience } from './AssetExperience';
import {
    AssetExperienceFromJSON,
    AssetExperienceFromJSONTyped,
    AssetExperienceToJSON,
    AssetExperienceToJSONTyped,
} from './AssetExperience';
import type { SOIQuestionnaire } from './SOIQuestionnaire';
import {
    SOIQuestionnaireFromJSON,
    SOIQuestionnaireFromJSONTyped,
    SOIQuestionnaireToJSON,
    SOIQuestionnaireToJSONTyped,
} from './SOIQuestionnaire';
import type { QuestionnaireType } from './QuestionnaireType';
import {
    QuestionnaireTypeFromJSON,
    QuestionnaireTypeFromJSONTyped,
    QuestionnaireTypeToJSON,
    QuestionnaireTypeToJSONTyped,
} from './QuestionnaireType';
import type { SourceOfWealthType } from './SourceOfWealthType';
import {
    SourceOfWealthTypeFromJSON,
    SourceOfWealthTypeFromJSONTyped,
    SourceOfWealthTypeToJSON,
    SourceOfWealthTypeToJSONTyped,
} from './SourceOfWealthType';

/**
 * 
 * @export
 * @interface FinancialInformation
 */
export interface FinancialInformation {
    /**
     * 
     * @type {Array<SourceOfIncomeType>}
     * @memberof FinancialInformation
     */
    additionalSourcesOfIncome?: Array<SourceOfIncomeType>;
    /**
     * 
     * @type {number}
     * @memberof FinancialInformation
     */
    annualNetIncome?: number;
    /**
     * 
     * @type {Array<AssetExperience>}
     * @memberof FinancialInformation
     */
    investmentExperience?: Array<AssetExperience>;
    /**
     * 
     * @type {Array<FinancialInformationInvestmentObjectivesEnum>}
     * @memberof FinancialInformation
     */
    investmentObjectives?: Array<FinancialInformationInvestmentObjectivesEnum>;
    /**
     * 
     * @type {number}
     * @memberof FinancialInformation
     */
    liquidNetWorth?: number;
    /**
     * 
     * @type {number}
     * @memberof FinancialInformation
     */
    netWorth?: number;
    /**
     * 
     * @type {Array<QuestionnaireType>}
     * @memberof FinancialInformation
     */
    questionnaires?: Array<QuestionnaireType>;
    /**
     * 
     * @type {SOIQuestionnaire}
     * @memberof FinancialInformation
     */
    soiQuestionnaire?: SOIQuestionnaire;
    /**
     * 
     * @type {string}
     * @memberof FinancialInformation
     */
    sourceOfFunds?: string;
    /**
     * 
     * @type {Array<SourceOfWealthType>}
     * @memberof FinancialInformation
     */
    sourcesOfWealth?: Array<SourceOfWealthType>;
    /**
     * 
     * @type {number}
     * @memberof FinancialInformation
     */
    totalAssets?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FinancialInformation
     */
    translated?: boolean;
}


/**
 * @export
 */
export const FinancialInformationInvestmentObjectivesEnum = {
    Trading: 'Trading',
    Growth: 'Growth',
    Speculation: 'Speculation',
    Hedging: 'Hedging',
    Preservation: 'Preservation',
    Income: 'Income'
} as const;
export type FinancialInformationInvestmentObjectivesEnum = typeof FinancialInformationInvestmentObjectivesEnum[keyof typeof FinancialInformationInvestmentObjectivesEnum];


/**
 * Check if a given object implements the FinancialInformation interface.
 */
export function instanceOfFinancialInformation(value: object): value is FinancialInformation {
    return true;
}

export function FinancialInformationFromJSON(json: any): FinancialInformation {
    return FinancialInformationFromJSONTyped(json, false);
}

export function FinancialInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalSourcesOfIncome': json['additionalSourcesOfIncome'] == null ? undefined : ((json['additionalSourcesOfIncome'] as Array<any>).map(SourceOfIncomeTypeFromJSON)),
        'annualNetIncome': json['annualNetIncome'] == null ? undefined : json['annualNetIncome'],
        'investmentExperience': json['investmentExperience'] == null ? undefined : ((json['investmentExperience'] as Array<any>).map(AssetExperienceFromJSON)),
        'investmentObjectives': json['investmentObjectives'] == null ? undefined : json['investmentObjectives'],
        'liquidNetWorth': json['liquidNetWorth'] == null ? undefined : json['liquidNetWorth'],
        'netWorth': json['netWorth'] == null ? undefined : json['netWorth'],
        'questionnaires': json['questionnaires'] == null ? undefined : ((json['questionnaires'] as Array<any>).map(QuestionnaireTypeFromJSON)),
        'soiQuestionnaire': json['soiQuestionnaire'] == null ? undefined : SOIQuestionnaireFromJSON(json['soiQuestionnaire']),
        'sourceOfFunds': json['sourceOfFunds'] == null ? undefined : json['sourceOfFunds'],
        'sourcesOfWealth': json['sourcesOfWealth'] == null ? undefined : ((json['sourcesOfWealth'] as Array<any>).map(SourceOfWealthTypeFromJSON)),
        'totalAssets': json['totalAssets'] == null ? undefined : json['totalAssets'],
        'translated': json['translated'] == null ? undefined : json['translated'],
    };
}

export function FinancialInformationToJSON(json: any): FinancialInformation {
    return FinancialInformationToJSONTyped(json, false);
}

export function FinancialInformationToJSONTyped(value?: FinancialInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additionalSourcesOfIncome': value['additionalSourcesOfIncome'] == null ? undefined : ((value['additionalSourcesOfIncome'] as Array<any>).map(SourceOfIncomeTypeToJSON)),
        'annualNetIncome': value['annualNetIncome'],
        'investmentExperience': value['investmentExperience'] == null ? undefined : ((value['investmentExperience'] as Array<any>).map(AssetExperienceToJSON)),
        'investmentObjectives': value['investmentObjectives'],
        'liquidNetWorth': value['liquidNetWorth'],
        'netWorth': value['netWorth'],
        'questionnaires': value['questionnaires'] == null ? undefined : ((value['questionnaires'] as Array<any>).map(QuestionnaireTypeToJSON)),
        'soiQuestionnaire': SOIQuestionnaireToJSON(value['soiQuestionnaire']),
        'sourceOfFunds': value['sourceOfFunds'],
        'sourcesOfWealth': value['sourcesOfWealth'] == null ? undefined : ((value['sourcesOfWealth'] as Array<any>).map(SourceOfWealthTypeToJSON)),
        'totalAssets': value['totalAssets'],
        'translated': value['translated'],
    };
}

