/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TradingInstrument } from './TradingInstrument';
import {
    TradingInstrumentFromJSON,
    TradingInstrumentFromJSONTyped,
    TradingInstrumentToJSON,
    TradingInstrumentToJSONTyped,
} from './TradingInstrument';

/**
 * 
 * @export
 * @interface FopInstruction
 */
export interface FopInstruction {
    /**
     * 
     * @type {string}
     * @memberof FopInstruction
     */
    accountId: string;
    /**
     * 
     * @type {number}
     * @memberof FopInstruction
     */
    clientInstructionId: number;
    /**
     * 
     * @type {string}
     * @memberof FopInstruction
     */
    contraBrokerAccountId: string;
    /**
     * 
     * @type {string}
     * @memberof FopInstruction
     */
    contraBrokerDtcCode: string;
    /**
     * 
     * @type {FopInstructionDirectionEnum}
     * @memberof FopInstruction
     */
    direction: FopInstructionDirectionEnum;
    /**
     * 
     * @type {number}
     * @memberof FopInstruction
     */
    quantity: number;
    /**
     * 
     * @type {TradingInstrument}
     * @memberof FopInstruction
     */
    tradingInstrument: TradingInstrument;
}


/**
 * @export
 */
export const FopInstructionDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FopInstructionDirectionEnum = typeof FopInstructionDirectionEnum[keyof typeof FopInstructionDirectionEnum];


/**
 * Check if a given object implements the FopInstruction interface.
 */
export function instanceOfFopInstruction(value: object): value is FopInstruction {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('clientInstructionId' in value) || value['clientInstructionId'] === undefined) return false;
    if (!('contraBrokerAccountId' in value) || value['contraBrokerAccountId'] === undefined) return false;
    if (!('contraBrokerDtcCode' in value) || value['contraBrokerDtcCode'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('tradingInstrument' in value) || value['tradingInstrument'] === undefined) return false;
    return true;
}

export function FopInstructionFromJSON(json: any): FopInstruction {
    return FopInstructionFromJSONTyped(json, false);
}

export function FopInstructionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FopInstruction {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'clientInstructionId': json['clientInstructionId'],
        'contraBrokerAccountId': json['contraBrokerAccountId'],
        'contraBrokerDtcCode': json['contraBrokerDtcCode'],
        'direction': json['direction'],
        'quantity': json['quantity'],
        'tradingInstrument': TradingInstrumentFromJSON(json['tradingInstrument']),
    };
}

export function FopInstructionToJSON(json: any): FopInstruction {
    return FopInstructionToJSONTyped(json, false);
}

export function FopInstructionToJSONTyped(value?: FopInstruction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'clientInstructionId': value['clientInstructionId'],
        'contraBrokerAccountId': value['contraBrokerAccountId'],
        'contraBrokerDtcCode': value['contraBrokerDtcCode'],
        'direction': value['direction'],
        'quantity': value['quantity'],
        'tradingInstrument': TradingInstrumentToJSON(value['tradingInstrument']),
    };
}

