/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForecastDetailsResponse
 */
export interface ForecastDetailsResponse {
    /**
     * The affiliated market category declared in /forecast/category/tree.
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    category?: string;
    /**
     * Contract identifier of "no" contract
     * @type {number}
     * @memberof ForecastDetailsResponse
     */
    conid_no?: number;
    /**
     * Contract identifier of "yes" contract
     * @type {number}
     * @memberof ForecastDetailsResponse
     */
    conid_yes?: number;
    /**
     * Contract exchange.
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    exchange?: string;
    /**
     * Contract expiration date in YYYYMMDD format.
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    expiration?: string;
    /**
     * Logo category to use in logo service to get image.
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    logo_category?: string;
    /**
     * name of contract's market.
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    market_name?: string;
    /**
     * measured period
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    measured_period?: string;
    /**
     * Ratio of payout scaling.
     * @type {number}
     * @memberof ForecastDetailsResponse
     */
    payout?: number;
    /**
     * Contract question (i.e. "Will this happen on this date?")
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    question?: string;
    /**
     * "Y" or "N", yes or no contract.
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    side?: string;
    /**
     * Contract strike.
     * @type {number}
     * @memberof ForecastDetailsResponse
     */
    strike?: number;
    /**
     * Strike label to display.
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    strike_label?: string;
    /**
     * Contract symbol.
     * @type {string}
     * @memberof ForecastDetailsResponse
     */
    symbol?: string;
    /**
     * Immediate underlier to contract (i.e. future conid for FOPs)
     * @type {number}
     * @memberof ForecastDetailsResponse
     */
    underlying_conid?: number;
}

/**
 * Check if a given object implements the ForecastDetailsResponse interface.
 */
export function instanceOfForecastDetailsResponse(value: object): value is ForecastDetailsResponse {
    return true;
}

export function ForecastDetailsResponseFromJSON(json: any): ForecastDetailsResponse {
    return ForecastDetailsResponseFromJSONTyped(json, false);
}

export function ForecastDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastDetailsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'conid_no': json['conid_no'] == null ? undefined : json['conid_no'],
        'conid_yes': json['conid_yes'] == null ? undefined : json['conid_yes'],
        'exchange': json['exchange'] == null ? undefined : json['exchange'],
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'logo_category': json['logo_category'] == null ? undefined : json['logo_category'],
        'market_name': json['market_name'] == null ? undefined : json['market_name'],
        'measured_period': json['measured_period'] == null ? undefined : json['measured_period'],
        'payout': json['payout'] == null ? undefined : json['payout'],
        'question': json['question'] == null ? undefined : json['question'],
        'side': json['side'] == null ? undefined : json['side'],
        'strike': json['strike'] == null ? undefined : json['strike'],
        'strike_label': json['strike_label'] == null ? undefined : json['strike_label'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'underlying_conid': json['underlying_conid'] == null ? undefined : json['underlying_conid'],
    };
}

export function ForecastDetailsResponseToJSON(json: any): ForecastDetailsResponse {
    return ForecastDetailsResponseToJSONTyped(json, false);
}

export function ForecastDetailsResponseToJSONTyped(value?: ForecastDetailsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'conid_no': value['conid_no'],
        'conid_yes': value['conid_yes'],
        'exchange': value['exchange'],
        'expiration': value['expiration'],
        'logo_category': value['logo_category'],
        'market_name': value['market_name'],
        'measured_period': value['measured_period'],
        'payout': value['payout'],
        'question': value['question'],
        'side': value['side'],
        'strike': value['strike'],
        'strike_label': value['strike_label'],
        'symbol': value['symbol'],
        'underlying_conid': value['underlying_conid'],
    };
}

