/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalTaxForm } from './LocalTaxForm';
import {
    LocalTaxFormFromJSON,
    LocalTaxFormFromJSONTyped,
    LocalTaxFormToJSON,
    LocalTaxFormToJSONTyped,
} from './LocalTaxForm';

/**
 * 
 * @export
 * @interface FormW9
 */
export interface FormW9 {
    /**
     * 
     * @type {boolean}
     * @memberof FormW9
     */
    blankForm?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FormW9
     */
    businessName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FormW9
     */
    cert1?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FormW9
     */
    cert2?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FormW9
     */
    cert3?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FormW9
     */
    cert4?: boolean;
    /**
     * 
     * @type {FormW9CustomerTypeEnum}
     * @memberof FormW9
     */
    customerType?: FormW9CustomerTypeEnum;
    /**
     * 
     * @type {Array<LocalTaxForm>}
     * @memberof FormW9
     */
    localTaxForms?: Array<LocalTaxForm>;
    /**
     * 
     * @type {string}
     * @memberof FormW9
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FormW9
     */
    otherCustomerType?: string;
    /**
     * 
     * @type {number}
     * @memberof FormW9
     */
    proprietaryFormNumber?: number;
    /**
     * 
     * @type {FormW9SignatureTypeEnum}
     * @memberof FormW9
     */
    signatureType?: FormW9SignatureTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof FormW9
     */
    taxClassification?: string;
    /**
     * 
     * @type {string}
     * @memberof FormW9
     */
    taxFormFile?: string;
    /**
     * 
     * @type {string}
     * @memberof FormW9
     */
    tin?: string;
    /**
     * 
     * @type {FormW9TinTypeEnum}
     * @memberof FormW9
     */
    tinType?: FormW9TinTypeEnum;
}


/**
 * @export
 */
export const FormW9CustomerTypeEnum = {
    Individual: 'Individual',
    Corporation: 'Corporation',
    Partnership: 'Partnership',
    Llc: 'LLC',
    Other: 'Other'
} as const;
export type FormW9CustomerTypeEnum = typeof FormW9CustomerTypeEnum[keyof typeof FormW9CustomerTypeEnum];

/**
 * @export
 */
export const FormW9SignatureTypeEnum = {
    Electronic: 'Electronic',
    Physical: 'Physical'
} as const;
export type FormW9SignatureTypeEnum = typeof FormW9SignatureTypeEnum[keyof typeof FormW9SignatureTypeEnum];

/**
 * @export
 */
export const FormW9TinTypeEnum = {
    Ssn: 'SSN',
    Ein: 'EIN',
    NonUsNationalId: 'NonUS_NationalId'
} as const;
export type FormW9TinTypeEnum = typeof FormW9TinTypeEnum[keyof typeof FormW9TinTypeEnum];


/**
 * Check if a given object implements the FormW9 interface.
 */
export function instanceOfFormW9(value: object): value is FormW9 {
    return true;
}

export function FormW9FromJSON(json: any): FormW9 {
    return FormW9FromJSONTyped(json, false);
}

export function FormW9FromJSONTyped(json: any, ignoreDiscriminator: boolean): FormW9 {
    if (json == null) {
        return json;
    }
    return {
        
        'blankForm': json['blankForm'] == null ? undefined : json['blankForm'],
        'businessName': json['businessName'] == null ? undefined : json['businessName'],
        'cert1': json['cert1'] == null ? undefined : json['cert1'],
        'cert2': json['cert2'] == null ? undefined : json['cert2'],
        'cert3': json['cert3'] == null ? undefined : json['cert3'],
        'cert4': json['cert4'] == null ? undefined : json['cert4'],
        'customerType': json['customerType'] == null ? undefined : json['customerType'],
        'localTaxForms': json['localTaxForms'] == null ? undefined : ((json['localTaxForms'] as Array<any>).map(LocalTaxFormFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'otherCustomerType': json['otherCustomerType'] == null ? undefined : json['otherCustomerType'],
        'proprietaryFormNumber': json['proprietaryFormNumber'] == null ? undefined : json['proprietaryFormNumber'],
        'signatureType': json['signatureType'] == null ? undefined : json['signatureType'],
        'taxClassification': json['taxClassification'] == null ? undefined : json['taxClassification'],
        'taxFormFile': json['taxFormFile'] == null ? undefined : json['taxFormFile'],
        'tin': json['tin'] == null ? undefined : json['tin'],
        'tinType': json['tinType'] == null ? undefined : json['tinType'],
    };
}

export function FormW9ToJSON(json: any): FormW9 {
    return FormW9ToJSONTyped(json, false);
}

export function FormW9ToJSONTyped(value?: FormW9 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blankForm': value['blankForm'],
        'businessName': value['businessName'],
        'cert1': value['cert1'],
        'cert2': value['cert2'],
        'cert3': value['cert3'],
        'cert4': value['cert4'],
        'customerType': value['customerType'],
        'localTaxForms': value['localTaxForms'] == null ? undefined : ((value['localTaxForms'] as Array<any>).map(LocalTaxFormToJSON)),
        'name': value['name'],
        'otherCustomerType': value['otherCustomerType'],
        'proprietaryFormNumber': value['proprietaryFormNumber'],
        'signatureType': value['signatureType'],
        'taxClassification': value['taxClassification'],
        'taxFormFile': value['taxFormFile'],
        'tin': value['tin'],
        'tinType': value['tinType'],
    };
}

