/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvailableTaxFormsData } from './AvailableTaxFormsData';
import {
    AvailableTaxFormsDataFromJSON,
    AvailableTaxFormsDataFromJSONTyped,
    AvailableTaxFormsDataToJSON,
    AvailableTaxFormsDataToJSONTyped,
} from './AvailableTaxFormsData';

/**
 * 
 * @export
 * @interface GetAvailableTaxFormsResponse
 */
export interface GetAvailableTaxFormsResponse {
    /**
     * 
     * @type {AvailableTaxFormsData}
     * @memberof GetAvailableTaxFormsResponse
     */
    data?: AvailableTaxFormsData;
}

/**
 * Check if a given object implements the GetAvailableTaxFormsResponse interface.
 */
export function instanceOfGetAvailableTaxFormsResponse(value: object): value is GetAvailableTaxFormsResponse {
    return true;
}

export function GetAvailableTaxFormsResponseFromJSON(json: any): GetAvailableTaxFormsResponse {
    return GetAvailableTaxFormsResponseFromJSONTyped(json, false);
}

export function GetAvailableTaxFormsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAvailableTaxFormsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AvailableTaxFormsDataFromJSON(json['data']),
    };
}

export function GetAvailableTaxFormsResponseToJSON(json: any): GetAvailableTaxFormsResponse {
    return GetAvailableTaxFormsResponseToJSONTyped(json, false);
}

export function GetAvailableTaxFormsResponseToJSONTyped(value?: GetAvailableTaxFormsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AvailableTaxFormsDataToJSON(value['data']),
    };
}

