/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetStatementsResponseData } from './GetStatementsResponseData';
import {
    GetStatementsResponseDataFromJSON,
    GetStatementsResponseDataFromJSONTyped,
    GetStatementsResponseDataToJSON,
    GetStatementsResponseDataToJSONTyped,
} from './GetStatementsResponseData';

/**
 * 
 * @export
 * @interface GetStatementsResponse
 */
export interface GetStatementsResponse {
    /**
     * 
     * @type {GetStatementsResponseData}
     * @memberof GetStatementsResponse
     */
    data?: GetStatementsResponseData;
}

/**
 * Check if a given object implements the GetStatementsResponse interface.
 */
export function instanceOfGetStatementsResponse(value: object): value is GetStatementsResponse {
    return true;
}

export function GetStatementsResponseFromJSON(json: any): GetStatementsResponse {
    return GetStatementsResponseFromJSONTyped(json, false);
}

export function GetStatementsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatementsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : GetStatementsResponseDataFromJSON(json['data']),
    };
}

export function GetStatementsResponseToJSON(json: any): GetStatementsResponse {
    return GetStatementsResponseToJSONTyped(json, false);
}

export function GetStatementsResponseToJSONTyped(value?: GetStatementsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetStatementsResponseDataToJSON(value['data']),
    };
}

