/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTransactionsRequest
 */
export interface GetTransactionsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetTransactionsRequest
     */
    acctIds?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof GetTransactionsRequest
     */
    conids?: Array<number>;
    /**
     * Define the currency to display price amounts with.
     * @type {string}
     * @memberof GetTransactionsRequest
     */
    currency?: string;
    /**
     * Specify the number of days to receive transaction data for.
     * @type {number}
     * @memberof GetTransactionsRequest
     */
    days?: number;
}

/**
 * Check if a given object implements the GetTransactionsRequest interface.
 */
export function instanceOfGetTransactionsRequest(value: object): value is GetTransactionsRequest {
    return true;
}

export function GetTransactionsRequestFromJSON(json: any): GetTransactionsRequest {
    return GetTransactionsRequestFromJSONTyped(json, false);
}

export function GetTransactionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransactionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'acctIds': json['acctIds'] == null ? undefined : json['acctIds'],
        'conids': json['conids'] == null ? undefined : json['conids'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'days': json['days'] == null ? undefined : json['days'],
    };
}

export function GetTransactionsRequestToJSON(json: any): GetTransactionsRequest {
    return GetTransactionsRequestToJSONTyped(json, false);
}

export function GetTransactionsRequestToJSONTyped(value?: GetTransactionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acctIds': value['acctIds'],
        'conids': value['conids'],
        'currency': value['currency'],
        'days': value['days'],
    };
}

