/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single display rule increment.
 * @export
 * @interface IndividualPositionDisplayRuleDisplayRuleStepInner
 */
export interface IndividualPositionDisplayRuleDisplayRuleStepInner {
    /**
     * Number of decimal digits to display.
     * @type {number}
     * @memberof IndividualPositionDisplayRuleDisplayRuleStepInner
     */
    decimalDigits?: number;
    /**
     * Lower edge from which the display rule is effective.
     * @type {number}
     * @memberof IndividualPositionDisplayRuleDisplayRuleStepInner
     */
    lowerEdge?: number;
    /**
     * Number of integer digits to display.
     * @type {number}
     * @memberof IndividualPositionDisplayRuleDisplayRuleStepInner
     */
    wholeDigits?: number;
}

/**
 * Check if a given object implements the IndividualPositionDisplayRuleDisplayRuleStepInner interface.
 */
export function instanceOfIndividualPositionDisplayRuleDisplayRuleStepInner(value: object): value is IndividualPositionDisplayRuleDisplayRuleStepInner {
    return true;
}

export function IndividualPositionDisplayRuleDisplayRuleStepInnerFromJSON(json: any): IndividualPositionDisplayRuleDisplayRuleStepInner {
    return IndividualPositionDisplayRuleDisplayRuleStepInnerFromJSONTyped(json, false);
}

export function IndividualPositionDisplayRuleDisplayRuleStepInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualPositionDisplayRuleDisplayRuleStepInner {
    if (json == null) {
        return json;
    }
    return {
        
        'decimalDigits': json['decimalDigits'] == null ? undefined : json['decimalDigits'],
        'lowerEdge': json['lowerEdge'] == null ? undefined : json['lowerEdge'],
        'wholeDigits': json['wholeDigits'] == null ? undefined : json['wholeDigits'],
    };
}

export function IndividualPositionDisplayRuleDisplayRuleStepInnerToJSON(json: any): IndividualPositionDisplayRuleDisplayRuleStepInner {
    return IndividualPositionDisplayRuleDisplayRuleStepInnerToJSONTyped(json, false);
}

export function IndividualPositionDisplayRuleDisplayRuleStepInnerToJSONTyped(value?: IndividualPositionDisplayRuleDisplayRuleStepInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'decimalDigits': value['decimalDigits'],
        'lowerEdge': value['lowerEdge'],
        'wholeDigits': value['wholeDigits'],
    };
}

