/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Objects describing a single increment rule.
 * @export
 * @interface IndividualPositionIncrementRulesInner
 */
export interface IndividualPositionIncrementRulesInner {
    /**
     * The pricing increment.
     * @type {number}
     * @memberof IndividualPositionIncrementRulesInner
     */
    increment?: number;
    /**
     * Lower edge from which the price increment rule is effective.
     * @type {number}
     * @memberof IndividualPositionIncrementRulesInner
     */
    lowerEdge?: number;
}

/**
 * Check if a given object implements the IndividualPositionIncrementRulesInner interface.
 */
export function instanceOfIndividualPositionIncrementRulesInner(value: object): value is IndividualPositionIncrementRulesInner {
    return true;
}

export function IndividualPositionIncrementRulesInnerFromJSON(json: any): IndividualPositionIncrementRulesInner {
    return IndividualPositionIncrementRulesInnerFromJSONTyped(json, false);
}

export function IndividualPositionIncrementRulesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualPositionIncrementRulesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'increment': json['increment'] == null ? undefined : json['increment'],
        'lowerEdge': json['lowerEdge'] == null ? undefined : json['lowerEdge'],
    };
}

export function IndividualPositionIncrementRulesInnerToJSON(json: any): IndividualPositionIncrementRulesInner {
    return IndividualPositionIncrementRulesInnerToJSONTyped(json, false);
}

export function IndividualPositionIncrementRulesInnerToJSONTyped(value?: IndividualPositionIncrementRulesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'increment': value['increment'],
        'lowerEdge': value['lowerEdge'],
    };
}

