/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssociatedIndividual } from './AssociatedIndividual';
import {
    AssociatedIndividualFromJSON,
    AssociatedIndividualFromJSONTyped,
    AssociatedIndividualToJSON,
    AssociatedIndividualToJSONTyped,
} from './AssociatedIndividual';
import type { RegulatoryInformation } from './RegulatoryInformation';
import {
    RegulatoryInformationFromJSON,
    RegulatoryInformationFromJSONTyped,
    RegulatoryInformationToJSON,
    RegulatoryInformationToJSONTyped,
} from './RegulatoryInformation';
import type { FinancialInformation } from './FinancialInformation';
import {
    FinancialInformationFromJSON,
    FinancialInformationFromJSONTyped,
    FinancialInformationToJSON,
    FinancialInformationToJSONTyped,
} from './FinancialInformation';
import type { IndividualTaxInformation } from './IndividualTaxInformation';
import {
    IndividualTaxInformationFromJSON,
    IndividualTaxInformationFromJSONTyped,
    IndividualTaxInformationToJSON,
    IndividualTaxInformationToJSONTyped,
} from './IndividualTaxInformation';
import type { RegulatedMembership } from './RegulatedMembership';
import {
    RegulatedMembershipFromJSON,
    RegulatedMembershipFromJSONTyped,
    RegulatedMembershipToJSON,
    RegulatedMembershipToJSONTyped,
} from './RegulatedMembership';
import type { WithholdingStatementType } from './WithholdingStatementType';
import {
    WithholdingStatementTypeFromJSON,
    WithholdingStatementTypeFromJSONTyped,
    WithholdingStatementTypeToJSON,
    WithholdingStatementTypeToJSONTyped,
} from './WithholdingStatementType';
import type { AccreditedInvestorInformation } from './AccreditedInvestorInformation';
import {
    AccreditedInvestorInformationFromJSON,
    AccreditedInvestorInformationFromJSONTyped,
    AccreditedInvestorInformationToJSON,
    AccreditedInvestorInformationToJSONTyped,
} from './AccreditedInvestorInformation';

/**
 * 
 * @export
 * @interface IndividualApplicant
 */
export interface IndividualApplicant {
    /**
     * 
     * @type {Array<AssociatedIndividual>}
     * @memberof IndividualApplicant
     */
    accountHolderDetails?: Array<AssociatedIndividual>;
    /**
     * 
     * @type {AccreditedInvestorInformation}
     * @memberof IndividualApplicant
     */
    accreditedInvestorInformation?: AccreditedInvestorInformation;
    /**
     * 
     * @type {AssociatedIndividual}
     * @memberof IndividualApplicant
     */
    associatedIndividual?: AssociatedIndividual;
    /**
     * 
     * @type {Array<FinancialInformation>}
     * @memberof IndividualApplicant
     */
    financialInformation?: Array<FinancialInformation>;
    /**
     * 
     * @type {Array<RegulatedMembership>}
     * @memberof IndividualApplicant
     */
    regulatedMemberships?: Array<RegulatedMembership>;
    /**
     * 
     * @type {Array<RegulatoryInformation>}
     * @memberof IndividualApplicant
     */
    regulatoryInformation?: Array<RegulatoryInformation>;
    /**
     * 
     * @type {IndividualTaxInformation}
     * @memberof IndividualApplicant
     */
    taxInformation?: IndividualTaxInformation;
    /**
     * 
     * @type {WithholdingStatementType}
     * @memberof IndividualApplicant
     */
    withholdingStatement?: WithholdingStatementType;
}

/**
 * Check if a given object implements the IndividualApplicant interface.
 */
export function instanceOfIndividualApplicant(value: object): value is IndividualApplicant {
    return true;
}

export function IndividualApplicantFromJSON(json: any): IndividualApplicant {
    return IndividualApplicantFromJSONTyped(json, false);
}

export function IndividualApplicantFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualApplicant {
    if (json == null) {
        return json;
    }
    return {
        
        'accountHolderDetails': json['accountHolderDetails'] == null ? undefined : ((json['accountHolderDetails'] as Array<any>).map(AssociatedIndividualFromJSON)),
        'accreditedInvestorInformation': json['accreditedInvestorInformation'] == null ? undefined : AccreditedInvestorInformationFromJSON(json['accreditedInvestorInformation']),
        'associatedIndividual': json['associatedIndividual'] == null ? undefined : AssociatedIndividualFromJSON(json['associatedIndividual']),
        'financialInformation': json['financialInformation'] == null ? undefined : ((json['financialInformation'] as Array<any>).map(FinancialInformationFromJSON)),
        'regulatedMemberships': json['regulatedMemberships'] == null ? undefined : ((json['regulatedMemberships'] as Array<any>).map(RegulatedMembershipFromJSON)),
        'regulatoryInformation': json['regulatoryInformation'] == null ? undefined : ((json['regulatoryInformation'] as Array<any>).map(RegulatoryInformationFromJSON)),
        'taxInformation': json['taxInformation'] == null ? undefined : IndividualTaxInformationFromJSON(json['taxInformation']),
        'withholdingStatement': json['withholdingStatement'] == null ? undefined : WithholdingStatementTypeFromJSON(json['withholdingStatement']),
    };
}

export function IndividualApplicantToJSON(json: any): IndividualApplicant {
    return IndividualApplicantToJSONTyped(json, false);
}

export function IndividualApplicantToJSONTyped(value?: IndividualApplicant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountHolderDetails': value['accountHolderDetails'] == null ? undefined : ((value['accountHolderDetails'] as Array<any>).map(AssociatedIndividualToJSON)),
        'accreditedInvestorInformation': AccreditedInvestorInformationToJSON(value['accreditedInvestorInformation']),
        'associatedIndividual': AssociatedIndividualToJSON(value['associatedIndividual']),
        'financialInformation': value['financialInformation'] == null ? undefined : ((value['financialInformation'] as Array<any>).map(FinancialInformationToJSON)),
        'regulatedMemberships': value['regulatedMemberships'] == null ? undefined : ((value['regulatedMemberships'] as Array<any>).map(RegulatedMembershipToJSON)),
        'regulatoryInformation': value['regulatoryInformation'] == null ? undefined : ((value['regulatoryInformation'] as Array<any>).map(RegulatoryInformationToJSON)),
        'taxInformation': IndividualTaxInformationToJSON(value['taxInformation']),
        'withholdingStatement': WithholdingStatementTypeToJSON(value['withholdingStatement']),
    };
}

