/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IndividualPositionDisplayRuleDisplayRuleStepInner } from './IndividualPositionDisplayRuleDisplayRuleStepInner';
import {
    IndividualPositionDisplayRuleDisplayRuleStepInnerFromJSON,
    IndividualPositionDisplayRuleDisplayRuleStepInnerFromJSONTyped,
    IndividualPositionDisplayRuleDisplayRuleStepInnerToJSON,
    IndividualPositionDisplayRuleDisplayRuleStepInnerToJSONTyped,
} from './IndividualPositionDisplayRuleDisplayRuleStepInner';

/**
 * Object defining minimum increments used in displaying market data for the instrument.
 * @export
 * @interface IndividualPositionDisplayRule
 */
export interface IndividualPositionDisplayRule {
    /**
     * Array containing objects corresponding to display rule increments.
     * @type {Array<IndividualPositionDisplayRuleDisplayRuleStepInner>}
     * @memberof IndividualPositionDisplayRule
     */
    displayRuleStep?: Array<IndividualPositionDisplayRuleDisplayRuleStepInner>;
    /**
     * Magnifier applied to pricing, if applicable.
     * @type {number}
     * @memberof IndividualPositionDisplayRule
     */
    magnification?: number;
}

/**
 * Check if a given object implements the IndividualPositionDisplayRule interface.
 */
export function instanceOfIndividualPositionDisplayRule(value: object): value is IndividualPositionDisplayRule {
    return true;
}

export function IndividualPositionDisplayRuleFromJSON(json: any): IndividualPositionDisplayRule {
    return IndividualPositionDisplayRuleFromJSONTyped(json, false);
}

export function IndividualPositionDisplayRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualPositionDisplayRule {
    if (json == null) {
        return json;
    }
    return {
        
        'displayRuleStep': json['displayRuleStep'] == null ? undefined : ((json['displayRuleStep'] as Array<any>).map(IndividualPositionDisplayRuleDisplayRuleStepInnerFromJSON)),
        'magnification': json['magnification'] == null ? undefined : json['magnification'],
    };
}

export function IndividualPositionDisplayRuleToJSON(json: any): IndividualPositionDisplayRule {
    return IndividualPositionDisplayRuleToJSONTyped(json, false);
}

export function IndividualPositionDisplayRuleToJSONTyped(value?: IndividualPositionDisplayRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayRuleStep': value['displayRuleStep'] == null ? undefined : ((value['displayRuleStep'] as Array<any>).map(IndividualPositionDisplayRuleDisplayRuleStepInnerToJSON)),
        'magnification': value['magnification'],
    };
}

