/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstructionErrorResultAllOfError } from './InstructionErrorResultAllOfError';
import {
    InstructionErrorResultAllOfErrorFromJSON,
    InstructionErrorResultAllOfErrorFromJSONTyped,
    InstructionErrorResultAllOfErrorToJSON,
    InstructionErrorResultAllOfErrorToJSONTyped,
} from './InstructionErrorResultAllOfError';

/**
 * 
 * @export
 * @interface InstructionErrorResult
 */
export interface InstructionErrorResult {
    /**
     * 
     * @type {number}
     * @memberof InstructionErrorResult
     */
    clientInstructionId: number;
    /**
     * 
     * @type {string}
     * @memberof InstructionErrorResult
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof InstructionErrorResult
     */
    ibReferenceId?: number;
    /**
     * 
     * @type {number}
     * @memberof InstructionErrorResult
     */
    instructionId: number;
    /**
     * 
     * @type {InstructionErrorResultInstructionStatusEnum}
     * @memberof InstructionErrorResult
     */
    instructionStatus: InstructionErrorResultInstructionStatusEnum;
    /**
     * 
     * @type {InstructionErrorResultInstructionTypeEnum}
     * @memberof InstructionErrorResult
     */
    instructionType: InstructionErrorResultInstructionTypeEnum;
    /**
     * 
     * @type {InstructionErrorResultAllOfError}
     * @memberof InstructionErrorResult
     */
    error: InstructionErrorResultAllOfError;
}


/**
 * @export
 */
export const InstructionErrorResultInstructionStatusEnum = {
    Pending: 'PENDING',
    Processed: 'PROCESSED',
    Rejected: 'REJECTED',
    PendingVerification: 'PENDING_VERIFICATION'
} as const;
export type InstructionErrorResultInstructionStatusEnum = typeof InstructionErrorResultInstructionStatusEnum[keyof typeof InstructionErrorResultInstructionStatusEnum];

/**
 * @export
 */
export const InstructionErrorResultInstructionTypeEnum = {
    AchInstruction: 'ACH_INSTRUCTION',
    CancelInstruction: 'CANCEL_INSTRUCTION',
    ComplexAssetTransfer: 'COMPLEX_ASSET_TRANSFER',
    DeleteBankInstruction: 'DELETE_BANK_INSTRUCTION',
    Deposit: 'DEPOSIT',
    Dwac: 'DWAC',
    ExternalPositionTransfer: 'EXTERNAL_POSITION_TRANSFER',
    Fop: 'FOP',
    QueryRecentInstructions: 'QUERY_RECENT_INSTRUCTIONS',
    QueryWithdrawableFunds: 'QUERY_WITHDRAWABLE_FUNDS',
    InternalPositionTransfer: 'INTERNAL_POSITION_TRANSFER',
    InternalCashTransfer: 'INTERNAL_CASH_TRANSFER',
    MicroAmount: 'MICRO_AMOUNT',
    PredefinedDestinationInstruction: 'PREDEFINED_DESTINATION_INSTRUCTION',
    TraditionalBankInstructionVerification: 'TRADITIONAL_BANK_INSTRUCTION_VERIFICATION',
    Withdrawal: 'WITHDRAWAL',
    QueryIraContributions: 'QUERY_IRA_CONTRIBUTIONS',
    EddaInstruction: 'EDDA_INSTRUCTION',
    QueryRecentRecurringEvents: 'QUERY_RECENT_RECURRING_EVENTS',
    QueryRecurringInstructions: 'QUERY_RECURRING_INSTRUCTIONS',
    QueryAccountBalances: 'QUERY_ACCOUNT_BALANCES',
    QueryBankInstruction: 'QUERY_BANK_INSTRUCTION',
    QueryWithdrawableCashEquity: 'QUERY_WITHDRAWABLE_CASH_EQUITY'
} as const;
export type InstructionErrorResultInstructionTypeEnum = typeof InstructionErrorResultInstructionTypeEnum[keyof typeof InstructionErrorResultInstructionTypeEnum];


/**
 * Check if a given object implements the InstructionErrorResult interface.
 */
export function instanceOfInstructionErrorResult(value: object): value is InstructionErrorResult {
    if (!('clientInstructionId' in value) || value['clientInstructionId'] === undefined) return false;
    if (!('instructionId' in value) || value['instructionId'] === undefined) return false;
    if (!('instructionStatus' in value) || value['instructionStatus'] === undefined) return false;
    if (!('instructionType' in value) || value['instructionType'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function InstructionErrorResultFromJSON(json: any): InstructionErrorResult {
    return InstructionErrorResultFromJSONTyped(json, false);
}

export function InstructionErrorResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstructionErrorResult {
    if (json == null) {
        return json;
    }
    return {
        
        'clientInstructionId': json['clientInstructionId'],
        'description': json['description'] == null ? undefined : json['description'],
        'ibReferenceId': json['ibReferenceId'] == null ? undefined : json['ibReferenceId'],
        'instructionId': json['instructionId'],
        'instructionStatus': json['instructionStatus'],
        'instructionType': json['instructionType'],
        'error': InstructionErrorResultAllOfErrorFromJSON(json['error']),
    };
}

export function InstructionErrorResultToJSON(json: any): InstructionErrorResult {
    return InstructionErrorResultToJSONTyped(json, false);
}

export function InstructionErrorResultToJSONTyped(value?: InstructionErrorResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientInstructionId': value['clientInstructionId'],
        'description': value['description'],
        'ibReferenceId': value['ibReferenceId'],
        'instructionId': value['instructionId'],
        'instructionStatus': value['instructionStatus'],
        'instructionType': value['instructionType'],
        'error': InstructionErrorResultAllOfErrorToJSON(value['error']),
    };
}

