/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IserverScannerRunResponseContractsInner
 */
export interface IserverScannerRunResponseContractsInner {
    /**
     * Internal Use Only
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    available_chart_periods?: string;
    /**
     * Always returned for the first contract.
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    column_name?: string;
    /**
     * Returns the company long name.
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    company_name?: string;
    /**
     * Returns the contract ID of the contract.
     * @type {number}
     * @memberof IserverScannerRunResponseContractsInner
     */
    con_id?: number;
    /**
     * Returns the contract ID of the contract.
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    conidex?: string;
    /**
     * For derivatives like Futures, the local symbol of the contract will be returned.
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    contract_description_1?: string;
    /**
     * Returns the primary listing exchange of the contract.
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    listing_exchange?: string;
    /**
     * Returns the security type of the contract.
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    sec_type?: string;
    /**
     * Contract's index in relation to the market scanner type's sorting priority.
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    server_id?: string;
    /**
     * Returns the contract's ticker symbol.
     * @type {string}
     * @memberof IserverScannerRunResponseContractsInner
     */
    symbol?: string;
}

/**
 * Check if a given object implements the IserverScannerRunResponseContractsInner interface.
 */
export function instanceOfIserverScannerRunResponseContractsInner(value: object): value is IserverScannerRunResponseContractsInner {
    return true;
}

export function IserverScannerRunResponseContractsInnerFromJSON(json: any): IserverScannerRunResponseContractsInner {
    return IserverScannerRunResponseContractsInnerFromJSONTyped(json, false);
}

export function IserverScannerRunResponseContractsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IserverScannerRunResponseContractsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'available_chart_periods': json['available_chart_periods'] == null ? undefined : json['available_chart_periods'],
        'column_name': json['column_name'] == null ? undefined : json['column_name'],
        'company_name': json['company_name'] == null ? undefined : json['company_name'],
        'con_id': json['con_id'] == null ? undefined : json['con_id'],
        'conidex': json['conidex'] == null ? undefined : json['conidex'],
        'contract_description_1': json['contract_description_1'] == null ? undefined : json['contract_description_1'],
        'listing_exchange': json['listing_exchange'] == null ? undefined : json['listing_exchange'],
        'sec_type': json['sec_type'] == null ? undefined : json['sec_type'],
        'server_id': json['server_id'] == null ? undefined : json['server_id'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
    };
}

export function IserverScannerRunResponseContractsInnerToJSON(json: any): IserverScannerRunResponseContractsInner {
    return IserverScannerRunResponseContractsInnerToJSONTyped(json, false);
}

export function IserverScannerRunResponseContractsInnerToJSONTyped(value?: IserverScannerRunResponseContractsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available_chart_periods': value['available_chart_periods'],
        'column_name': value['column_name'],
        'company_name': value['company_name'],
        'con_id': value['con_id'],
        'conidex': value['conidex'],
        'contract_description_1': value['contract_description_1'],
        'listing_exchange': value['listing_exchange'],
        'sec_type': value['sec_type'],
        'server_id': value['server_id'],
        'symbol': value['symbol'],
    };
}

