/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IserverScannerParamsFilterListInnerComboValuesInner
 */
export interface IserverScannerParamsFilterListInnerComboValuesInner {
    /**
     * 
     * @type {boolean}
     * @memberof IserverScannerParamsFilterListInnerComboValuesInner
     */
    _default?: boolean;
    /**
     * 
     * @type {object}
     * @memberof IserverScannerParamsFilterListInnerComboValuesInner
     */
    vendor?: object;
}

/**
 * Check if a given object implements the IserverScannerParamsFilterListInnerComboValuesInner interface.
 */
export function instanceOfIserverScannerParamsFilterListInnerComboValuesInner(value: object): value is IserverScannerParamsFilterListInnerComboValuesInner {
    return true;
}

export function IserverScannerParamsFilterListInnerComboValuesInnerFromJSON(json: any): IserverScannerParamsFilterListInnerComboValuesInner {
    return IserverScannerParamsFilterListInnerComboValuesInnerFromJSONTyped(json, false);
}

export function IserverScannerParamsFilterListInnerComboValuesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IserverScannerParamsFilterListInnerComboValuesInner {
    if (json == null) {
        return json;
    }
    return {
        
        '_default': json['default'] == null ? undefined : json['default'],
        'vendor': json['vendor'] == null ? undefined : json['vendor'],
    };
}

export function IserverScannerParamsFilterListInnerComboValuesInnerToJSON(json: any): IserverScannerParamsFilterListInnerComboValuesInner {
    return IserverScannerParamsFilterListInnerComboValuesInnerToJSONTyped(json, false);
}

export function IserverScannerParamsFilterListInnerComboValuesInnerToJSONTyped(value?: IserverScannerParamsFilterListInnerComboValuesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default': value['_default'],
        'vendor': value['vendor'],
    };
}

