/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface LegalEntityIdentification
 */
export interface LegalEntityIdentification {
    /**
     * 
     * @type {string}
     * @memberof LegalEntityIdentification
     */
    exchangeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof LegalEntityIdentification
     */
    exchangeSymbol?: string;
    /**
     * 
     * @type {string}
     * @memberof LegalEntityIdentification
     */
    formationCountry?: string;
    /**
     * 
     * @type {LegalEntityIdentificationFormationTypeEnum}
     * @memberof LegalEntityIdentification
     */
    formationType?: LegalEntityIdentificationFormationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LegalEntityIdentification
     */
    identification?: string;
    /**
     * 
     * @type {string}
     * @memberof LegalEntityIdentification
     */
    identificationCountry?: string;
    /**
     * 
     * @type {Address}
     * @memberof LegalEntityIdentification
     */
    mailingAddress?: Address;
    /**
     * 
     * @type {Address}
     * @memberof LegalEntityIdentification
     */
    placeOfBusinessAddress?: Address;
    /**
     * 
     * @type {boolean}
     * @memberof LegalEntityIdentification
     */
    sameMailAddress?: boolean;
}


/**
 * @export
 */
export const LegalEntityIdentificationFormationTypeEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE',
    Other: 'OTHER'
} as const;
export type LegalEntityIdentificationFormationTypeEnum = typeof LegalEntityIdentificationFormationTypeEnum[keyof typeof LegalEntityIdentificationFormationTypeEnum];


/**
 * Check if a given object implements the LegalEntityIdentification interface.
 */
export function instanceOfLegalEntityIdentification(value: object): value is LegalEntityIdentification {
    return true;
}

export function LegalEntityIdentificationFromJSON(json: any): LegalEntityIdentification {
    return LegalEntityIdentificationFromJSONTyped(json, false);
}

export function LegalEntityIdentificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalEntityIdentification {
    if (json == null) {
        return json;
    }
    return {
        
        'exchangeCode': json['exchangeCode'] == null ? undefined : json['exchangeCode'],
        'exchangeSymbol': json['exchangeSymbol'] == null ? undefined : json['exchangeSymbol'],
        'formationCountry': json['formationCountry'] == null ? undefined : json['formationCountry'],
        'formationType': json['formationType'] == null ? undefined : json['formationType'],
        'identification': json['identification'] == null ? undefined : json['identification'],
        'identificationCountry': json['identificationCountry'] == null ? undefined : json['identificationCountry'],
        'mailingAddress': json['mailingAddress'] == null ? undefined : AddressFromJSON(json['mailingAddress']),
        'placeOfBusinessAddress': json['placeOfBusinessAddress'] == null ? undefined : AddressFromJSON(json['placeOfBusinessAddress']),
        'sameMailAddress': json['sameMailAddress'] == null ? undefined : json['sameMailAddress'],
    };
}

export function LegalEntityIdentificationToJSON(json: any): LegalEntityIdentification {
    return LegalEntityIdentificationToJSONTyped(json, false);
}

export function LegalEntityIdentificationToJSONTyped(value?: LegalEntityIdentification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exchangeCode': value['exchangeCode'],
        'exchangeSymbol': value['exchangeSymbol'],
        'formationCountry': value['formationCountry'],
        'formationType': value['formationType'],
        'identification': value['identification'],
        'identificationCountry': value['identificationCountry'],
        'mailingAddress': AddressToJSON(value['mailingAddress']),
        'placeOfBusinessAddress': AddressToJSON(value['placeOfBusinessAddress']),
        'sameMailAddress': value['sameMailAddress'],
    };
}

