/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object representing one order.
 * @export
 * @interface LiveOrdersResponseOrdersInner
 */
export interface LiveOrdersResponseOrdersInner {
    /**
     * IB account ID to which the order was placed.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    account?: string;
    /**
     * IB account ID to which the order was placed.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    acct?: string;
    /**
     * Average price of fills against the order, if any.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    avgPrice?: string;
    /**
     * Internal use. IB's UI background color in hex.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    bgColor?: string;
    /**
     * Currency of the order ticket's Cash Quantity, if applicable.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    cashCcy?: string;
    /**
     * Name of business associated with instrument, or otherwise description of instrument.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    companyName?: string;
    /**
     * Contract ID of the order's instrument.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    conid?: string;
    /**
     * Contract ID and routing destination in format 123456@EXCHANGE.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    conidex?: string;
    /**
     * Descriptive text, or additional details that specific the instrument.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    description1?: string;
    /**
     * Only present for derivatives. Shows Expiry, Strike, Right, And Exchange information.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    description2?: string;
    /**
     * Routing destination of the order ticket.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    exchange?: string;
    /**
     * Internal use. IB's UI foreground color in hex.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    fgColor?: string;
    /**
     * Quantity filled in units of the instrument.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    filledQuantity?: string;
    /**
     * Indicates whether the order ticket is an Event Trading order.
     * @type {LiveOrdersResponseOrdersInnerIsEventTradingEnum}
     * @memberof LiveOrdersResponseOrdersInner
     */
    isEventTrading?: LiveOrdersResponseOrdersInnerIsEventTradingEnum;
    /**
     * Time of last execution against the order in format YYMMDDhhmmss.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    lastExecutionTime?: string;
    /**
     * Unix timestamp of the last execution against the order.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    lastExecutionTime_r?: string;
    /**
     * Exchange on which the instrument is listed.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    listingExchange?: string;
    /**
     * Human-readable shorthand rendering of the order ticket.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    orderDesc?: string;
    /**
     * IB-assigned order identifier.
     * @type {number}
     * @memberof LiveOrdersResponseOrdersInner
     */
    orderId?: number;
    /**
     * Order type of a working order ticket.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    orderType?: string;
    /**
     * Only present for Cancelled orders. Provides the reason for order to have been cancelled or rejected by the system.
     * 
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    order_cancellation_by_system_reason?: string;
    /**
     * IB internal order status.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    order_ccp_status?: string;
    /**
     * Order type of a filled order.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    origOrderType?: string;
    /**
     * Price of the order, if applicable to the order type.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    price?: string;
    /**
     * Quantity remaining to be filled in units of the instrument.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    remainingQuantity?: string;
    /**
     * Asset class of the instrument.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    secType?: string;
    /**
     * Side of the order.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    side?: string;
    /**
     * Human-readable shorthand rendering of the filled and total quantities of the order.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    sizeAndFills?: string;
    /**
     * Status of the order ticket.
     * @type {LiveOrdersResponseOrdersInnerStatusEnum}
     * @memberof LiveOrdersResponseOrdersInner
     */
    status?: LiveOrdersResponseOrdersInnerStatusEnum;
    /**
     * Indicates whether the order is supported by IB's Tax Optimization tool.
     * @type {LiveOrdersResponseOrdersInnerSupportsTaxOptEnum}
     * @memberof LiveOrdersResponseOrdersInner
     */
    supportsTaxOpt?: LiveOrdersResponseOrdersInnerSupportsTaxOptEnum;
    /**
     * Tax Optimizer id, identifies set of tax lots selected, for gains and losses management.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    taxOptimizerId?: string;
    /**
     * Symbol or base product code of the instrument.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    ticker?: string;
    /**
     * Time of force of the order.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    timeInForce?: string;
    /**
     * Total size of a cash quantity order.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    totalCashSize?: string;
    /**
     * Total size of an order in the instrument's units.
     * @type {string}
     * @memberof LiveOrdersResponseOrdersInner
     */
    totalSize?: string;
}


/**
 * @export
 */
export const LiveOrdersResponseOrdersInnerIsEventTradingEnum = {
    _0: '0',
    _1: '1'
} as const;
export type LiveOrdersResponseOrdersInnerIsEventTradingEnum = typeof LiveOrdersResponseOrdersInnerIsEventTradingEnum[keyof typeof LiveOrdersResponseOrdersInnerIsEventTradingEnum];

/**
 * @export
 */
export const LiveOrdersResponseOrdersInnerStatusEnum = {
    Inactive: 'Inactive',
    PendingSubmit: 'PendingSubmit',
    PreSubmitted: 'PreSubmitted',
    Submitted: 'Submitted',
    Filled: 'Filled',
    PendingCancel: 'PendingCancel',
    Cancelled: 'Cancelled',
    WarnState: 'WarnState'
} as const;
export type LiveOrdersResponseOrdersInnerStatusEnum = typeof LiveOrdersResponseOrdersInnerStatusEnum[keyof typeof LiveOrdersResponseOrdersInnerStatusEnum];

/**
 * @export
 */
export const LiveOrdersResponseOrdersInnerSupportsTaxOptEnum = {
    _0: '0',
    _1: '1'
} as const;
export type LiveOrdersResponseOrdersInnerSupportsTaxOptEnum = typeof LiveOrdersResponseOrdersInnerSupportsTaxOptEnum[keyof typeof LiveOrdersResponseOrdersInnerSupportsTaxOptEnum];


/**
 * Check if a given object implements the LiveOrdersResponseOrdersInner interface.
 */
export function instanceOfLiveOrdersResponseOrdersInner(value: object): value is LiveOrdersResponseOrdersInner {
    return true;
}

export function LiveOrdersResponseOrdersInnerFromJSON(json: any): LiveOrdersResponseOrdersInner {
    return LiveOrdersResponseOrdersInnerFromJSONTyped(json, false);
}

export function LiveOrdersResponseOrdersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveOrdersResponseOrdersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : json['account'],
        'acct': json['acct'] == null ? undefined : json['acct'],
        'avgPrice': json['avgPrice'] == null ? undefined : json['avgPrice'],
        'bgColor': json['bgColor'] == null ? undefined : json['bgColor'],
        'cashCcy': json['cashCcy'] == null ? undefined : json['cashCcy'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'conid': json['conid'] == null ? undefined : json['conid'],
        'conidex': json['conidex'] == null ? undefined : json['conidex'],
        'description1': json['description1'] == null ? undefined : json['description1'],
        'description2': json['description2'] == null ? undefined : json['description2'],
        'exchange': json['exchange'] == null ? undefined : json['exchange'],
        'fgColor': json['fgColor'] == null ? undefined : json['fgColor'],
        'filledQuantity': json['filledQuantity'] == null ? undefined : json['filledQuantity'],
        'isEventTrading': json['isEventTrading'] == null ? undefined : json['isEventTrading'],
        'lastExecutionTime': json['lastExecutionTime'] == null ? undefined : json['lastExecutionTime'],
        'lastExecutionTime_r': json['lastExecutionTime_r'] == null ? undefined : json['lastExecutionTime_r'],
        'listingExchange': json['listingExchange'] == null ? undefined : json['listingExchange'],
        'orderDesc': json['orderDesc'] == null ? undefined : json['orderDesc'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'orderType': json['orderType'] == null ? undefined : json['orderType'],
        'order_cancellation_by_system_reason': json['order_cancellation_by_system_reason'] == null ? undefined : json['order_cancellation_by_system_reason'],
        'order_ccp_status': json['order_ccp_status'] == null ? undefined : json['order_ccp_status'],
        'origOrderType': json['origOrderType'] == null ? undefined : json['origOrderType'],
        'price': json['price'] == null ? undefined : json['price'],
        'remainingQuantity': json['remainingQuantity'] == null ? undefined : json['remainingQuantity'],
        'secType': json['secType'] == null ? undefined : json['secType'],
        'side': json['side'] == null ? undefined : json['side'],
        'sizeAndFills': json['sizeAndFills'] == null ? undefined : json['sizeAndFills'],
        'status': json['status'] == null ? undefined : json['status'],
        'supportsTaxOpt': json['supportsTaxOpt'] == null ? undefined : json['supportsTaxOpt'],
        'taxOptimizerId': json['taxOptimizerId'] == null ? undefined : json['taxOptimizerId'],
        'ticker': json['ticker'] == null ? undefined : json['ticker'],
        'timeInForce': json['timeInForce'] == null ? undefined : json['timeInForce'],
        'totalCashSize': json['totalCashSize'] == null ? undefined : json['totalCashSize'],
        'totalSize': json['totalSize'] == null ? undefined : json['totalSize'],
    };
}

export function LiveOrdersResponseOrdersInnerToJSON(json: any): LiveOrdersResponseOrdersInner {
    return LiveOrdersResponseOrdersInnerToJSONTyped(json, false);
}

export function LiveOrdersResponseOrdersInnerToJSONTyped(value?: LiveOrdersResponseOrdersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'acct': value['acct'],
        'avgPrice': value['avgPrice'],
        'bgColor': value['bgColor'],
        'cashCcy': value['cashCcy'],
        'companyName': value['companyName'],
        'conid': value['conid'],
        'conidex': value['conidex'],
        'description1': value['description1'],
        'description2': value['description2'],
        'exchange': value['exchange'],
        'fgColor': value['fgColor'],
        'filledQuantity': value['filledQuantity'],
        'isEventTrading': value['isEventTrading'],
        'lastExecutionTime': value['lastExecutionTime'],
        'lastExecutionTime_r': value['lastExecutionTime_r'],
        'listingExchange': value['listingExchange'],
        'orderDesc': value['orderDesc'],
        'orderId': value['orderId'],
        'orderType': value['orderType'],
        'order_cancellation_by_system_reason': value['order_cancellation_by_system_reason'],
        'order_ccp_status': value['order_ccp_status'],
        'origOrderType': value['origOrderType'],
        'price': value['price'],
        'remainingQuantity': value['remainingQuantity'],
        'secType': value['secType'],
        'side': value['side'],
        'sizeAndFills': value['sizeAndFills'],
        'status': value['status'],
        'supportsTaxOpt': value['supportsTaxOpt'],
        'taxOptimizerId': value['taxOptimizerId'],
        'ticker': value['ticker'],
        'timeInForce': value['timeInForce'],
        'totalCashSize': value['totalCashSize'],
        'totalSize': value['totalSize'],
    };
}

