/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginMessage
 */
export interface LoginMessage {
    /**
     * 
     * @type {number}
     * @memberof LoginMessage
     */
    contentId?: number;
    /**
     * 
     * @type {string}
     * @memberof LoginMessage
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof LoginMessage
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LoginMessage
     */
    messageType?: string;
    /**
     * 
     * @type {Date}
     * @memberof LoginMessage
     */
    recordDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof LoginMessage
     */
    state?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof LoginMessage
     */
    tasks?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof LoginMessage
     */
    username?: string;
}

/**
 * Check if a given object implements the LoginMessage interface.
 */
export function instanceOfLoginMessage(value: object): value is LoginMessage {
    return true;
}

export function LoginMessageFromJSON(json: any): LoginMessage {
    return LoginMessageFromJSONTyped(json, false);
}

export function LoginMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'contentId': json['contentId'] == null ? undefined : json['contentId'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'messageType': json['messageType'] == null ? undefined : json['messageType'],
        'recordDate': json['recordDate'] == null ? undefined : (new Date(json['recordDate'])),
        'state': json['state'] == null ? undefined : json['state'],
        'tasks': json['tasks'] == null ? undefined : json['tasks'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function LoginMessageToJSON(json: any): LoginMessage {
    return LoginMessageToJSONTyped(json, false);
}

export function LoginMessageToJSONTyped(value?: LoginMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contentId': value['contentId'],
        'description': value['description'],
        'id': value['id'],
        'messageType': value['messageType'],
        'recordDate': value['recordDate'] == null ? value['recordDate'] : value['recordDate'].toISOString(),
        'state': value['state'],
        'tasks': value['tasks'],
        'username': value['username'],
    };
}

