/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManagingOwner
 */
export interface ManagingOwner {
    /**
     * 
     * @type {string}
     * @memberof ManagingOwner
     */
    externalId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ManagingOwner
     */
    is25PercentOwner?: boolean;
}

/**
 * Check if a given object implements the ManagingOwner interface.
 */
export function instanceOfManagingOwner(value: object): value is ManagingOwner {
    return true;
}

export function ManagingOwnerFromJSON(json: any): ManagingOwner {
    return ManagingOwnerFromJSONTyped(json, false);
}

export function ManagingOwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagingOwner {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'is25PercentOwner': json['is25PercentOwner'] == null ? undefined : json['is25PercentOwner'],
    };
}

export function ManagingOwnerToJSON(json: any): ManagingOwner {
    return ManagingOwnerToJSONTyped(json, false);
}

export function ManagingOwnerToJSONTyped(value?: ManagingOwner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalId': value['externalId'],
        'is25PercentOwner': value['is25PercentOwner'],
    };
}

