/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelPresetsResponse
 */
export interface ModelPresetsResponse {
    /**
     * Avoid negative offsetting cash in Independent
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    avoidNegativeCashInIndependent?: boolean;
    /**
     * Close out the full position while divesting.
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    closeDivestIndependentPosition?: boolean;
    /**
     * Use the maximum avialble funds to increase long positions.
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    fullyInvestExistingLongPositions?: boolean;
    /**
     * Keep model open for fully divested accounts.
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    keepModelOpen?: boolean;
    /**
     * Transfer positions to Independent instead of liquidating.
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    preferCrossWithIndependent?: boolean;
    /**
     * Transfer positions from Independent structure when possible.
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    preferTransferFromIndependent?: boolean;
    /**
     * Request identifier to uniquely track a request.
     * @type {number}
     * @memberof ModelPresetsResponse
     */
    reqID?: number;
    /**
     * Determine if allocation quantities should be handled by lot size.
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    roundAllocationQuantityToExchangeBoardLot?: boolean;
    /**
     * Describes if the model is in polling mode.
     * @type {number}
     * @memberof ModelPresetsResponse
     */
    subscriptionStatus?: number;
    /**
     * Use non-base balances when available.
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    useNonBaseCcy?: boolean;
    /**
     * Designate of tolerance ranges should be used for rebalancing.
     * @type {boolean}
     * @memberof ModelPresetsResponse
     */
    useToleranceRange?: boolean;
}

/**
 * Check if a given object implements the ModelPresetsResponse interface.
 */
export function instanceOfModelPresetsResponse(value: object): value is ModelPresetsResponse {
    return true;
}

export function ModelPresetsResponseFromJSON(json: any): ModelPresetsResponse {
    return ModelPresetsResponseFromJSONTyped(json, false);
}

export function ModelPresetsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelPresetsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avoidNegativeCashInIndependent': json['avoidNegativeCashInIndependent'] == null ? undefined : json['avoidNegativeCashInIndependent'],
        'closeDivestIndependentPosition': json['closeDivestIndependentPosition'] == null ? undefined : json['closeDivestIndependentPosition'],
        'fullyInvestExistingLongPositions': json['fullyInvestExistingLongPositions'] == null ? undefined : json['fullyInvestExistingLongPositions'],
        'keepModelOpen': json['keepModelOpen'] == null ? undefined : json['keepModelOpen'],
        'preferCrossWithIndependent': json['preferCrossWithIndependent'] == null ? undefined : json['preferCrossWithIndependent'],
        'preferTransferFromIndependent': json['preferTransferFromIndependent'] == null ? undefined : json['preferTransferFromIndependent'],
        'reqID': json['reqID'] == null ? undefined : json['reqID'],
        'roundAllocationQuantityToExchangeBoardLot': json['roundAllocationQuantityToExchangeBoardLot'] == null ? undefined : json['roundAllocationQuantityToExchangeBoardLot'],
        'subscriptionStatus': json['subscriptionStatus'] == null ? undefined : json['subscriptionStatus'],
        'useNonBaseCcy': json['useNonBaseCcy'] == null ? undefined : json['useNonBaseCcy'],
        'useToleranceRange': json['useToleranceRange'] == null ? undefined : json['useToleranceRange'],
    };
}

export function ModelPresetsResponseToJSON(json: any): ModelPresetsResponse {
    return ModelPresetsResponseToJSONTyped(json, false);
}

export function ModelPresetsResponseToJSONTyped(value?: ModelPresetsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avoidNegativeCashInIndependent': value['avoidNegativeCashInIndependent'],
        'closeDivestIndependentPosition': value['closeDivestIndependentPosition'],
        'fullyInvestExistingLongPositions': value['fullyInvestExistingLongPositions'],
        'keepModelOpen': value['keepModelOpen'],
        'preferCrossWithIndependent': value['preferCrossWithIndependent'],
        'preferTransferFromIndependent': value['preferTransferFromIndependent'],
        'reqID': value['reqID'],
        'roundAllocationQuantityToExchangeBoardLot': value['roundAllocationQuantityToExchangeBoardLot'],
        'subscriptionStatus': value['subscriptionStatus'],
        'useNonBaseCcy': value['useNonBaseCcy'],
        'useToleranceRange': value['useToleranceRange'],
    };
}

