/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelSummaryResponse
 */
export interface ModelSummaryResponse {
    /**
     * Used internally for client portal designation. Should be ignored.
     * @type {boolean}
     * @memberof ModelSummaryResponse
     */
    bootstrapped?: boolean;
    /**
     * Used internally for client portal. Should be ignored.
     * @type {boolean}
     * @memberof ModelSummaryResponse
     */
    customIndex?: boolean;
    /**
     * Personal description of model to read in IBKR GUI elements.
     * @type {string}
     * @memberof ModelSummaryResponse
     */
    desc?: string;
    /**
     * Determine if investing and rebalancing should be handled statically or dynamically. * `true` - Static models will always use the original targets. * `false` - Dynamic models will adjust allocation in response to market movements.
     * 
     * @type {boolean}
     * @memberof ModelSummaryResponse
     */
    isStatic?: boolean;
    /**
     * Notes if the Actual allocation has become misalligned with the Target.
     * @type {boolean}
     * @memberof ModelSummaryResponse
     */
    mismatch?: boolean;
    /**
     * Name of the model.
     * @type {string}
     * @memberof ModelSummaryResponse
     */
    model?: string;
    /**
     * Net Liquidation of the model.
     * @type {number}
     * @memberof ModelSummaryResponse
     */
    nlv?: number;
    /**
     * Lists the number of accounts held within the model.
     * @type {number}
     * @memberof ModelSummaryResponse
     */
    numAccounts?: number;
    /**
     * Request identifier to uniquely track a request.
     * @type {number}
     * @memberof ModelSummaryResponse
     */
    reqID?: number;
    /**
     * Describes if the model is in polling mode.
     * @type {number}
     * @memberof ModelSummaryResponse
     */
    subscriptionStatus?: number;
}

/**
 * Check if a given object implements the ModelSummaryResponse interface.
 */
export function instanceOfModelSummaryResponse(value: object): value is ModelSummaryResponse {
    return true;
}

export function ModelSummaryResponseFromJSON(json: any): ModelSummaryResponse {
    return ModelSummaryResponseFromJSONTyped(json, false);
}

export function ModelSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bootstrapped': json['bootstrapped'] == null ? undefined : json['bootstrapped'],
        'customIndex': json['customIndex'] == null ? undefined : json['customIndex'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'isStatic': json['isStatic'] == null ? undefined : json['isStatic'],
        'mismatch': json['mismatch'] == null ? undefined : json['mismatch'],
        'model': json['model'] == null ? undefined : json['model'],
        'nlv': json['nlv'] == null ? undefined : json['nlv'],
        'numAccounts': json['numAccounts'] == null ? undefined : json['numAccounts'],
        'reqID': json['reqID'] == null ? undefined : json['reqID'],
        'subscriptionStatus': json['subscriptionStatus'] == null ? undefined : json['subscriptionStatus'],
    };
}

export function ModelSummaryResponseToJSON(json: any): ModelSummaryResponse {
    return ModelSummaryResponseToJSONTyped(json, false);
}

export function ModelSummaryResponseToJSONTyped(value?: ModelSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bootstrapped': value['bootstrapped'],
        'customIndex': value['customIndex'],
        'desc': value['desc'],
        'isStatic': value['isStatic'],
        'mismatch': value['mismatch'],
        'model': value['model'],
        'nlv': value['nlv'],
        'numAccounts': value['numAccounts'],
        'reqID': value['reqID'],
        'subscriptionStatus': value['subscriptionStatus'],
    };
}

