/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Indicates that the order reply ID does not exist.
 * @export
 * @interface OrderReplyNotFound
 */
export interface OrderReplyNotFound {
    /**
     * Message indicating that order reply id was not found.
     * @type {string}
     * @memberof OrderReplyNotFound
     */
    error?: string;
}

/**
 * Check if a given object implements the OrderReplyNotFound interface.
 */
export function instanceOfOrderReplyNotFound(value: object): value is OrderReplyNotFound {
    return true;
}

export function OrderReplyNotFoundFromJSON(json: any): OrderReplyNotFound {
    return OrderReplyNotFoundFromJSONTyped(json, false);
}

export function OrderReplyNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderReplyNotFound {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function OrderReplyNotFoundToJSON(json: any): OrderReplyNotFound {
    return OrderReplyNotFoundToJSONTyped(json, false);
}

export function OrderReplyNotFoundToJSONTyped(value?: OrderReplyNotFound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

