/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An object containing order reply messages emitted against a single order ticket.
 * @export
 * @interface OrderReplyMessageInner
 */
export interface OrderReplyMessageInner {
    /**
     * The replyId UUID of the order ticket's emitted order reply messages, used to confirm them and proceed. Use the POST /iserver/reply/{replyId} endpoint to confirm an order reply message.
     * 
     * @type {string}
     * @memberof OrderReplyMessageInner
     */
    id?: string;
    /**
     * Internal use. Always delivers value 'false'.
     * @type {boolean}
     * @memberof OrderReplyMessageInner
     */
    isSuppressed?: boolean;
    /**
     * An array containing the human-readable text of all order reply messages emitted for the order ticket.
     * @type {Array<string>}
     * @memberof OrderReplyMessageInner
     */
    message?: Array<string>;
    /**
     * An array containing identifiers that categorize the types of order reply messages that have been emitted.  Elements of this array are ordered so that indicies match the corresponding human-readable text strings in the 'message' array. A messageId can typically be passed in the POST /iserver/questions/suppress endpoint to auto-accept a given warning message.
     * 
     * @type {Array<string>}
     * @memberof OrderReplyMessageInner
     */
    messageIds?: Array<string>;
}

/**
 * Check if a given object implements the OrderReplyMessageInner interface.
 */
export function instanceOfOrderReplyMessageInner(value: object): value is OrderReplyMessageInner {
    return true;
}

export function OrderReplyMessageInnerFromJSON(json: any): OrderReplyMessageInner {
    return OrderReplyMessageInnerFromJSONTyped(json, false);
}

export function OrderReplyMessageInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderReplyMessageInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'isSuppressed': json['isSuppressed'] == null ? undefined : json['isSuppressed'],
        'message': json['message'] == null ? undefined : json['message'],
        'messageIds': json['messageIds'] == null ? undefined : json['messageIds'],
    };
}

export function OrderReplyMessageInnerToJSON(json: any): OrderReplyMessageInner {
    return OrderReplyMessageInnerToJSONTyped(json, false);
}

export function OrderReplyMessageInnerToJSONTyped(value?: OrderReplyMessageInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'isSuppressed': value['isSuppressed'],
        'message': value['message'],
        'messageIds': value['messageIds'],
    };
}

