/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceResponseCpsDataInner
 */
export interface PerformanceResponseCpsDataInner {
    /**
     * Returns the base curency for the account.
     * @type {string}
     * @memberof PerformanceResponseCpsDataInner
     */
    baseCurrency?: string;
    /**
     * Returns the ending value of the value range.
     * @type {string}
     * @memberof PerformanceResponseCpsDataInner
     */
    end?: string;
    /**
     * Returns the account identifier.
     * @type {string}
     * @memberof PerformanceResponseCpsDataInner
     */
    id?: string;
    /**
     * Returns the key value of the request.
     * @type {string}
     * @memberof PerformanceResponseCpsDataInner
     */
    idType?: string;
    /**
     * Returns all cps values in order between the start and end times.
     * @type {Array<any>}
     * @memberof PerformanceResponseCpsDataInner
     */
    returns?: Array<any>;
    /**
     * Returns the starting value of the value range.
     * @type {string}
     * @memberof PerformanceResponseCpsDataInner
     */
    start?: string;
}

/**
 * Check if a given object implements the PerformanceResponseCpsDataInner interface.
 */
export function instanceOfPerformanceResponseCpsDataInner(value: object): value is PerformanceResponseCpsDataInner {
    return true;
}

export function PerformanceResponseCpsDataInnerFromJSON(json: any): PerformanceResponseCpsDataInner {
    return PerformanceResponseCpsDataInnerFromJSONTyped(json, false);
}

export function PerformanceResponseCpsDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceResponseCpsDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'baseCurrency': json['baseCurrency'] == null ? undefined : json['baseCurrency'],
        'end': json['end'] == null ? undefined : json['end'],
        'id': json['id'] == null ? undefined : json['id'],
        'idType': json['idType'] == null ? undefined : json['idType'],
        'returns': json['returns'] == null ? undefined : json['returns'],
        'start': json['start'] == null ? undefined : json['start'],
    };
}

export function PerformanceResponseCpsDataInnerToJSON(json: any): PerformanceResponseCpsDataInner {
    return PerformanceResponseCpsDataInnerToJSONTyped(json, false);
}

export function PerformanceResponseCpsDataInnerToJSONTyped(value?: PerformanceResponseCpsDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseCurrency': value['baseCurrency'],
        'end': value['end'],
        'id': value['id'],
        'idType': value['idType'],
        'returns': value['returns'],
        'start': value['start'],
    };
}

