/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PnlPartitionedResponseUpnl } from './PnlPartitionedResponseUpnl';
import {
    PnlPartitionedResponseUpnlFromJSON,
    PnlPartitionedResponseUpnlFromJSONTyped,
    PnlPartitionedResponseUpnlToJSON,
    PnlPartitionedResponseUpnlToJSONTyped,
} from './PnlPartitionedResponseUpnl';

/**
 * 
 * @export
 * @interface PnlPartitionedResponse
 */
export interface PnlPartitionedResponse {
    /**
     * 
     * @type {PnlPartitionedResponseUpnl}
     * @memberof PnlPartitionedResponse
     */
    upnl?: PnlPartitionedResponseUpnl;
}

/**
 * Check if a given object implements the PnlPartitionedResponse interface.
 */
export function instanceOfPnlPartitionedResponse(value: object): value is PnlPartitionedResponse {
    return true;
}

export function PnlPartitionedResponseFromJSON(json: any): PnlPartitionedResponse {
    return PnlPartitionedResponseFromJSONTyped(json, false);
}

export function PnlPartitionedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PnlPartitionedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'upnl': json['upnl'] == null ? undefined : PnlPartitionedResponseUpnlFromJSON(json['upnl']),
    };
}

export function PnlPartitionedResponseToJSON(json: any): PnlPartitionedResponse {
    return PnlPartitionedResponseToJSONTyped(json, false);
}

export function PnlPartitionedResponseToJSONTyped(value?: PnlPartitionedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'upnl': PnlPartitionedResponseUpnlToJSON(value['upnl']),
    };
}

