/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstructionErrorResultAllOfError } from './InstructionErrorResultAllOfError';
import {
    InstructionErrorResultAllOfErrorFromJSON,
    InstructionErrorResultAllOfErrorFromJSONTyped,
    InstructionErrorResultAllOfErrorToJSON,
    InstructionErrorResultAllOfErrorToJSONTyped,
} from './InstructionErrorResultAllOfError';

/**
 * 
 * @export
 * @interface PollingInstructionResult
 */
export interface PollingInstructionResult {
    /**
     * 
     * @type {number}
     * @memberof PollingInstructionResult
     */
    clientInstructionId: number;
    /**
     * 
     * @type {string}
     * @memberof PollingInstructionResult
     */
    description?: string;
    /**
     * 
     * @type {InstructionErrorResultAllOfError}
     * @memberof PollingInstructionResult
     */
    error?: InstructionErrorResultAllOfError;
    /**
     * 
     * @type {number}
     * @memberof PollingInstructionResult
     */
    ibReferenceId?: number;
    /**
     * 
     * @type {number}
     * @memberof PollingInstructionResult
     */
    instructionId: number;
    /**
     * 
     * @type {PollingInstructionResultInstructionStatusEnum}
     * @memberof PollingInstructionResult
     */
    instructionStatus: PollingInstructionResultInstructionStatusEnum;
    /**
     * 
     * @type {PollingInstructionResultInstructionTypeEnum}
     * @memberof PollingInstructionResult
     */
    instructionType: PollingInstructionResultInstructionTypeEnum;
}


/**
 * @export
 */
export const PollingInstructionResultInstructionStatusEnum = {
    Pending: 'PENDING',
    Rejected: 'REJECTED',
    Processed: 'PROCESSED'
} as const;
export type PollingInstructionResultInstructionStatusEnum = typeof PollingInstructionResultInstructionStatusEnum[keyof typeof PollingInstructionResultInstructionStatusEnum];

/**
 * @export
 */
export const PollingInstructionResultInstructionTypeEnum = {
    AchInstruction: 'ACH_INSTRUCTION',
    CancelInstruction: 'CANCEL_INSTRUCTION',
    ComplexAssetTransfer: 'COMPLEX_ASSET_TRANSFER',
    DeleteBankInstruction: 'DELETE_BANK_INSTRUCTION',
    Deposit: 'DEPOSIT',
    Dwac: 'DWAC',
    ExternalPositionTransfer: 'EXTERNAL_POSITION_TRANSFER',
    Fop: 'FOP',
    QueryRecentInstructions: 'QUERY_RECENT_INSTRUCTIONS',
    QueryWithdrawableFunds: 'QUERY_WITHDRAWABLE_FUNDS',
    InternalPositionTransfer: 'INTERNAL_POSITION_TRANSFER',
    InternalCashTransfer: 'INTERNAL_CASH_TRANSFER',
    MicroAmount: 'MICRO_AMOUNT',
    PredefinedDestinationInstruction: 'PREDEFINED_DESTINATION_INSTRUCTION',
    TraditionalBankInstructionVerification: 'TRADITIONAL_BANK_INSTRUCTION_VERIFICATION',
    Withdrawal: 'WITHDRAWAL',
    QueryIraContributions: 'QUERY_IRA_CONTRIBUTIONS',
    EddaInstruction: 'EDDA_INSTRUCTION',
    QueryRecentRecurringEvents: 'QUERY_RECENT_RECURRING_EVENTS',
    QueryRecurringInstructions: 'QUERY_RECURRING_INSTRUCTIONS',
    QueryAccountBalances: 'QUERY_ACCOUNT_BALANCES',
    QueryBankInstruction: 'QUERY_BANK_INSTRUCTION',
    QueryWithdrawableCashEquity: 'QUERY_WITHDRAWABLE_CASH_EQUITY'
} as const;
export type PollingInstructionResultInstructionTypeEnum = typeof PollingInstructionResultInstructionTypeEnum[keyof typeof PollingInstructionResultInstructionTypeEnum];


/**
 * Check if a given object implements the PollingInstructionResult interface.
 */
export function instanceOfPollingInstructionResult(value: object): value is PollingInstructionResult {
    if (!('clientInstructionId' in value) || value['clientInstructionId'] === undefined) return false;
    if (!('instructionId' in value) || value['instructionId'] === undefined) return false;
    if (!('instructionStatus' in value) || value['instructionStatus'] === undefined) return false;
    if (!('instructionType' in value) || value['instructionType'] === undefined) return false;
    return true;
}

export function PollingInstructionResultFromJSON(json: any): PollingInstructionResult {
    return PollingInstructionResultFromJSONTyped(json, false);
}

export function PollingInstructionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PollingInstructionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'clientInstructionId': json['clientInstructionId'],
        'description': json['description'] == null ? undefined : json['description'],
        'error': json['error'] == null ? undefined : InstructionErrorResultAllOfErrorFromJSON(json['error']),
        'ibReferenceId': json['ibReferenceId'] == null ? undefined : json['ibReferenceId'],
        'instructionId': json['instructionId'],
        'instructionStatus': json['instructionStatus'],
        'instructionType': json['instructionType'],
    };
}

export function PollingInstructionResultToJSON(json: any): PollingInstructionResult {
    return PollingInstructionResultToJSONTyped(json, false);
}

export function PollingInstructionResultToJSONTyped(value?: PollingInstructionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientInstructionId': value['clientInstructionId'],
        'description': value['description'],
        'error': InstructionErrorResultAllOfErrorToJSON(value['error']),
        'ibReferenceId': value['ibReferenceId'],
        'instructionId': value['instructionId'],
        'instructionStatus': value['instructionStatus'],
        'instructionType': value['instructionType'],
    };
}

