/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioSummarySma
 */
export interface PortfolioSummarySma {
    /**
     * Numerical data for the associated key.
     * @type {number}
     * @memberof PortfolioSummarySma
     */
    amount?: number;
    /**
     * The currency in which the value of the 'amount' field is denominated.
     * @type {number}
     * @memberof PortfolioSummarySma
     */
    currency?: number;
    /**
     * Indicates whether the associated key's value does not exist, as opposed to a value of zero.
     * @type {boolean}
     * @memberof PortfolioSummarySma
     */
    isNull?: boolean;
    /**
     * severity
     * @type {number}
     * @memberof PortfolioSummarySma
     */
    severity?: number;
    /**
     * Unix epoch timestamp of returned data in milliseconds.
     * @type {number}
     * @memberof PortfolioSummarySma
     */
    timestamp?: number;
    /**
     * String and boolean (non-numerical) data for the associated key.
     * @type {string}
     * @memberof PortfolioSummarySma
     */
    value?: string;
}

/**
 * Check if a given object implements the PortfolioSummarySma interface.
 */
export function instanceOfPortfolioSummarySma(value: object): value is PortfolioSummarySma {
    return true;
}

export function PortfolioSummarySmaFromJSON(json: any): PortfolioSummarySma {
    return PortfolioSummarySmaFromJSONTyped(json, false);
}

export function PortfolioSummarySmaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioSummarySma {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'isNull': json['isNull'] == null ? undefined : json['isNull'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function PortfolioSummarySmaToJSON(json: any): PortfolioSummarySma {
    return PortfolioSummarySmaToJSONTyped(json, false);
}

export function PortfolioSummarySmaToJSONTyped(value?: PortfolioSummarySma | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'isNull': value['isNull'],
        'severity': value['severity'],
        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}

