/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioSummaryExcessliquidityS
 */
export interface PortfolioSummaryExcessliquidityS {
    /**
     * Numerical data for the associated key.
     * @type {number}
     * @memberof PortfolioSummaryExcessliquidityS
     */
    amount?: number;
    /**
     * The currency in which the value of the 'amount' field is denominated.
     * @type {number}
     * @memberof PortfolioSummaryExcessliquidityS
     */
    currency?: number;
    /**
     * Indicates whether the associated key's value does not exist, as opposed to a value of zero.
     * @type {boolean}
     * @memberof PortfolioSummaryExcessliquidityS
     */
    isNull?: boolean;
    /**
     * severity
     * @type {number}
     * @memberof PortfolioSummaryExcessliquidityS
     */
    severity?: number;
    /**
     * Unix epoch timestamp of returned data in milliseconds.
     * @type {number}
     * @memberof PortfolioSummaryExcessliquidityS
     */
    timestamp?: number;
    /**
     * String and boolean (non-numerical) data for the associated key.
     * @type {string}
     * @memberof PortfolioSummaryExcessliquidityS
     */
    value?: string;
}

/**
 * Check if a given object implements the PortfolioSummaryExcessliquidityS interface.
 */
export function instanceOfPortfolioSummaryExcessliquidityS(value: object): value is PortfolioSummaryExcessliquidityS {
    return true;
}

export function PortfolioSummaryExcessliquiditySFromJSON(json: any): PortfolioSummaryExcessliquidityS {
    return PortfolioSummaryExcessliquiditySFromJSONTyped(json, false);
}

export function PortfolioSummaryExcessliquiditySFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioSummaryExcessliquidityS {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'isNull': json['isNull'] == null ? undefined : json['isNull'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function PortfolioSummaryExcessliquiditySToJSON(json: any): PortfolioSummaryExcessliquidityS {
    return PortfolioSummaryExcessliquiditySToJSONTyped(json, false);
}

export function PortfolioSummaryExcessliquiditySToJSONTyped(value?: PortfolioSummaryExcessliquidityS | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'isNull': value['isNull'],
        'severity': value['severity'],
        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}

