/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostGwApiV1InternalAssetTransfersBulkRequest
 */
export interface PostGwApiV1InternalAssetTransfersBulkRequest {
    /**
     * 
     * @type {PostGwApiV1InternalAssetTransfersBulkRequestInstructionTypeEnum}
     * @memberof PostGwApiV1InternalAssetTransfersBulkRequest
     */
    instructionType: PostGwApiV1InternalAssetTransfersBulkRequestInstructionTypeEnum;
    /**
     * 
     * @type {Array<any>}
     * @memberof PostGwApiV1InternalAssetTransfersBulkRequest
     */
    instructions: Array<any>;
}


/**
 * @export
 */
export const PostGwApiV1InternalAssetTransfersBulkRequestInstructionTypeEnum = {
    InternalPositionTransfer: 'INTERNAL_POSITION_TRANSFER'
} as const;
export type PostGwApiV1InternalAssetTransfersBulkRequestInstructionTypeEnum = typeof PostGwApiV1InternalAssetTransfersBulkRequestInstructionTypeEnum[keyof typeof PostGwApiV1InternalAssetTransfersBulkRequestInstructionTypeEnum];


/**
 * Check if a given object implements the PostGwApiV1InternalAssetTransfersBulkRequest interface.
 */
export function instanceOfPostGwApiV1InternalAssetTransfersBulkRequest(value: object): value is PostGwApiV1InternalAssetTransfersBulkRequest {
    if (!('instructionType' in value) || value['instructionType'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    return true;
}

export function PostGwApiV1InternalAssetTransfersBulkRequestFromJSON(json: any): PostGwApiV1InternalAssetTransfersBulkRequest {
    return PostGwApiV1InternalAssetTransfersBulkRequestFromJSONTyped(json, false);
}

export function PostGwApiV1InternalAssetTransfersBulkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGwApiV1InternalAssetTransfersBulkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'instructionType': json['instructionType'],
        'instructions': json['instructions'],
    };
}

export function PostGwApiV1InternalAssetTransfersBulkRequestToJSON(json: any): PostGwApiV1InternalAssetTransfersBulkRequest {
    return PostGwApiV1InternalAssetTransfersBulkRequestToJSONTyped(json, false);
}

export function PostGwApiV1InternalAssetTransfersBulkRequestToJSONTyped(value?: PostGwApiV1InternalAssetTransfersBulkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instructionType': value['instructionType'],
        'instructions': value['instructions'],
    };
}

