/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalPositionTransferInstruction } from './InternalPositionTransferInstruction';
import {
    InternalPositionTransferInstructionFromJSON,
    InternalPositionTransferInstructionFromJSONTyped,
    InternalPositionTransferInstructionToJSON,
    InternalPositionTransferInstructionToJSONTyped,
} from './InternalPositionTransferInstruction';

/**
 * 
 * @export
 * @interface PostGwApiV1InternalAssetTransfersRequest
 */
export interface PostGwApiV1InternalAssetTransfersRequest {
    /**
     * 
     * @type {InternalPositionTransferInstruction}
     * @memberof PostGwApiV1InternalAssetTransfersRequest
     */
    instruction: InternalPositionTransferInstruction;
    /**
     * 
     * @type {PostGwApiV1InternalAssetTransfersRequestInstructionTypeEnum}
     * @memberof PostGwApiV1InternalAssetTransfersRequest
     */
    instructionType: PostGwApiV1InternalAssetTransfersRequestInstructionTypeEnum;
}


/**
 * @export
 */
export const PostGwApiV1InternalAssetTransfersRequestInstructionTypeEnum = {
    InternalPositionTransfer: 'INTERNAL_POSITION_TRANSFER'
} as const;
export type PostGwApiV1InternalAssetTransfersRequestInstructionTypeEnum = typeof PostGwApiV1InternalAssetTransfersRequestInstructionTypeEnum[keyof typeof PostGwApiV1InternalAssetTransfersRequestInstructionTypeEnum];


/**
 * Check if a given object implements the PostGwApiV1InternalAssetTransfersRequest interface.
 */
export function instanceOfPostGwApiV1InternalAssetTransfersRequest(value: object): value is PostGwApiV1InternalAssetTransfersRequest {
    if (!('instruction' in value) || value['instruction'] === undefined) return false;
    if (!('instructionType' in value) || value['instructionType'] === undefined) return false;
    return true;
}

export function PostGwApiV1InternalAssetTransfersRequestFromJSON(json: any): PostGwApiV1InternalAssetTransfersRequest {
    return PostGwApiV1InternalAssetTransfersRequestFromJSONTyped(json, false);
}

export function PostGwApiV1InternalAssetTransfersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGwApiV1InternalAssetTransfersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'instruction': InternalPositionTransferInstructionFromJSON(json['instruction']),
        'instructionType': json['instructionType'],
    };
}

export function PostGwApiV1InternalAssetTransfersRequestToJSON(json: any): PostGwApiV1InternalAssetTransfersRequest {
    return PostGwApiV1InternalAssetTransfersRequestToJSONTyped(json, false);
}

export function PostGwApiV1InternalAssetTransfersRequestToJSONTyped(value?: PostGwApiV1InternalAssetTransfersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instruction': InternalPositionTransferInstructionToJSON(value['instruction']),
        'instructionType': value['instructionType'],
    };
}

