/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryWithdrawableCashEquity } from './QueryWithdrawableCashEquity';
import {
    QueryWithdrawableCashEquityFromJSON,
    QueryWithdrawableCashEquityFromJSONTyped,
    QueryWithdrawableCashEquityToJSON,
    QueryWithdrawableCashEquityToJSONTyped,
} from './QueryWithdrawableCashEquity';

/**
 * 
 * @export
 * @interface PostGwApiV1BalancesQueryRequest
 */
export interface PostGwApiV1BalancesQueryRequest {
    /**
     * 
     * @type {QueryWithdrawableCashEquity}
     * @memberof PostGwApiV1BalancesQueryRequest
     */
    instruction: QueryWithdrawableCashEquity;
    /**
     * 
     * @type {PostGwApiV1BalancesQueryRequestInstructionTypeEnum}
     * @memberof PostGwApiV1BalancesQueryRequest
     */
    instructionType: PostGwApiV1BalancesQueryRequestInstructionTypeEnum;
}


/**
 * @export
 */
export const PostGwApiV1BalancesQueryRequestInstructionTypeEnum = {
    QueryWithdrawableCashEquity: 'QUERY_WITHDRAWABLE_CASH_EQUITY'
} as const;
export type PostGwApiV1BalancesQueryRequestInstructionTypeEnum = typeof PostGwApiV1BalancesQueryRequestInstructionTypeEnum[keyof typeof PostGwApiV1BalancesQueryRequestInstructionTypeEnum];


/**
 * Check if a given object implements the PostGwApiV1BalancesQueryRequest interface.
 */
export function instanceOfPostGwApiV1BalancesQueryRequest(value: object): value is PostGwApiV1BalancesQueryRequest {
    if (!('instruction' in value) || value['instruction'] === undefined) return false;
    if (!('instructionType' in value) || value['instructionType'] === undefined) return false;
    return true;
}

export function PostGwApiV1BalancesQueryRequestFromJSON(json: any): PostGwApiV1BalancesQueryRequest {
    return PostGwApiV1BalancesQueryRequestFromJSONTyped(json, false);
}

export function PostGwApiV1BalancesQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGwApiV1BalancesQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'instruction': QueryWithdrawableCashEquityFromJSON(json['instruction']),
        'instructionType': json['instructionType'],
    };
}

export function PostGwApiV1BalancesQueryRequestToJSON(json: any): PostGwApiV1BalancesQueryRequest {
    return PostGwApiV1BalancesQueryRequestToJSONTyped(json, false);
}

export function PostGwApiV1BalancesQueryRequestToJSONTyped(value?: PostGwApiV1BalancesQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instruction': QueryWithdrawableCashEquityToJSON(value['instruction']),
        'instructionType': value['instructionType'],
    };
}

