/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostGwApiV1InstructionsCancelBulkRequest
 */
export interface PostGwApiV1InstructionsCancelBulkRequest {
    /**
     * 
     * @type {PostGwApiV1InstructionsCancelBulkRequestInstructionTypeEnum}
     * @memberof PostGwApiV1InstructionsCancelBulkRequest
     */
    instructionType: PostGwApiV1InstructionsCancelBulkRequestInstructionTypeEnum;
    /**
     * 
     * @type {Array<any>}
     * @memberof PostGwApiV1InstructionsCancelBulkRequest
     */
    instructions: Array<any>;
}


/**
 * @export
 */
export const PostGwApiV1InstructionsCancelBulkRequestInstructionTypeEnum = {
    CancelInstruction: 'CANCEL_INSTRUCTION'
} as const;
export type PostGwApiV1InstructionsCancelBulkRequestInstructionTypeEnum = typeof PostGwApiV1InstructionsCancelBulkRequestInstructionTypeEnum[keyof typeof PostGwApiV1InstructionsCancelBulkRequestInstructionTypeEnum];


/**
 * Check if a given object implements the PostGwApiV1InstructionsCancelBulkRequest interface.
 */
export function instanceOfPostGwApiV1InstructionsCancelBulkRequest(value: object): value is PostGwApiV1InstructionsCancelBulkRequest {
    if (!('instructionType' in value) || value['instructionType'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    return true;
}

export function PostGwApiV1InstructionsCancelBulkRequestFromJSON(json: any): PostGwApiV1InstructionsCancelBulkRequest {
    return PostGwApiV1InstructionsCancelBulkRequestFromJSONTyped(json, false);
}

export function PostGwApiV1InstructionsCancelBulkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGwApiV1InstructionsCancelBulkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'instructionType': json['instructionType'],
        'instructions': json['instructions'],
    };
}

export function PostGwApiV1InstructionsCancelBulkRequestToJSON(json: any): PostGwApiV1InstructionsCancelBulkRequest {
    return PostGwApiV1InstructionsCancelBulkRequestToJSONTyped(json, false);
}

export function PostGwApiV1InstructionsCancelBulkRequestToJSONTyped(value?: PostGwApiV1InstructionsCancelBulkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instructionType': value['instructionType'],
        'instructions': value['instructions'],
    };
}

