/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryBankInstruction
 */
export interface QueryBankInstruction {
    /**
     * 
     * @type {string}
     * @memberof QueryBankInstruction
     */
    accountId: string;
    /**
     * 
     * @type {QueryBankInstructionBankInstructionMethodEnum}
     * @memberof QueryBankInstruction
     */
    bankInstructionMethod: QueryBankInstructionBankInstructionMethodEnum;
    /**
     * 
     * @type {number}
     * @memberof QueryBankInstruction
     */
    clientInstructionId: number;
}


/**
 * @export
 */
export const QueryBankInstructionBankInstructionMethodEnum = {
    Ach: 'ACH',
    Wire: 'WIRE',
    Usach: 'USACH',
    Caach: 'CAACH',
    Sepa: 'SEPA',
    EDda: 'eDDA',
    EGiro: 'eGIRO',
    OpenBanking: 'OPEN_BANKING'
} as const;
export type QueryBankInstructionBankInstructionMethodEnum = typeof QueryBankInstructionBankInstructionMethodEnum[keyof typeof QueryBankInstructionBankInstructionMethodEnum];


/**
 * Check if a given object implements the QueryBankInstruction interface.
 */
export function instanceOfQueryBankInstruction(value: object): value is QueryBankInstruction {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('bankInstructionMethod' in value) || value['bankInstructionMethod'] === undefined) return false;
    if (!('clientInstructionId' in value) || value['clientInstructionId'] === undefined) return false;
    return true;
}

export function QueryBankInstructionFromJSON(json: any): QueryBankInstruction {
    return QueryBankInstructionFromJSONTyped(json, false);
}

export function QueryBankInstructionFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryBankInstruction {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'bankInstructionMethod': json['bankInstructionMethod'],
        'clientInstructionId': json['clientInstructionId'],
    };
}

export function QueryBankInstructionToJSON(json: any): QueryBankInstruction {
    return QueryBankInstructionToJSONTyped(json, false);
}

export function QueryBankInstructionToJSONTyped(value?: QueryBankInstruction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'bankInstructionMethod': value['bankInstructionMethod'],
        'clientInstructionId': value['clientInstructionId'],
    };
}

