/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryWithdrawableFunds
 */
export interface QueryWithdrawableFunds {
    /**
     * 
     * @type {string}
     * @memberof QueryWithdrawableFunds
     */
    accountId: string;
    /**
     * If bankAccountNumber is provided then bankRoutingNumber is also required, cannot be passed with bankInstructionName
     * @type {string}
     * @memberof QueryWithdrawableFunds
     */
    bankAccountNumber?: string;
    /**
     * bankInstructionName cannot be passed with (bankAccountNumber or bankRoutingNumber)
     * @type {string}
     * @memberof QueryWithdrawableFunds
     */
    bankInstructionName?: string;
    /**
     * If bankRoutingNumber is provided then bankAccountNumber is also required, cannot be passed with bankInstructionName
     * @type {string}
     * @memberof QueryWithdrawableFunds
     */
    bankRoutingNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof QueryWithdrawableFunds
     */
    clientInstructionId: number;
    /**
     * 
     * @type {string}
     * @memberof QueryWithdrawableFunds
     */
    currency: string;
}

/**
 * Check if a given object implements the QueryWithdrawableFunds interface.
 */
export function instanceOfQueryWithdrawableFunds(value: object): value is QueryWithdrawableFunds {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('clientInstructionId' in value) || value['clientInstructionId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function QueryWithdrawableFundsFromJSON(json: any): QueryWithdrawableFunds {
    return QueryWithdrawableFundsFromJSONTyped(json, false);
}

export function QueryWithdrawableFundsFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryWithdrawableFunds {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'bankAccountNumber': json['bankAccountNumber'] == null ? undefined : json['bankAccountNumber'],
        'bankInstructionName': json['bankInstructionName'] == null ? undefined : json['bankInstructionName'],
        'bankRoutingNumber': json['bankRoutingNumber'] == null ? undefined : json['bankRoutingNumber'],
        'clientInstructionId': json['clientInstructionId'],
        'currency': json['currency'],
    };
}

export function QueryWithdrawableFundsToJSON(json: any): QueryWithdrawableFunds {
    return QueryWithdrawableFundsToJSONTyped(json, false);
}

export function QueryWithdrawableFundsToJSONTyped(value?: QueryWithdrawableFunds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'bankAccountNumber': value['bankAccountNumber'],
        'bankInstructionName': value['bankInstructionName'],
        'bankRoutingNumber': value['bankRoutingNumber'],
        'clientInstructionId': value['clientInstructionId'],
        'currency': value['currency'],
    };
}

