/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryIRAContributionsResultAllOfContributions } from './QueryIRAContributionsResultAllOfContributions';
import {
    QueryIRAContributionsResultAllOfContributionsFromJSON,
    QueryIRAContributionsResultAllOfContributionsFromJSONTyped,
    QueryIRAContributionsResultAllOfContributionsToJSON,
    QueryIRAContributionsResultAllOfContributionsToJSONTyped,
} from './QueryIRAContributionsResultAllOfContributions';
import type { InstructionErrorResultAllOfError } from './InstructionErrorResultAllOfError';
import {
    InstructionErrorResultAllOfErrorFromJSON,
    InstructionErrorResultAllOfErrorFromJSONTyped,
    InstructionErrorResultAllOfErrorToJSON,
    InstructionErrorResultAllOfErrorToJSONTyped,
} from './InstructionErrorResultAllOfError';

/**
 * 
 * @export
 * @interface QueryIRAContributionsResult
 */
export interface QueryIRAContributionsResult {
    /**
     * 
     * @type {number}
     * @memberof QueryIRAContributionsResult
     */
    clientInstructionId: number;
    /**
     * 
     * @type {string}
     * @memberof QueryIRAContributionsResult
     */
    description?: string;
    /**
     * 
     * @type {InstructionErrorResultAllOfError}
     * @memberof QueryIRAContributionsResult
     */
    error?: InstructionErrorResultAllOfError;
    /**
     * 
     * @type {number}
     * @memberof QueryIRAContributionsResult
     */
    ibReferenceId?: number;
    /**
     * 
     * @type {number}
     * @memberof QueryIRAContributionsResult
     */
    instructionId: number;
    /**
     * 
     * @type {QueryIRAContributionsResultInstructionStatusEnum}
     * @memberof QueryIRAContributionsResult
     */
    instructionStatus: QueryIRAContributionsResultInstructionStatusEnum;
    /**
     * 
     * @type {QueryIRAContributionsResultInstructionTypeEnum}
     * @memberof QueryIRAContributionsResult
     */
    instructionType: QueryIRAContributionsResultInstructionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof QueryIRAContributionsResult
     */
    accountId: string;
    /**
     * 
     * @type {Array<QueryIRAContributionsResultAllOfContributions>}
     * @memberof QueryIRAContributionsResult
     */
    contributions: Array<QueryIRAContributionsResultAllOfContributions>;
    /**
     * 
     * @type {string}
     * @memberof QueryIRAContributionsResult
     */
    iraType: string;
    /**
     * 
     * @type {string}
     * @memberof QueryIRAContributionsResult
     */
    year: string;
}


/**
 * @export
 */
export const QueryIRAContributionsResultInstructionStatusEnum = {
    Pending: 'PENDING',
    Rejected: 'REJECTED',
    Processed: 'PROCESSED'
} as const;
export type QueryIRAContributionsResultInstructionStatusEnum = typeof QueryIRAContributionsResultInstructionStatusEnum[keyof typeof QueryIRAContributionsResultInstructionStatusEnum];

/**
 * @export
 */
export const QueryIRAContributionsResultInstructionTypeEnum = {
    AchInstruction: 'ACH_INSTRUCTION',
    CancelInstruction: 'CANCEL_INSTRUCTION',
    ComplexAssetTransfer: 'COMPLEX_ASSET_TRANSFER',
    DeleteBankInstruction: 'DELETE_BANK_INSTRUCTION',
    Deposit: 'DEPOSIT',
    Dwac: 'DWAC',
    ExternalPositionTransfer: 'EXTERNAL_POSITION_TRANSFER',
    Fop: 'FOP',
    QueryRecentInstructions: 'QUERY_RECENT_INSTRUCTIONS',
    QueryWithdrawableFunds: 'QUERY_WITHDRAWABLE_FUNDS',
    InternalPositionTransfer: 'INTERNAL_POSITION_TRANSFER',
    InternalCashTransfer: 'INTERNAL_CASH_TRANSFER',
    MicroAmount: 'MICRO_AMOUNT',
    PredefinedDestinationInstruction: 'PREDEFINED_DESTINATION_INSTRUCTION',
    TraditionalBankInstructionVerification: 'TRADITIONAL_BANK_INSTRUCTION_VERIFICATION',
    Withdrawal: 'WITHDRAWAL',
    QueryIraContributions: 'QUERY_IRA_CONTRIBUTIONS',
    EddaInstruction: 'EDDA_INSTRUCTION',
    QueryRecentRecurringEvents: 'QUERY_RECENT_RECURRING_EVENTS',
    QueryRecurringInstructions: 'QUERY_RECURRING_INSTRUCTIONS',
    QueryAccountBalances: 'QUERY_ACCOUNT_BALANCES',
    QueryBankInstruction: 'QUERY_BANK_INSTRUCTION',
    QueryWithdrawableCashEquity: 'QUERY_WITHDRAWABLE_CASH_EQUITY'
} as const;
export type QueryIRAContributionsResultInstructionTypeEnum = typeof QueryIRAContributionsResultInstructionTypeEnum[keyof typeof QueryIRAContributionsResultInstructionTypeEnum];


/**
 * Check if a given object implements the QueryIRAContributionsResult interface.
 */
export function instanceOfQueryIRAContributionsResult(value: object): value is QueryIRAContributionsResult {
    if (!('clientInstructionId' in value) || value['clientInstructionId'] === undefined) return false;
    if (!('instructionId' in value) || value['instructionId'] === undefined) return false;
    if (!('instructionStatus' in value) || value['instructionStatus'] === undefined) return false;
    if (!('instructionType' in value) || value['instructionType'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('contributions' in value) || value['contributions'] === undefined) return false;
    if (!('iraType' in value) || value['iraType'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    return true;
}

export function QueryIRAContributionsResultFromJSON(json: any): QueryIRAContributionsResult {
    return QueryIRAContributionsResultFromJSONTyped(json, false);
}

export function QueryIRAContributionsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryIRAContributionsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'clientInstructionId': json['clientInstructionId'],
        'description': json['description'] == null ? undefined : json['description'],
        'error': json['error'] == null ? undefined : InstructionErrorResultAllOfErrorFromJSON(json['error']),
        'ibReferenceId': json['ibReferenceId'] == null ? undefined : json['ibReferenceId'],
        'instructionId': json['instructionId'],
        'instructionStatus': json['instructionStatus'],
        'instructionType': json['instructionType'],
        'accountId': json['accountId'],
        'contributions': ((json['contributions'] as Array<any>).map(QueryIRAContributionsResultAllOfContributionsFromJSON)),
        'iraType': json['iraType'],
        'year': json['year'],
    };
}

export function QueryIRAContributionsResultToJSON(json: any): QueryIRAContributionsResult {
    return QueryIRAContributionsResultToJSONTyped(json, false);
}

export function QueryIRAContributionsResultToJSONTyped(value?: QueryIRAContributionsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientInstructionId': value['clientInstructionId'],
        'description': value['description'],
        'error': InstructionErrorResultAllOfErrorToJSON(value['error']),
        'ibReferenceId': value['ibReferenceId'],
        'instructionId': value['instructionId'],
        'instructionStatus': value['instructionStatus'],
        'instructionType': value['instructionType'],
        'accountId': value['accountId'],
        'contributions': ((value['contributions'] as Array<any>).map(QueryIRAContributionsResultAllOfContributionsToJSON)),
        'iraType': value['iraType'],
        'year': value['year'],
    };
}

