/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationTask
 */
export interface RegistrationTask {
    /**
     * 
     * @type {string}
     * @memberof RegistrationTask
     */
    action?: string;
    /**
     * 
     * @type {Date}
     * @memberof RegistrationTask
     */
    dateCompleted?: Date;
    /**
     * 
     * @type {string}
     * @memberof RegistrationTask
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationTask
     */
    formName?: string;
    /**
     * 
     * @type {number}
     * @memberof RegistrationTask
     */
    formNumber?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RegistrationTask
     */
    isCompleted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegistrationTask
     */
    isDeclined?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegistrationTask
     */
    isRequiredForApproval?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof RegistrationTask
     */
    questionIds?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof RegistrationTask
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationTask
     */
    warning?: string;
}

/**
 * Check if a given object implements the RegistrationTask interface.
 */
export function instanceOfRegistrationTask(value: object): value is RegistrationTask {
    return true;
}

export function RegistrationTaskFromJSON(json: any): RegistrationTask {
    return RegistrationTaskFromJSONTyped(json, false);
}

export function RegistrationTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationTask {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'dateCompleted': json['dateCompleted'] == null ? undefined : (new Date(json['dateCompleted'])),
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'formName': json['formName'] == null ? undefined : json['formName'],
        'formNumber': json['formNumber'] == null ? undefined : json['formNumber'],
        'isCompleted': json['isCompleted'] == null ? undefined : json['isCompleted'],
        'isDeclined': json['isDeclined'] == null ? undefined : json['isDeclined'],
        'isRequiredForApproval': json['isRequiredForApproval'] == null ? undefined : json['isRequiredForApproval'],
        'questionIds': json['questionIds'] == null ? undefined : json['questionIds'],
        'state': json['state'] == null ? undefined : json['state'],
        'warning': json['warning'] == null ? undefined : json['warning'],
    };
}

export function RegistrationTaskToJSON(json: any): RegistrationTask {
    return RegistrationTaskToJSONTyped(json, false);
}

export function RegistrationTaskToJSONTyped(value?: RegistrationTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'dateCompleted': value['dateCompleted'] == null ? value['dateCompleted'] : value['dateCompleted'].toISOString(),
        'externalId': value['externalId'],
        'formName': value['formName'],
        'formNumber': value['formNumber'],
        'isCompleted': value['isCompleted'],
        'isDeclined': value['isDeclined'],
        'isRequiredForApproval': value['isRequiredForApproval'],
        'questionIds': value['questionIds'],
        'state': value['state'],
        'warning': value['warning'],
    };
}

