/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequiredFormsRequest
 */
export interface RequiredFormsRequest {
    /**
     * 
     * @type {string}
     * @memberof RequiredFormsRequest
     */
    accountType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequiredFormsRequest
     */
    additionalAccount?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RequiredFormsRequest
     */
    additionalApplicant?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequiredFormsRequest
     */
    applicantType?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RequiredFormsRequest
     */
    capability?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof RequiredFormsRequest
     */
    faTradingAccount?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RequiredFormsRequest
     */
    ira?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequiredFormsRequest
     */
    iraType?: string;
    /**
     * 
     * @type {string}
     * @memberof RequiredFormsRequest
     */
    mifidCategory?: string;
    /**
     * 
     * @type {string}
     * @memberof RequiredFormsRequest
     */
    processType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequiredFormsRequest
     */
    requestedFCBP?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RequiredFormsRequest
     */
    requestedSYEP?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequiredFormsRequest
     */
    residenceCountry?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RequiredFormsRequest
     */
    tradingPermissions?: Array<string>;
}

/**
 * Check if a given object implements the RequiredFormsRequest interface.
 */
export function instanceOfRequiredFormsRequest(value: object): value is RequiredFormsRequest {
    return true;
}

export function RequiredFormsRequestFromJSON(json: any): RequiredFormsRequest {
    return RequiredFormsRequestFromJSONTyped(json, false);
}

export function RequiredFormsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequiredFormsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountType': json['accountType'] == null ? undefined : json['accountType'],
        'additionalAccount': json['additionalAccount'] == null ? undefined : json['additionalAccount'],
        'additionalApplicant': json['additionalApplicant'] == null ? undefined : json['additionalApplicant'],
        'applicantType': json['applicantType'] == null ? undefined : json['applicantType'],
        'capability': json['capability'] == null ? undefined : json['capability'],
        'faTradingAccount': json['faTradingAccount'] == null ? undefined : json['faTradingAccount'],
        'ira': json['ira'] == null ? undefined : json['ira'],
        'iraType': json['iraType'] == null ? undefined : json['iraType'],
        'mifidCategory': json['mifidCategory'] == null ? undefined : json['mifidCategory'],
        'processType': json['processType'] == null ? undefined : json['processType'],
        'requestedFCBP': json['requestedFCBP'] == null ? undefined : json['requestedFCBP'],
        'requestedSYEP': json['requestedSYEP'] == null ? undefined : json['requestedSYEP'],
        'residenceCountry': json['residenceCountry'] == null ? undefined : json['residenceCountry'],
        'tradingPermissions': json['tradingPermissions'] == null ? undefined : json['tradingPermissions'],
    };
}

export function RequiredFormsRequestToJSON(json: any): RequiredFormsRequest {
    return RequiredFormsRequestToJSONTyped(json, false);
}

export function RequiredFormsRequestToJSONTyped(value?: RequiredFormsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountType': value['accountType'],
        'additionalAccount': value['additionalAccount'],
        'additionalApplicant': value['additionalApplicant'],
        'applicantType': value['applicantType'],
        'capability': value['capability'],
        'faTradingAccount': value['faTradingAccount'],
        'ira': value['ira'],
        'iraType': value['iraType'],
        'mifidCategory': value['mifidCategory'],
        'processType': value['processType'],
        'requestedFCBP': value['requestedFCBP'],
        'requestedSYEP': value['requestedSYEP'],
        'residenceCountry': value['residenceCountry'],
        'tradingPermissions': value['tradingPermissions'],
    };
}

