/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleResponseSchedulesDate } from './ScheduleResponseSchedulesDate';
import {
    ScheduleResponseSchedulesDateFromJSON,
    ScheduleResponseSchedulesDateFromJSONTyped,
    ScheduleResponseSchedulesDateToJSON,
    ScheduleResponseSchedulesDateToJSONTyped,
} from './ScheduleResponseSchedulesDate';

/**
 * Returns a series of date objects of the given contract.
 * @export
 * @interface ScheduleResponseSchedules
 */
export interface ScheduleResponseSchedules {
    /**
     * 
     * @type {ScheduleResponseSchedulesDate}
     * @memberof ScheduleResponseSchedules
     */
    date?: ScheduleResponseSchedulesDate;
}

/**
 * Check if a given object implements the ScheduleResponseSchedules interface.
 */
export function instanceOfScheduleResponseSchedules(value: object): value is ScheduleResponseSchedules {
    return true;
}

export function ScheduleResponseSchedulesFromJSON(json: any): ScheduleResponseSchedules {
    return ScheduleResponseSchedulesFromJSONTyped(json, false);
}

export function ScheduleResponseSchedulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleResponseSchedules {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : ScheduleResponseSchedulesDateFromJSON(json['date']),
    };
}

export function ScheduleResponseSchedulesToJSON(json: any): ScheduleResponseSchedules {
    return ScheduleResponseSchedulesToJSONTyped(json, false);
}

export function ScheduleResponseSchedulesToJSONTyped(value?: ScheduleResponseSchedules | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ScheduleResponseSchedulesDateToJSON(value['date']),
    };
}

