/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleResponseSchedulesDateLiquidHoursInner
 */
export interface ScheduleResponseSchedulesDateLiquidHoursInner {
    /**
     * Epoch timestamp of the exchange's close.
     * @type {number}
     * @memberof ScheduleResponseSchedulesDateLiquidHoursInner
     */
    closing?: number;
    /**
     * Epoch timestamp of the exchange's open.
     * @type {number}
     * @memberof ScheduleResponseSchedulesDateLiquidHoursInner
     */
    opening?: number;
}

/**
 * Check if a given object implements the ScheduleResponseSchedulesDateLiquidHoursInner interface.
 */
export function instanceOfScheduleResponseSchedulesDateLiquidHoursInner(value: object): value is ScheduleResponseSchedulesDateLiquidHoursInner {
    return true;
}

export function ScheduleResponseSchedulesDateLiquidHoursInnerFromJSON(json: any): ScheduleResponseSchedulesDateLiquidHoursInner {
    return ScheduleResponseSchedulesDateLiquidHoursInnerFromJSONTyped(json, false);
}

export function ScheduleResponseSchedulesDateLiquidHoursInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleResponseSchedulesDateLiquidHoursInner {
    if (json == null) {
        return json;
    }
    return {
        
        'closing': json['closing'] == null ? undefined : json['closing'],
        'opening': json['opening'] == null ? undefined : json['opening'],
    };
}

export function ScheduleResponseSchedulesDateLiquidHoursInnerToJSON(json: any): ScheduleResponseSchedulesDateLiquidHoursInner {
    return ScheduleResponseSchedulesDateLiquidHoursInnerToJSONTyped(json, false);
}

export function ScheduleResponseSchedulesDateLiquidHoursInnerToJSONTyped(value?: ScheduleResponseSchedulesDateLiquidHoursInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'closing': value['closing'],
        'opening': value['opening'],
    };
}

