/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetModelTargetPositionsRequestCashTargetsInner
 */
export interface SetModelTargetPositionsRequestCashTargetsInner {
    /**
     * Currency code to hold positions.
     * @type {string}
     * @memberof SetModelTargetPositionsRequestCashTargetsInner
     */
    ccy?: string;
    /**
     * Percentage of model to distribute to the given currency.
     * @type {number}
     * @memberof SetModelTargetPositionsRequestCashTargetsInner
     */
    target?: number;
}

/**
 * Check if a given object implements the SetModelTargetPositionsRequestCashTargetsInner interface.
 */
export function instanceOfSetModelTargetPositionsRequestCashTargetsInner(value: object): value is SetModelTargetPositionsRequestCashTargetsInner {
    return true;
}

export function SetModelTargetPositionsRequestCashTargetsInnerFromJSON(json: any): SetModelTargetPositionsRequestCashTargetsInner {
    return SetModelTargetPositionsRequestCashTargetsInnerFromJSONTyped(json, false);
}

export function SetModelTargetPositionsRequestCashTargetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetModelTargetPositionsRequestCashTargetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'ccy': json['ccy'] == null ? undefined : json['ccy'],
        'target': json['target'] == null ? undefined : json['target'],
    };
}

export function SetModelTargetPositionsRequestCashTargetsInnerToJSON(json: any): SetModelTargetPositionsRequestCashTargetsInner {
    return SetModelTargetPositionsRequestCashTargetsInnerToJSONTyped(json, false);
}

export function SetModelTargetPositionsRequestCashTargetsInnerToJSONTyped(value?: SetModelTargetPositionsRequestCashTargetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ccy': value['ccy'],
        'target': value['target'],
    };
}

