/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetModelTargetPositions200Response
 */
export interface SetModelTargetPositions200Response {
    /**
     * Request identifier to uniquely track a request.
     * @type {number}
     * @memberof SetModelTargetPositions200Response
     */
    reqID?: number;
    /**
     * Signifies that the request was successfully submitted.
     * @type {boolean}
     * @memberof SetModelTargetPositions200Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the SetModelTargetPositions200Response interface.
 */
export function instanceOfSetModelTargetPositions200Response(value: object): value is SetModelTargetPositions200Response {
    return true;
}

export function SetModelTargetPositions200ResponseFromJSON(json: any): SetModelTargetPositions200Response {
    return SetModelTargetPositions200ResponseFromJSONTyped(json, false);
}

export function SetModelTargetPositions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetModelTargetPositions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'reqID': json['reqID'] == null ? undefined : json['reqID'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function SetModelTargetPositions200ResponseToJSON(json: any): SetModelTargetPositions200Response {
    return SetModelTargetPositions200ResponseToJSONTyped(json, false);
}

export function SetModelTargetPositions200ResponseToJSONTyped(value?: SetModelTargetPositions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reqID': value['reqID'],
        'success': value['success'],
    };
}

