/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object containing Bid and Ask data for a single OHLC bar.
 * @export
 * @interface SingleHistoricalBarBidAsk
 */
export interface SingleHistoricalBarBidAsk {
    /**
     * Closing value of the bar. Indicates the time average ask during the bar.
     * @type {number}
     * @memberof SingleHistoricalBarBidAsk
     */
    c?: number;
    /**
     * High value of the bar. Indicates the highest ask price during the bar.
     * @type {number}
     * @memberof SingleHistoricalBarBidAsk
     */
    h?: number;
    /**
     * Low value of the bar. Indicates the lowest bid price during the bar.
     * @type {number}
     * @memberof SingleHistoricalBarBidAsk
     */
    l?: number;
    /**
     * Opening value of the bar. Indicates the time average bid during the bar.
     * @type {number}
     * @memberof SingleHistoricalBarBidAsk
     */
    o?: number;
    /**
     * Unix timestamp of the start (chronologically earlier) of the bar.
     * @type {number}
     * @memberof SingleHistoricalBarBidAsk
     */
    t?: number;
    /**
     * Volume value of the bar. Always returns 0.
     * @type {number}
     * @memberof SingleHistoricalBarBidAsk
     */
    v?: number;
}

/**
 * Check if a given object implements the SingleHistoricalBarBidAsk interface.
 */
export function instanceOfSingleHistoricalBarBidAsk(value: object): value is SingleHistoricalBarBidAsk {
    return true;
}

export function SingleHistoricalBarBidAskFromJSON(json: any): SingleHistoricalBarBidAsk {
    return SingleHistoricalBarBidAskFromJSONTyped(json, false);
}

export function SingleHistoricalBarBidAskFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleHistoricalBarBidAsk {
    if (json == null) {
        return json;
    }
    return {
        
        'c': json['c'] == null ? undefined : json['c'],
        'h': json['h'] == null ? undefined : json['h'],
        'l': json['l'] == null ? undefined : json['l'],
        'o': json['o'] == null ? undefined : json['o'],
        't': json['t'] == null ? undefined : json['t'],
        'v': json['v'] == null ? undefined : json['v'],
    };
}

export function SingleHistoricalBarBidAskToJSON(json: any): SingleHistoricalBarBidAsk {
    return SingleHistoricalBarBidAskToJSONTyped(json, false);
}

export function SingleHistoricalBarBidAskToJSONTyped(value?: SingleHistoricalBarBidAsk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'c': value['c'],
        'h': value['h'],
        'l': value['l'],
        'o': value['o'],
        't': value['t'],
        'v': value['v'],
    };
}

