/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SingleWatchlistEntry } from './SingleWatchlistEntry';
import {
    SingleWatchlistEntryFromJSON,
    SingleWatchlistEntryFromJSONTyped,
    SingleWatchlistEntryToJSON,
    SingleWatchlistEntryToJSONTyped,
} from './SingleWatchlistEntry';

/**
 * Object detailing a single watchlist.
 * @export
 * @interface SingleWatchlist
 */
export interface SingleWatchlist {
    /**
     * Internal use. Unique hash of the watchlist.
     * @type {string}
     * @memberof SingleWatchlist
     */
    hash?: string;
    /**
     * Identifier of the watchlist.
     * @type {string}
     * @memberof SingleWatchlist
     */
    id?: string;
    /**
     * Array of instruments contained in the watchlist.
     * @type {Array<SingleWatchlistEntry>}
     * @memberof SingleWatchlist
     */
    instruments?: Array<SingleWatchlistEntry>;
    /**
     * Human-readable display name of the watchlist.
     * @type {string}
     * @memberof SingleWatchlist
     */
    name?: string;
    /**
     * Indicates whether the watchlist can be edited.
     * @type {boolean}
     * @memberof SingleWatchlist
     */
    readOnly?: boolean;
}

/**
 * Check if a given object implements the SingleWatchlist interface.
 */
export function instanceOfSingleWatchlist(value: object): value is SingleWatchlist {
    return true;
}

export function SingleWatchlistFromJSON(json: any): SingleWatchlist {
    return SingleWatchlistFromJSONTyped(json, false);
}

export function SingleWatchlistFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleWatchlist {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'] == null ? undefined : json['hash'],
        'id': json['id'] == null ? undefined : json['id'],
        'instruments': json['instruments'] == null ? undefined : ((json['instruments'] as Array<any>).map(SingleWatchlistEntryFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
    };
}

export function SingleWatchlistToJSON(json: any): SingleWatchlist {
    return SingleWatchlistToJSONTyped(json, false);
}

export function SingleWatchlistToJSONTyped(value?: SingleWatchlist | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hash': value['hash'],
        'id': value['id'],
        'instruments': value['instruments'] == null ? undefined : ((value['instruments'] as Array<any>).map(SingleWatchlistEntryToJSON)),
        'name': value['name'],
        'readOnly': value['readOnly'],
    };
}

