/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object containing Midpoint data for a single OHLC bar.
 * @export
 * @interface SingleHistoricalBarMidpoint
 */
export interface SingleHistoricalBarMidpoint {
    /**
     * Closing value of the bar. Indicates the last midpoint price traded price during the bar.
     * @type {number}
     * @memberof SingleHistoricalBarMidpoint
     */
    c?: number;
    /**
     * High value of the bar. Indicates the highest midpoint price traded price during the bar.
     * @type {number}
     * @memberof SingleHistoricalBarMidpoint
     */
    h?: number;
    /**
     * Low value of the bar. Indicates the lowest midpoint price traded price during the bar.
     * @type {number}
     * @memberof SingleHistoricalBarMidpoint
     */
    l?: number;
    /**
     * Opening value of the bar. Indicates the starting midpoint price traded price during the bar.
     * @type {number}
     * @memberof SingleHistoricalBarMidpoint
     */
    o?: number;
    /**
     * Unix timestamp of the start (chronologically earlier) of the bar.
     * @type {number}
     * @memberof SingleHistoricalBarMidpoint
     */
    t?: number;
    /**
     * Volume value of the bar. Always returns 0.
     * @type {number}
     * @memberof SingleHistoricalBarMidpoint
     */
    v?: number;
}

/**
 * Check if a given object implements the SingleHistoricalBarMidpoint interface.
 */
export function instanceOfSingleHistoricalBarMidpoint(value: object): value is SingleHistoricalBarMidpoint {
    return true;
}

export function SingleHistoricalBarMidpointFromJSON(json: any): SingleHistoricalBarMidpoint {
    return SingleHistoricalBarMidpointFromJSONTyped(json, false);
}

export function SingleHistoricalBarMidpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleHistoricalBarMidpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'c': json['c'] == null ? undefined : json['c'],
        'h': json['h'] == null ? undefined : json['h'],
        'l': json['l'] == null ? undefined : json['l'],
        'o': json['o'] == null ? undefined : json['o'],
        't': json['t'] == null ? undefined : json['t'],
        'v': json['v'] == null ? undefined : json['v'],
    };
}

export function SingleHistoricalBarMidpointToJSON(json: any): SingleHistoricalBarMidpoint {
    return SingleHistoricalBarMidpointToJSONTyped(json, false);
}

export function SingleHistoricalBarMidpointToJSONTyped(value?: SingleHistoricalBarMidpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'c': value['c'],
        'h': value['h'],
        'l': value['l'],
        'o': value['o'],
        't': value['t'],
        'v': value['v'],
    };
}

