/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SOIQuestionnaire
 */
export interface SOIQuestionnaire {
    /**
     * 
     * @type {string}
     * @memberof SOIQuestionnaire
     */
    details?: string;
}

/**
 * Check if a given object implements the SOIQuestionnaire interface.
 */
export function instanceOfSOIQuestionnaire(value: object): value is SOIQuestionnaire {
    return true;
}

export function SOIQuestionnaireFromJSON(json: any): SOIQuestionnaire {
    return SOIQuestionnaireFromJSONTyped(json, false);
}

export function SOIQuestionnaireFromJSONTyped(json: any, ignoreDiscriminator: boolean): SOIQuestionnaire {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function SOIQuestionnaireToJSON(json: any): SOIQuestionnaire {
    return SOIQuestionnaireToJSONTyped(json, false);
}

export function SOIQuestionnaireToJSONTyped(value?: SOIQuestionnaire | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': value['details'],
    };
}

