/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SsoValidateResponseFeatures } from './SsoValidateResponseFeatures';
import {
    SsoValidateResponseFeaturesFromJSON,
    SsoValidateResponseFeaturesFromJSONTyped,
    SsoValidateResponseFeaturesToJSON,
    SsoValidateResponseFeaturesToJSONTyped,
} from './SsoValidateResponseFeatures';

/**
 * 
 * @export
 * @interface SsoValidateResponse
 */
export interface SsoValidateResponse {
    /**
     * Returns the time of authentication in epoch time.
     * @type {number}
     * @memberof SsoValidateResponse
     */
    AUTH_TIME?: number;
    /**
     * Returns the underlying username of the account.
     * @type {string}
     * @memberof SsoValidateResponse
     */
    CREDENTIAL?: string;
    /**
     * Returns the time until SSO session expiration in milliseconds.
     * @type {number}
     * @memberof SsoValidateResponse
     */
    EXPIRES?: number;
    /**
     * Internal use only. Does not reflect the IP address of the user.
     * @type {string}
     * @memberof SsoValidateResponse
     */
    IP?: string;
    /**
     * Returns if the account is a trial account or a funded account.
     * @type {boolean}
     * @memberof SsoValidateResponse
     */
    IS_FREE_TRIAL?: boolean;
    /**
     * Returns whether the account is a master account (true) or subaccount (false).
     * @type {boolean}
     * @memberof SsoValidateResponse
     */
    IS_MASTER?: boolean;
    /**
     * Used for Client Portal (Internal use only)
     * @type {string}
     * @memberof SsoValidateResponse
     */
    LANDING_APP?: string;
    /**
     * Returns the paper username for the account.
     * @type {string}
     * @memberof SsoValidateResponse
     */
    PAPER_USER_NAME?: string;
    /**
     * Returns if the customer requires two factor authentication.
     * @type {boolean}
     * @memberof SsoValidateResponse
     */
    QUALIFIED_FOR_MOBILE_AUTH?: boolean;
    /**
     * Confirms if validation was successful. True if session was validated; false if not.
     * @type {boolean}
     * @memberof SsoValidateResponse
     */
    RESULT?: boolean;
    /**
     * (Internal use only)
     * @type {boolean}
     * @memberof SsoValidateResponse
     */
    SF_ENABLED?: boolean;
    /**
     * Internal user identifier.
     * @type {number}
     * @memberof SsoValidateResponse
     */
    USER_ID?: number;
    /**
     * current username logged in for the session.
     * @type {string}
     * @memberof SsoValidateResponse
     */
    USER_NAME?: string;
    /**
     * 
     * @type {SsoValidateResponseFeatures}
     * @memberof SsoValidateResponse
     */
    features?: SsoValidateResponseFeatures;
    /**
     * Returns the last time the user was accessed in epoch time.
     * @type {number}
     * @memberof SsoValidateResponse
     */
    lastAccessed?: number;
    /**
     * Returns the login type. 1 for Live, 2 for Paper
     * @type {number}
     * @memberof SsoValidateResponse
     */
    loginType?: number;
    /**
     * Returns the region connected to internally.
     * @type {string}
     * @memberof SsoValidateResponse
     */
    region?: string;
}

/**
 * Check if a given object implements the SsoValidateResponse interface.
 */
export function instanceOfSsoValidateResponse(value: object): value is SsoValidateResponse {
    return true;
}

export function SsoValidateResponseFromJSON(json: any): SsoValidateResponse {
    return SsoValidateResponseFromJSONTyped(json, false);
}

export function SsoValidateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SsoValidateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'AUTH_TIME': json['AUTH_TIME'] == null ? undefined : json['AUTH_TIME'],
        'CREDENTIAL': json['CREDENTIAL'] == null ? undefined : json['CREDENTIAL'],
        'EXPIRES': json['EXPIRES'] == null ? undefined : json['EXPIRES'],
        'IP': json['IP'] == null ? undefined : json['IP'],
        'IS_FREE_TRIAL': json['IS_FREE_TRIAL'] == null ? undefined : json['IS_FREE_TRIAL'],
        'IS_MASTER': json['IS_MASTER'] == null ? undefined : json['IS_MASTER'],
        'LANDING_APP': json['LANDING_APP'] == null ? undefined : json['LANDING_APP'],
        'PAPER_USER_NAME': json['PAPER_USER_NAME'] == null ? undefined : json['PAPER_USER_NAME'],
        'QUALIFIED_FOR_MOBILE_AUTH': json['QUALIFIED_FOR_MOBILE_AUTH'] == null ? undefined : json['QUALIFIED_FOR_MOBILE_AUTH'],
        'RESULT': json['RESULT'] == null ? undefined : json['RESULT'],
        'SF_ENABLED': json['SF_ENABLED'] == null ? undefined : json['SF_ENABLED'],
        'USER_ID': json['USER_ID'] == null ? undefined : json['USER_ID'],
        'USER_NAME': json['USER_NAME'] == null ? undefined : json['USER_NAME'],
        'features': json['features'] == null ? undefined : SsoValidateResponseFeaturesFromJSON(json['features']),
        'lastAccessed': json['lastAccessed'] == null ? undefined : json['lastAccessed'],
        'loginType': json['loginType'] == null ? undefined : json['loginType'],
        'region': json['region'] == null ? undefined : json['region'],
    };
}

export function SsoValidateResponseToJSON(json: any): SsoValidateResponse {
    return SsoValidateResponseToJSONTyped(json, false);
}

export function SsoValidateResponseToJSONTyped(value?: SsoValidateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AUTH_TIME': value['AUTH_TIME'],
        'CREDENTIAL': value['CREDENTIAL'],
        'EXPIRES': value['EXPIRES'],
        'IP': value['IP'],
        'IS_FREE_TRIAL': value['IS_FREE_TRIAL'],
        'IS_MASTER': value['IS_MASTER'],
        'LANDING_APP': value['LANDING_APP'],
        'PAPER_USER_NAME': value['PAPER_USER_NAME'],
        'QUALIFIED_FOR_MOBILE_AUTH': value['QUALIFIED_FOR_MOBILE_AUTH'],
        'RESULT': value['RESULT'],
        'SF_ENABLED': value['SF_ENABLED'],
        'USER_ID': value['USER_ID'],
        'USER_NAME': value['USER_NAME'],
        'features': SsoValidateResponseFeaturesToJSON(value['features']),
        'lastAccessed': value['lastAccessed'],
        'loginType': value['loginType'],
        'region': value['region'],
    };
}

