/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StmtRequest
 */
export interface StmtRequest {
    /**
     * account id
     * @type {string}
     * @memberof StmtRequest
     */
    accountId: string;
    /**
     * array of account id's
     * @type {Array<string>}
     * @memberof StmtRequest
     */
    accountIds?: Array<string>;
    /**
     * crypto consolidate flag, If request contains any accounts with crypto segment, will turn request into Crypto Consolidated
     * @type {boolean}
     * @memberof StmtRequest
     */
    cryptoConsolIfAvailable?: boolean;
    /**
     * to date
     * @type {string}
     * @memberof StmtRequest
     */
    endDate: string;
    /**
     * to gzip the whole response pass true
     * @type {boolean}
     * @memberof StmtRequest
     */
    gzip?: boolean;
    /**
     * two character ISO language code
     * @type {string}
     * @memberof StmtRequest
     */
    language?: string;
    /**
     * output format
     * @type {string}
     * @memberof StmtRequest
     */
    mimeType?: string;
    /**
     * possible values are consolidate, concatenate, or customConsolidate
     * @type {string}
     * @memberof StmtRequest
     */
    multiAccountFormat?: string;
    /**
     * from date
     * @type {string}
     * @memberof StmtRequest
     */
    startDate: string;
}

/**
 * Check if a given object implements the StmtRequest interface.
 */
export function instanceOfStmtRequest(value: object): value is StmtRequest {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    return true;
}

export function StmtRequestFromJSON(json: any): StmtRequest {
    return StmtRequestFromJSONTyped(json, false);
}

export function StmtRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StmtRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'accountIds': json['accountIds'] == null ? undefined : json['accountIds'],
        'cryptoConsolIfAvailable': json['cryptoConsolIfAvailable'] == null ? undefined : json['cryptoConsolIfAvailable'],
        'endDate': json['endDate'],
        'gzip': json['gzip'] == null ? undefined : json['gzip'],
        'language': json['language'] == null ? undefined : json['language'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'multiAccountFormat': json['multiAccountFormat'] == null ? undefined : json['multiAccountFormat'],
        'startDate': json['startDate'],
    };
}

export function StmtRequestToJSON(json: any): StmtRequest {
    return StmtRequestToJSONTyped(json, false);
}

export function StmtRequestToJSONTyped(value?: StmtRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'accountIds': value['accountIds'],
        'cryptoConsolIfAvailable': value['cryptoConsolIfAvailable'],
        'endDate': value['endDate'],
        'gzip': value['gzip'],
        'language': value['language'],
        'mimeType': value['mimeType'],
        'multiAccountFormat': value['multiAccountFormat'],
        'startDate': value['startDate'],
    };
}

