/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StocksValueInnerContractsInner } from './StocksValueInnerContractsInner';
import {
    StocksValueInnerContractsInnerFromJSON,
    StocksValueInnerContractsInnerFromJSONTyped,
    StocksValueInnerContractsInnerToJSON,
    StocksValueInnerContractsInnerToJSONTyped,
} from './StocksValueInnerContractsInner';

/**
 * Contains a series of objects for each symbol that matches the requested
 * @export
 * @interface StocksValueInner
 */
export interface StocksValueInner {
    /**
     * Asset class for the given company.
     * @type {string}
     * @memberof StocksValueInner
     */
    assetClass?: string;
    /**
     * Chinese name for the given company as unicode.
     * @type {string}
     * @memberof StocksValueInner
     */
    chineseName?: string;
    /**
     * A series of arrays pertaining to the same company listed by "name". Typically differentiated based on currency of the primary exchange.
     * 
     * @type {Array<StocksValueInnerContractsInner>}
     * @memberof StocksValueInner
     */
    contracts?: Array<StocksValueInnerContractsInner>;
    /**
     * Full company name for the given contract.
     * @type {string}
     * @memberof StocksValueInner
     */
    name?: string;
}

/**
 * Check if a given object implements the StocksValueInner interface.
 */
export function instanceOfStocksValueInner(value: object): value is StocksValueInner {
    return true;
}

export function StocksValueInnerFromJSON(json: any): StocksValueInner {
    return StocksValueInnerFromJSONTyped(json, false);
}

export function StocksValueInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StocksValueInner {
    if (json == null) {
        return json;
    }
    return {
        
        'assetClass': json['assetClass'] == null ? undefined : json['assetClass'],
        'chineseName': json['chineseName'] == null ? undefined : json['chineseName'],
        'contracts': json['contracts'] == null ? undefined : ((json['contracts'] as Array<any>).map(StocksValueInnerContractsInnerFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function StocksValueInnerToJSON(json: any): StocksValueInner {
    return StocksValueInnerToJSONTyped(json, false);
}

export function StocksValueInnerToJSONTyped(value?: StocksValueInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assetClass': value['assetClass'],
        'chineseName': value['chineseName'],
        'contracts': value['contracts'] == null ? undefined : ((value['contracts'] as Array<any>).map(StocksValueInnerContractsInnerToJSON)),
        'name': value['name'],
    };
}

