/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata container describing the subaccounts.
 * @export
 * @interface Subaccounts2ResponseMetadata
 */
export interface Subaccounts2ResponseMetadata {
    /**
     * The active page number.
     * @type {number}
     * @memberof Subaccounts2ResponseMetadata
     */
    pageNum?: number;
    /**
     * Items contained in the returning page.
     * @type {number}
     * @memberof Subaccounts2ResponseMetadata
     */
    pageSize?: number;
    /**
     * The total number of accounts returned for the page.
     * @type {number}
     * @memberof Subaccounts2ResponseMetadata
     */
    total?: number;
}

/**
 * Check if a given object implements the Subaccounts2ResponseMetadata interface.
 */
export function instanceOfSubaccounts2ResponseMetadata(value: object): value is Subaccounts2ResponseMetadata {
    return true;
}

export function Subaccounts2ResponseMetadataFromJSON(json: any): Subaccounts2ResponseMetadata {
    return Subaccounts2ResponseMetadataFromJSONTyped(json, false);
}

export function Subaccounts2ResponseMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subaccounts2ResponseMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNum': json['pageNum'] == null ? undefined : json['pageNum'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function Subaccounts2ResponseMetadataToJSON(json: any): Subaccounts2ResponseMetadata {
    return Subaccounts2ResponseMetadataToJSONTyped(json, false);
}

export function Subaccounts2ResponseMetadataToJSONTyped(value?: Subaccounts2ResponseMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageNum': value['pageNum'],
        'pageSize': value['pageSize'],
        'total': value['total'],
    };
}

