/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubAccountsAccountsInnerDataInner } from './SubAccountsAccountsInnerDataInner';
import {
    SubAccountsAccountsInnerDataInnerFromJSON,
    SubAccountsAccountsInnerDataInnerFromJSONTyped,
    SubAccountsAccountsInnerDataInnerToJSON,
    SubAccountsAccountsInnerDataInnerToJSONTyped,
} from './SubAccountsAccountsInnerDataInner';

/**
 * 
 * @export
 * @interface SubAccountsAccountsInner
 */
export interface SubAccountsAccountsInner {
    /**
     * Contains Net liquidation and available equity of the given account Id.
     * @type {Array<SubAccountsAccountsInnerDataInner>}
     * @memberof SubAccountsAccountsInner
     */
    data?: Array<SubAccountsAccountsInnerDataInner>;
    /**
     * Returns the account ID affiliated with the balance data.
     * @type {string}
     * @memberof SubAccountsAccountsInner
     */
    name?: string;
}

/**
 * Check if a given object implements the SubAccountsAccountsInner interface.
 */
export function instanceOfSubAccountsAccountsInner(value: object): value is SubAccountsAccountsInner {
    return true;
}

export function SubAccountsAccountsInnerFromJSON(json: any): SubAccountsAccountsInner {
    return SubAccountsAccountsInnerFromJSONTyped(json, false);
}

export function SubAccountsAccountsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubAccountsAccountsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SubAccountsAccountsInnerDataInnerFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SubAccountsAccountsInnerToJSON(json: any): SubAccountsAccountsInner {
    return SubAccountsAccountsInnerToJSONTyped(json, false);
}

export function SubAccountsAccountsInnerToJSONTyped(value?: SubAccountsAccountsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SubAccountsAccountsInnerDataInnerToJSON)),
        'name': value['name'],
    };
}

