/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuppressOrderRepliesRequest
 */
export interface SuppressOrderRepliesRequest {
    /**
     * Array of order reply messageId identifier strings to be suppressed.
     * @type {Array<SuppressOrderRepliesRequestMessageIdsEnum>}
     * @memberof SuppressOrderRepliesRequest
     */
    messageIds?: Array<SuppressOrderRepliesRequestMessageIdsEnum>;
}


/**
 * @export
 */
export const SuppressOrderRepliesRequestMessageIdsEnum = {
    O163: 'o163',
    O354: 'o354',
    O382: 'o382',
    O383: 'o383',
    O403: 'o403',
    O451: 'o451',
    O2136: 'o2136',
    O2137: 'o2137',
    O2165: 'o2165',
    O10082: 'o10082',
    O10138: 'o10138',
    O10151: 'o10151',
    O10152: 'o10152',
    O10153: 'o10153',
    O10164: 'o10164',
    O10223: 'o10223',
    O10288: 'o10288',
    O10331: 'o10331',
    O10332: 'o10332',
    O10333: 'o10333',
    O10334: 'o10334',
    O10335: 'o10335',
    O10336: 'o10336',
    P6: 'p6',
    P12: 'p12'
} as const;
export type SuppressOrderRepliesRequestMessageIdsEnum = typeof SuppressOrderRepliesRequestMessageIdsEnum[keyof typeof SuppressOrderRepliesRequestMessageIdsEnum];


/**
 * Check if a given object implements the SuppressOrderRepliesRequest interface.
 */
export function instanceOfSuppressOrderRepliesRequest(value: object): value is SuppressOrderRepliesRequest {
    return true;
}

export function SuppressOrderRepliesRequestFromJSON(json: any): SuppressOrderRepliesRequest {
    return SuppressOrderRepliesRequestFromJSONTyped(json, false);
}

export function SuppressOrderRepliesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuppressOrderRepliesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'messageIds': json['messageIds'] == null ? undefined : json['messageIds'],
    };
}

export function SuppressOrderRepliesRequestToJSON(json: any): SuppressOrderRepliesRequest {
    return SuppressOrderRepliesRequestToJSONTyped(json, false);
}

export function SuppressOrderRepliesRequestToJSONTyped(value?: SuppressOrderRepliesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageIds': value['messageIds'],
    };
}

