/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxFormType
 */
export interface TaxFormType {
    /**
     * available tax form formats
     * @type {Array<string>}
     * @memberof TaxFormType
     */
    formats?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof TaxFormType
     */
    isForm?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TaxFormType
     */
    taxFormName?: string;
}

/**
 * Check if a given object implements the TaxFormType interface.
 */
export function instanceOfTaxFormType(value: object): value is TaxFormType {
    return true;
}

export function TaxFormTypeFromJSON(json: any): TaxFormType {
    return TaxFormTypeFromJSONTyped(json, false);
}

export function TaxFormTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxFormType {
    if (json == null) {
        return json;
    }
    return {
        
        'formats': json['formats'] == null ? undefined : json['formats'],
        'isForm': json['isForm'] == null ? undefined : json['isForm'],
        'taxFormName': json['taxFormName'] == null ? undefined : json['taxFormName'],
    };
}

export function TaxFormTypeToJSON(json: any): TaxFormType {
    return TaxFormTypeToJSONTyped(json, false);
}

export function TaxFormTypeToJSONTyped(value?: TaxFormType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'formats': value['formats'],
        'isForm': value['isForm'],
        'taxFormName': value['taxFormName'],
    };
}

