/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionsResponseRpnl } from './TransactionsResponseRpnl';
import {
    TransactionsResponseRpnlFromJSON,
    TransactionsResponseRpnlFromJSONTyped,
    TransactionsResponseRpnlToJSON,
    TransactionsResponseRpnlToJSONTyped,
} from './TransactionsResponseRpnl';
import type { TransactionsResponseTransactionsInner } from './TransactionsResponseTransactionsInner';
import {
    TransactionsResponseTransactionsInnerFromJSON,
    TransactionsResponseTransactionsInnerFromJSONTyped,
    TransactionsResponseTransactionsInnerToJSON,
    TransactionsResponseTransactionsInnerToJSONTyped,
} from './TransactionsResponseTransactionsInner';

/**
 * 
 * @export
 * @interface TransactionsResponse
 */
export interface TransactionsResponse {
    /**
     * Returns the currency the account is traded in.
     * @type {string}
     * @memberof TransactionsResponse
     */
    currency?: string;
    /**
     * Returns the epoch time for the start of requests.
     * @type {number}
     * @memberof TransactionsResponse
     */
    from?: number;
    /**
     * Returns the request identifier, getTransactions.
     * @type {string}
     * @memberof TransactionsResponse
     */
    id?: string;
    /**
     * Returns if the trades are up to date or not.
     * @type {boolean}
     * @memberof TransactionsResponse
     */
    includesRealTime?: boolean;
    /**
     * Client portal use only
     * @type {number}
     * @memberof TransactionsResponse
     */
    nd?: number;
    /**
     * Client portal use only
     * @type {number}
     * @memberof TransactionsResponse
     */
    rc?: number;
    /**
     * 
     * @type {TransactionsResponseRpnl}
     * @memberof TransactionsResponse
     */
    rpnl?: TransactionsResponseRpnl;
    /**
     * Returns the epoch time for the end of requests.
     * @type {number}
     * @memberof TransactionsResponse
     */
    to?: number;
    /**
     * Lists all supported transaction values.
     * @type {Array<TransactionsResponseTransactionsInner>}
     * @memberof TransactionsResponse
     */
    transactions?: Array<TransactionsResponseTransactionsInner>;
}

/**
 * Check if a given object implements the TransactionsResponse interface.
 */
export function instanceOfTransactionsResponse(value: object): value is TransactionsResponse {
    return true;
}

export function TransactionsResponseFromJSON(json: any): TransactionsResponse {
    return TransactionsResponseFromJSONTyped(json, false);
}

export function TransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'from': json['from'] == null ? undefined : json['from'],
        'id': json['id'] == null ? undefined : json['id'],
        'includesRealTime': json['includesRealTime'] == null ? undefined : json['includesRealTime'],
        'nd': json['nd'] == null ? undefined : json['nd'],
        'rc': json['rc'] == null ? undefined : json['rc'],
        'rpnl': json['rpnl'] == null ? undefined : TransactionsResponseRpnlFromJSON(json['rpnl']),
        'to': json['to'] == null ? undefined : json['to'],
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(TransactionsResponseTransactionsInnerFromJSON)),
    };
}

export function TransactionsResponseToJSON(json: any): TransactionsResponse {
    return TransactionsResponseToJSONTyped(json, false);
}

export function TransactionsResponseToJSONTyped(value?: TransactionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'from': value['from'],
        'id': value['id'],
        'includesRealTime': value['includesRealTime'],
        'nd': value['nd'],
        'rc': value['rc'],
        'rpnl': TransactionsResponseRpnlToJSON(value['rpnl']),
        'to': value['to'],
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(TransactionsResponseTransactionsInnerToJSON)),
    };
}

