/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrusteesType } from './TrusteesType';
import {
    TrusteesTypeFromJSON,
    TrusteesTypeFromJSONTyped,
    TrusteesTypeToJSON,
    TrusteesTypeToJSONTyped,
} from './TrusteesType';
import type { FormW8IMY } from './FormW8IMY';
import {
    FormW8IMYFromJSON,
    FormW8IMYFromJSONTyped,
    FormW8IMYToJSON,
    FormW8IMYToJSONTyped,
} from './FormW8IMY';
import type { RegulatoryInformation } from './RegulatoryInformation';
import {
    RegulatoryInformationFromJSON,
    RegulatoryInformationFromJSONTyped,
    RegulatoryInformationToJSON,
    RegulatoryInformationToJSONTyped,
} from './RegulatoryInformation';
import type { TaxResidency } from './TaxResidency';
import {
    TaxResidencyFromJSON,
    TaxResidencyFromJSONTyped,
    TaxResidencyToJSON,
    TaxResidencyToJSONTyped,
} from './TaxResidency';
import type { FinancialInformation } from './FinancialInformation';
import {
    FinancialInformationFromJSON,
    FinancialInformationFromJSONTyped,
    FinancialInformationToJSON,
    FinancialInformationToJSONTyped,
} from './FinancialInformation';
import type { FormW8BENE } from './FormW8BENE';
import {
    FormW8BENEFromJSON,
    FormW8BENEFromJSONTyped,
    FormW8BENEToJSON,
    FormW8BENEToJSONTyped,
} from './FormW8BENE';
import type { AssociationTypeEntities } from './AssociationTypeEntities';
import {
    AssociationTypeEntitiesFromJSON,
    AssociationTypeEntitiesFromJSONTyped,
    AssociationTypeEntitiesToJSON,
    AssociationTypeEntitiesToJSONTyped,
} from './AssociationTypeEntities';
import type { RegulatedMembership } from './RegulatedMembership';
import {
    RegulatedMembershipFromJSON,
    RegulatedMembershipFromJSONTyped,
    RegulatedMembershipToJSON,
    RegulatedMembershipToJSONTyped,
} from './RegulatedMembership';
import type { WithholdingStatementType } from './WithholdingStatementType';
import {
    WithholdingStatementTypeFromJSON,
    WithholdingStatementTypeFromJSONTyped,
    WithholdingStatementTypeToJSON,
    WithholdingStatementTypeToJSONTyped,
} from './WithholdingStatementType';
import type { AccreditedInvestorInformation } from './AccreditedInvestorInformation';
import {
    AccreditedInvestorInformationFromJSON,
    AccreditedInvestorInformationFromJSONTyped,
    AccreditedInvestorInformationToJSON,
    AccreditedInvestorInformationToJSONTyped,
} from './AccreditedInvestorInformation';
import type { TrustIdentification } from './TrustIdentification';
import {
    TrustIdentificationFromJSON,
    TrustIdentificationFromJSONTyped,
    TrustIdentificationToJSON,
    TrustIdentificationToJSONTyped,
} from './TrustIdentification';

/**
 * 
 * @export
 * @interface TrustApplicant
 */
export interface TrustApplicant {
    /**
     * 
     * @type {AccreditedInvestorInformation}
     * @memberof TrustApplicant
     */
    accreditedInvestorInformation?: AccreditedInvestorInformation;
    /**
     * 
     * @type {AssociationTypeEntities}
     * @memberof TrustApplicant
     */
    beneficiaries?: AssociationTypeEntities;
    /**
     * 
     * @type {Array<FinancialInformation>}
     * @memberof TrustApplicant
     */
    financialInformation?: Array<FinancialInformation>;
    /**
     * 
     * @type {AssociationTypeEntities}
     * @memberof TrustApplicant
     */
    grantors?: AssociationTypeEntities;
    /**
     * 
     * @type {Array<TrustIdentification>}
     * @memberof TrustApplicant
     */
    identification?: Array<TrustIdentification>;
    /**
     * 
     * @type {Array<RegulatedMembership>}
     * @memberof TrustApplicant
     */
    regulatedMemberships?: Array<RegulatedMembership>;
    /**
     * 
     * @type {Array<RegulatoryInformation>}
     * @memberof TrustApplicant
     */
    regulatoryInformation?: Array<RegulatoryInformation>;
    /**
     * 
     * @type {Array<TaxResidency>}
     * @memberof TrustApplicant
     */
    taxResidencies?: Array<TaxResidency>;
    /**
     * 
     * @type {boolean}
     * @memberof TrustApplicant
     */
    thirdPartyManagement?: boolean;
    /**
     * 
     * @type {TrustApplicantTrustTypeEnum}
     * @memberof TrustApplicant
     */
    trustType?: TrustApplicantTrustTypeEnum;
    /**
     * 
     * @type {TrusteesType}
     * @memberof TrustApplicant
     */
    trustees?: TrusteesType;
    /**
     * 
     * @type {FormW8BENE}
     * @memberof TrustApplicant
     */
    w8BenE?: FormW8BENE;
    /**
     * 
     * @type {FormW8IMY}
     * @memberof TrustApplicant
     */
    w8IMY?: FormW8IMY;
    /**
     * 
     * @type {WithholdingStatementType}
     * @memberof TrustApplicant
     */
    withholdingStatement?: WithholdingStatementType;
}


/**
 * @export
 */
export const TrustApplicantTrustTypeEnum = {
    ComplexTrust: 'COMPLEX_TRUST',
    SingleTrust: 'SINGLE_TRUST',
    GrantorTrust: 'GRANTOR_TRUST',
    UsTaxableTrust: 'US_TAXABLE_TRUST'
} as const;
export type TrustApplicantTrustTypeEnum = typeof TrustApplicantTrustTypeEnum[keyof typeof TrustApplicantTrustTypeEnum];


/**
 * Check if a given object implements the TrustApplicant interface.
 */
export function instanceOfTrustApplicant(value: object): value is TrustApplicant {
    return true;
}

export function TrustApplicantFromJSON(json: any): TrustApplicant {
    return TrustApplicantFromJSONTyped(json, false);
}

export function TrustApplicantFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrustApplicant {
    if (json == null) {
        return json;
    }
    return {
        
        'accreditedInvestorInformation': json['accreditedInvestorInformation'] == null ? undefined : AccreditedInvestorInformationFromJSON(json['accreditedInvestorInformation']),
        'beneficiaries': json['beneficiaries'] == null ? undefined : AssociationTypeEntitiesFromJSON(json['beneficiaries']),
        'financialInformation': json['financialInformation'] == null ? undefined : ((json['financialInformation'] as Array<any>).map(FinancialInformationFromJSON)),
        'grantors': json['grantors'] == null ? undefined : AssociationTypeEntitiesFromJSON(json['grantors']),
        'identification': json['identification'] == null ? undefined : ((json['identification'] as Array<any>).map(TrustIdentificationFromJSON)),
        'regulatedMemberships': json['regulatedMemberships'] == null ? undefined : ((json['regulatedMemberships'] as Array<any>).map(RegulatedMembershipFromJSON)),
        'regulatoryInformation': json['regulatoryInformation'] == null ? undefined : ((json['regulatoryInformation'] as Array<any>).map(RegulatoryInformationFromJSON)),
        'taxResidencies': json['taxResidencies'] == null ? undefined : ((json['taxResidencies'] as Array<any>).map(TaxResidencyFromJSON)),
        'thirdPartyManagement': json['thirdPartyManagement'] == null ? undefined : json['thirdPartyManagement'],
        'trustType': json['trustType'] == null ? undefined : json['trustType'],
        'trustees': json['trustees'] == null ? undefined : TrusteesTypeFromJSON(json['trustees']),
        'w8BenE': json['w8BenE'] == null ? undefined : FormW8BENEFromJSON(json['w8BenE']),
        'w8IMY': json['w8IMY'] == null ? undefined : FormW8IMYFromJSON(json['w8IMY']),
        'withholdingStatement': json['withholdingStatement'] == null ? undefined : WithholdingStatementTypeFromJSON(json['withholdingStatement']),
    };
}

export function TrustApplicantToJSON(json: any): TrustApplicant {
    return TrustApplicantToJSONTyped(json, false);
}

export function TrustApplicantToJSONTyped(value?: TrustApplicant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accreditedInvestorInformation': AccreditedInvestorInformationToJSON(value['accreditedInvestorInformation']),
        'beneficiaries': AssociationTypeEntitiesToJSON(value['beneficiaries']),
        'financialInformation': value['financialInformation'] == null ? undefined : ((value['financialInformation'] as Array<any>).map(FinancialInformationToJSON)),
        'grantors': AssociationTypeEntitiesToJSON(value['grantors']),
        'identification': value['identification'] == null ? undefined : ((value['identification'] as Array<any>).map(TrustIdentificationToJSON)),
        'regulatedMemberships': value['regulatedMemberships'] == null ? undefined : ((value['regulatedMemberships'] as Array<any>).map(RegulatedMembershipToJSON)),
        'regulatoryInformation': value['regulatoryInformation'] == null ? undefined : ((value['regulatoryInformation'] as Array<any>).map(RegulatoryInformationToJSON)),
        'taxResidencies': value['taxResidencies'] == null ? undefined : ((value['taxResidencies'] as Array<any>).map(TaxResidencyToJSON)),
        'thirdPartyManagement': value['thirdPartyManagement'],
        'trustType': value['trustType'],
        'trustees': TrusteesTypeToJSON(value['trustees']),
        'w8BenE': FormW8BENEToJSON(value['w8BenE']),
        'w8IMY': FormW8IMYToJSON(value['w8IMY']),
        'withholdingStatement': WithholdingStatementTypeToJSON(value['withholdingStatement']),
    };
}

