/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAccountsResponseAcctPropsU1234567 } from './UserAccountsResponseAcctPropsU1234567';
import {
    UserAccountsResponseAcctPropsU1234567FromJSON,
    UserAccountsResponseAcctPropsU1234567FromJSONTyped,
    UserAccountsResponseAcctPropsU1234567ToJSON,
    UserAccountsResponseAcctPropsU1234567ToJSONTyped,
} from './UserAccountsResponseAcctPropsU1234567';

/**
 * Returns an json object for each accessible account's properties.
 * @export
 * @interface UserAccountsResponseAcctProps
 */
export interface UserAccountsResponseAcctProps {
    /**
     * 
     * @type {UserAccountsResponseAcctPropsU1234567}
     * @memberof UserAccountsResponseAcctProps
     */
    U1234567?: UserAccountsResponseAcctPropsU1234567;
}

/**
 * Check if a given object implements the UserAccountsResponseAcctProps interface.
 */
export function instanceOfUserAccountsResponseAcctProps(value: object): value is UserAccountsResponseAcctProps {
    return true;
}

export function UserAccountsResponseAcctPropsFromJSON(json: any): UserAccountsResponseAcctProps {
    return UserAccountsResponseAcctPropsFromJSONTyped(json, false);
}

export function UserAccountsResponseAcctPropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccountsResponseAcctProps {
    if (json == null) {
        return json;
    }
    return {
        
        'U1234567': json['U1234567'] == null ? undefined : UserAccountsResponseAcctPropsU1234567FromJSON(json['U1234567']),
    };
}

export function UserAccountsResponseAcctPropsToJSON(json: any): UserAccountsResponseAcctProps {
    return UserAccountsResponseAcctPropsToJSONTyped(json, false);
}

export function UserAccountsResponseAcctPropsToJSONTyped(value?: UserAccountsResponseAcctProps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'U1234567': UserAccountsResponseAcctPropsU1234567ToJSON(value['U1234567']),
    };
}

