/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WithdrawFundsInstructionIraWithdrawalDetail
 */
export interface WithdrawFundsInstructionIraWithdrawalDetail {
    /**
     * 
     * @type {number}
     * @memberof WithdrawFundsInstructionIraWithdrawalDetail
     */
    fedIncomeTaxPercentage: number;
    /**
     * 
     * @type {WithdrawFundsInstructionIraWithdrawalDetailIraWithholdTypeEnum}
     * @memberof WithdrawFundsInstructionIraWithdrawalDetail
     */
    iraWithholdType: WithdrawFundsInstructionIraWithdrawalDetailIraWithholdTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WithdrawFundsInstructionIraWithdrawalDetail
     */
    stateCd: string;
    /**
     * 
     * @type {number}
     * @memberof WithdrawFundsInstructionIraWithdrawalDetail
     */
    stateIncomeTaxPercentage: number;
}


/**
 * @export
 */
export const WithdrawFundsInstructionIraWithdrawalDetailIraWithholdTypeEnum = {
    DirectRollover: 'DIRECT_ROLLOVER',
    RothDistribution: 'ROTH_DISTRIBUTION',
    Normal: 'NORMAL',
    Early: 'EARLY',
    Death: 'DEATH',
    ExcessCy: 'EXCESS_CY',
    ExcessPy: 'EXCESS_PY',
    ExcessSc: 'EXCESS_SC'
} as const;
export type WithdrawFundsInstructionIraWithdrawalDetailIraWithholdTypeEnum = typeof WithdrawFundsInstructionIraWithdrawalDetailIraWithholdTypeEnum[keyof typeof WithdrawFundsInstructionIraWithdrawalDetailIraWithholdTypeEnum];


/**
 * Check if a given object implements the WithdrawFundsInstructionIraWithdrawalDetail interface.
 */
export function instanceOfWithdrawFundsInstructionIraWithdrawalDetail(value: object): value is WithdrawFundsInstructionIraWithdrawalDetail {
    if (!('fedIncomeTaxPercentage' in value) || value['fedIncomeTaxPercentage'] === undefined) return false;
    if (!('iraWithholdType' in value) || value['iraWithholdType'] === undefined) return false;
    if (!('stateCd' in value) || value['stateCd'] === undefined) return false;
    if (!('stateIncomeTaxPercentage' in value) || value['stateIncomeTaxPercentage'] === undefined) return false;
    return true;
}

export function WithdrawFundsInstructionIraWithdrawalDetailFromJSON(json: any): WithdrawFundsInstructionIraWithdrawalDetail {
    return WithdrawFundsInstructionIraWithdrawalDetailFromJSONTyped(json, false);
}

export function WithdrawFundsInstructionIraWithdrawalDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawFundsInstructionIraWithdrawalDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'fedIncomeTaxPercentage': json['fedIncomeTaxPercentage'],
        'iraWithholdType': json['iraWithholdType'],
        'stateCd': json['stateCd'],
        'stateIncomeTaxPercentage': json['stateIncomeTaxPercentage'],
    };
}

export function WithdrawFundsInstructionIraWithdrawalDetailToJSON(json: any): WithdrawFundsInstructionIraWithdrawalDetail {
    return WithdrawFundsInstructionIraWithdrawalDetailToJSONTyped(json, false);
}

export function WithdrawFundsInstructionIraWithdrawalDetailToJSONTyped(value?: WithdrawFundsInstructionIraWithdrawalDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fedIncomeTaxPercentage': value['fedIncomeTaxPercentage'],
        'iraWithholdType': value['iraWithholdType'],
        'stateCd': value['stateCd'],
        'stateIncomeTaxPercentage': value['stateIncomeTaxPercentage'],
    };
}

