/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountDetailsResponse,
  AccountStatusBulkResponse,
  AccountStatusRequest,
  AccountStatusResponse,
  Au10TixDetailResponse,
  GetGwApiV1Accounts200Response,
  GetGwApiV1AccountsAccountidTasks200Response,
  LoginMessageRequest,
  LoginMessageResponse,
  StatusResponse,
  TaskActionResponse,
} from '../models/index';
import {
    AccountDetailsResponseFromJSON,
    AccountDetailsResponseToJSON,
    AccountStatusBulkResponseFromJSON,
    AccountStatusBulkResponseToJSON,
    AccountStatusRequestFromJSON,
    AccountStatusRequestToJSON,
    AccountStatusResponseFromJSON,
    AccountStatusResponseToJSON,
    Au10TixDetailResponseFromJSON,
    Au10TixDetailResponseToJSON,
    GetGwApiV1Accounts200ResponseFromJSON,
    GetGwApiV1Accounts200ResponseToJSON,
    GetGwApiV1AccountsAccountidTasks200ResponseFromJSON,
    GetGwApiV1AccountsAccountidTasks200ResponseToJSON,
    LoginMessageRequestFromJSON,
    LoginMessageRequestToJSON,
    LoginMessageResponseFromJSON,
    LoginMessageResponseToJSON,
    StatusResponseFromJSON,
    StatusResponseToJSON,
    TaskActionResponseFromJSON,
    TaskActionResponseToJSON,
} from '../models/index';

export interface GetGwApiV1AccountsRequest {
    accountId?: string;
    externalId?: string;
}

export interface GetGwApiV1AccountsAccountidDetailsRequest {
    accountId: string;
}

export interface GetGwApiV1AccountsAccountidKycRequest {
    accountId: string;
}

export interface GetGwApiV1AccountsAccountidLoginMessagesRequest {
    accountId: string;
    type?: string;
}

export interface GetGwApiV1AccountsAccountidStatusRequest {
    accountId: string;
}

export interface GetGwApiV1AccountsAccountidTasksRequest {
    accountId: string;
    type?: GetGwApiV1AccountsAccountidTasksTypeEnum;
}

export interface GetGwApiV1AccountsLoginMessagesRequest {
    loginMessageRequest: LoginMessageRequest;
}

export interface GetGwApiV1AccountsStatusRequest {
    accountStatusRequest: AccountStatusRequest;
}

export interface PatchGwApiV1AccountsRequest {
    body: string;
}

export interface PatchGwApiV1AccountsAccountidStatusRequest {
    accountId: string;
    body: string;
}

export interface PatchGwApiV1AccountsAccountidTasksRequest {
    accountId: string;
    body: string;
}

export interface PostGwApiV1AccountsRequest {
    body: string;
}

export interface PostGwApiV1AccountsAccountidTasksRequest {
    accountId: string;
    body: string;
}

export interface PostGwApiV1AccountsDocumentsRequest {
    body: string;
}

/**
 * AccountManagementAccountsApi - interface
 * 
 * @export
 * @interface AccountManagementAccountsApiInterface
 */
export interface AccountManagementAccountsApiInterface {
    /**
     * Creates request options for getGwApiV1Accounts without sending the request
     * @param {string} [accountId] 
     * @param {string} [externalId] 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsRequestOpts(requestParameters: GetGwApiV1AccountsRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieve the application request and IBKR response data based on IBKR accountId or externalId. Only available for accounts that originate via API<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * @summary Retrieve Processed Application
     * @param {string} [accountId] 
     * @param {string} [externalId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsRaw(requestParameters: GetGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGwApiV1Accounts200Response>>;

    /**
     * Retrieve the application request and IBKR response data based on IBKR accountId or externalId. Only available for accounts that originate via API<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Retrieve Processed Application
     */
    getGwApiV1Accounts(requestParameters: GetGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGwApiV1Accounts200Response>;

    /**
     * Creates request options for getGwApiV1AccountsAccountidDetails without sending the request
     * @param {string} accountId 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidDetailsRequestOpts(requestParameters: GetGwApiV1AccountsAccountidDetailsRequest): Promise<runtime.RequestOpts>;

    /**
     * <br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * @summary Get Account Information
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidDetailsRaw(requestParameters: GetGwApiV1AccountsAccountidDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDetailsResponse>>;

    /**
     * <br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Account Information
     */
    getGwApiV1AccountsAccountidDetails(requestParameters: GetGwApiV1AccountsAccountidDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDetailsResponse>;

    /**
     * Creates request options for getGwApiV1AccountsAccountidKyc without sending the request
     * @param {string} accountId 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidKycRequestOpts(requestParameters: GetGwApiV1AccountsAccountidKycRequest): Promise<runtime.RequestOpts>;

    /**
     * Generate URL address to complete real-time KYC verification using Au10Tix<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * @summary Retrieve Au10Tix URL
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidKycRaw(requestParameters: GetGwApiV1AccountsAccountidKycRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Au10TixDetailResponse>>;

    /**
     * Generate URL address to complete real-time KYC verification using Au10Tix<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Retrieve Au10Tix URL
     */
    getGwApiV1AccountsAccountidKyc(requestParameters: GetGwApiV1AccountsAccountidKycRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Au10TixDetailResponse>;

    /**
     * Creates request options for getGwApiV1AccountsAccountidLoginMessages without sending the request
     * @param {string} accountId 
     * @param {string} [type] 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidLoginMessagesRequestOpts(requestParameters: GetGwApiV1AccountsAccountidLoginMessagesRequest): Promise<runtime.RequestOpts>;

    /**
     * Query login messages assigned by accountId<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * @summary Get Login Message By Account
     * @param {string} accountId 
     * @param {string} [type] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidLoginMessagesRaw(requestParameters: GetGwApiV1AccountsAccountidLoginMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginMessageResponse>>;

    /**
     * Query login messages assigned by accountId<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Login Message By Account
     */
    getGwApiV1AccountsAccountidLoginMessages(requestParameters: GetGwApiV1AccountsAccountidLoginMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginMessageResponse>;

    /**
     * Creates request options for getGwApiV1AccountsAccountidStatus without sending the request
     * @param {string} accountId 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidStatusRequestOpts(requestParameters: GetGwApiV1AccountsAccountidStatusRequest): Promise<runtime.RequestOpts>;

    /**
     * Query status of account by accountId<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * @summary Get Status By Account
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidStatusRaw(requestParameters: GetGwApiV1AccountsAccountidStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountStatusResponse>>;

    /**
     * Query status of account by accountId<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Status By Account
     */
    getGwApiV1AccountsAccountidStatus(requestParameters: GetGwApiV1AccountsAccountidStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountStatusResponse>;

    /**
     * Creates request options for getGwApiV1AccountsAccountidTasks without sending the request
     * @param {string} accountId 
     * @param {'pending' | 'registration'} [type] 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidTasksRequestOpts(requestParameters: GetGwApiV1AccountsAccountidTasksRequest): Promise<runtime.RequestOpts>;

    /**
     * Query registration tasks assigned to account and pending tasks that are required for account approval<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * @summary Get Registration Tasks
     * @param {string} accountId 
     * @param {'pending' | 'registration'} [type] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsAccountidTasksRaw(requestParameters: GetGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGwApiV1AccountsAccountidTasks200Response>>;

    /**
     * Query registration tasks assigned to account and pending tasks that are required for account approval<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Registration Tasks
     */
    getGwApiV1AccountsAccountidTasks(requestParameters: GetGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGwApiV1AccountsAccountidTasks200Response>;

    /**
     * Creates request options for getGwApiV1AccountsLoginMessages without sending the request
     * @param {LoginMessageRequest} loginMessageRequest 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsLoginMessagesRequestOpts(requestParameters: GetGwApiV1AccountsLoginMessagesRequest): Promise<runtime.RequestOpts>;

    /**
     * Query all accounts associated with ‘Client ID’ that have incomplete login message<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * @summary Get Login Messages
     * @param {LoginMessageRequest} loginMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsLoginMessagesRaw(requestParameters: GetGwApiV1AccountsLoginMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginMessageResponse>>;

    /**
     * Query all accounts associated with ‘Client ID’ that have incomplete login message<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Login Messages
     */
    getGwApiV1AccountsLoginMessages(requestParameters: GetGwApiV1AccountsLoginMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginMessageResponse>;

    /**
     * Creates request options for getGwApiV1AccountsStatus without sending the request
     * @param {AccountStatusRequest} accountStatusRequest 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsStatusRequestOpts(requestParameters: GetGwApiV1AccountsStatusRequest): Promise<runtime.RequestOpts>;

    /**
     * Query status of all accounts associated with ‘Client ID\'<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * @summary Get Status Of Accounts
     * @param {AccountStatusRequest} accountStatusRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    getGwApiV1AccountsStatusRaw(requestParameters: GetGwApiV1AccountsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountStatusBulkResponse>>;

    /**
     * Query status of all accounts associated with ‘Client ID\'<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Status Of Accounts
     */
    getGwApiV1AccountsStatus(requestParameters: GetGwApiV1AccountsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountStatusBulkResponse>;

    /**
     * Creates request options for patchGwApiV1Accounts without sending the request
     * @param {string} body 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    patchGwApiV1AccountsRequestOpts(requestParameters: PatchGwApiV1AccountsRequest): Promise<runtime.RequestOpts>;

    /**
     * Update information for an existing accountId<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * @summary Update Account
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    patchGwApiV1AccountsRaw(requestParameters: PatchGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>>;

    /**
     * Update information for an existing accountId<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Account
     */
    patchGwApiV1Accounts(requestParameters: PatchGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse>;

    /**
     * Creates request options for patchGwApiV1AccountsAccountidStatus without sending the request
     * @param {string} accountId 
     * @param {string} body 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    patchGwApiV1AccountsAccountidStatusRequestOpts(requestParameters: PatchGwApiV1AccountsAccountidStatusRequest): Promise<runtime.RequestOpts>;

    /**
     * Query status of account by accountId<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * @summary Update Status By Account
     * @param {string} accountId 
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    patchGwApiV1AccountsAccountidStatusRaw(requestParameters: PatchGwApiV1AccountsAccountidStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountStatusResponse>>;

    /**
     * Query status of account by accountId<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Status By Account
     */
    patchGwApiV1AccountsAccountidStatus(requestParameters: PatchGwApiV1AccountsAccountidStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountStatusResponse>;

    /**
     * Creates request options for patchGwApiV1AccountsAccountidTasks without sending the request
     * @param {string} accountId 
     * @param {string} body 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    patchGwApiV1AccountsAccountidTasksRequestOpts(requestParameters: PatchGwApiV1AccountsAccountidTasksRequest): Promise<runtime.RequestOpts>;

    /**
     * Task status can be updated from this api<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * @summary Update Tasks Status
     * @param {string} accountId 
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    patchGwApiV1AccountsAccountidTasksRaw(requestParameters: PatchGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskActionResponse>>>;

    /**
     * Task status can be updated from this api<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Tasks Status
     */
    patchGwApiV1AccountsAccountidTasks(requestParameters: PatchGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskActionResponse>>;

    /**
     * Creates request options for postGwApiV1Accounts without sending the request
     * @param {string} body 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    postGwApiV1AccountsRequestOpts(requestParameters: PostGwApiV1AccountsRequest): Promise<runtime.RequestOpts>;

    /**
     * Submit account application. This will create brokerage account for the end user.<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * @summary Create Account
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    postGwApiV1AccountsRaw(requestParameters: PostGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>>;

    /**
     * Submit account application. This will create brokerage account for the end user.<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Create Account
     */
    postGwApiV1Accounts(requestParameters: PostGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse>;

    /**
     * Creates request options for postGwApiV1AccountsAccountidTasks without sending the request
     * @param {string} accountId 
     * @param {string} body 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    postGwApiV1AccountsAccountidTasksRequestOpts(requestParameters: PostGwApiV1AccountsAccountidTasksRequest): Promise<runtime.RequestOpts>;

    /**
     * Task can be assigned from this api<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * @summary Assign Tasks
     * @param {string} accountId 
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    postGwApiV1AccountsAccountidTasksRaw(requestParameters: PostGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskActionResponse>>>;

    /**
     * Task can be assigned from this api<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Assign Tasks
     */
    postGwApiV1AccountsAccountidTasks(requestParameters: PostGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskActionResponse>>;

    /**
     * Creates request options for postGwApiV1AccountsDocuments without sending the request
     * @param {string} body 
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    postGwApiV1AccountsDocumentsRequestOpts(requestParameters: PostGwApiV1AccountsDocumentsRequest): Promise<runtime.RequestOpts>;

    /**
     * Provides mechanism to submit Agreements and Disclosures to IBKR once a day instead of with each application. We store these documents on the servers and will use them for new application requests submitted that day.<ul><li>Documents will need to be submitted once a day (before the Applications are submitted). PDFs will be displayed and submitted as is- no changes/edits will be made to the actual PDF files.</li><li>This end-point will not process any Tax Form Documents. Tax Form document should be submitted with every application</li><li>If submitted in the morning, you only need to include the Tax Form attachment for each applicant. Otherwise, you will need to include PDFs with each application (Create Account).</li></ul><br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * @summary Submit General Agreements And Disclosures
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountManagementAccountsApiInterface
     */
    postGwApiV1AccountsDocumentsRaw(requestParameters: PostGwApiV1AccountsDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>>;

    /**
     * Provides mechanism to submit Agreements and Disclosures to IBKR once a day instead of with each application. We store these documents on the servers and will use them for new application requests submitted that day.<ul><li>Documents will need to be submitted once a day (before the Applications are submitted). PDFs will be displayed and submitted as is- no changes/edits will be made to the actual PDF files.</li><li>This end-point will not process any Tax Form Documents. Tax Form document should be submitted with every application</li><li>If submitted in the morning, you only need to include the Tax Form attachment for each applicant. Otherwise, you will need to include PDFs with each application (Create Account).</li></ul><br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Submit General Agreements And Disclosures
     */
    postGwApiV1AccountsDocuments(requestParameters: PostGwApiV1AccountsDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse>;

}

/**
 * 
 */
export class AccountManagementAccountsApi extends runtime.BaseAPI implements AccountManagementAccountsApiInterface {

    /**
     * Creates request options for getGwApiV1Accounts without sending the request
     */
    async getGwApiV1AccountsRequestOpts(requestParameters: GetGwApiV1AccountsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['externalId'] != null) {
            queryParameters['externalId'] = requestParameters['externalId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gw/api/v1/accounts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve the application request and IBKR response data based on IBKR accountId or externalId. Only available for accounts that originate via API<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Retrieve Processed Application
     */
    async getGwApiV1AccountsRaw(requestParameters: GetGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGwApiV1Accounts200Response>> {
        const requestOptions = await this.getGwApiV1AccountsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGwApiV1Accounts200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the application request and IBKR response data based on IBKR accountId or externalId. Only available for accounts that originate via API<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Retrieve Processed Application
     */
    async getGwApiV1Accounts(requestParameters: GetGwApiV1AccountsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGwApiV1Accounts200Response> {
        const response = await this.getGwApiV1AccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGwApiV1AccountsAccountidDetails without sending the request
     */
    async getGwApiV1AccountsAccountidDetailsRequestOpts(requestParameters: GetGwApiV1AccountsAccountidDetailsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getGwApiV1AccountsAccountidDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gw/api/v1/accounts/{accountId}/details`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * <br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Account Information
     */
    async getGwApiV1AccountsAccountidDetailsRaw(requestParameters: GetGwApiV1AccountsAccountidDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDetailsResponse>> {
        const requestOptions = await this.getGwApiV1AccountsAccountidDetailsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountDetailsResponseFromJSON(jsonValue));
    }

    /**
     * <br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Account Information
     */
    async getGwApiV1AccountsAccountidDetails(requestParameters: GetGwApiV1AccountsAccountidDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDetailsResponse> {
        const response = await this.getGwApiV1AccountsAccountidDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGwApiV1AccountsAccountidKyc without sending the request
     */
    async getGwApiV1AccountsAccountidKycRequestOpts(requestParameters: GetGwApiV1AccountsAccountidKycRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getGwApiV1AccountsAccountidKyc().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gw/api/v1/accounts/{accountId}/kyc`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Generate URL address to complete real-time KYC verification using Au10Tix<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Retrieve Au10Tix URL
     */
    async getGwApiV1AccountsAccountidKycRaw(requestParameters: GetGwApiV1AccountsAccountidKycRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Au10TixDetailResponse>> {
        const requestOptions = await this.getGwApiV1AccountsAccountidKycRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Au10TixDetailResponseFromJSON(jsonValue));
    }

    /**
     * Generate URL address to complete real-time KYC verification using Au10Tix<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Retrieve Au10Tix URL
     */
    async getGwApiV1AccountsAccountidKyc(requestParameters: GetGwApiV1AccountsAccountidKycRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Au10TixDetailResponse> {
        const response = await this.getGwApiV1AccountsAccountidKycRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGwApiV1AccountsAccountidLoginMessages without sending the request
     */
    async getGwApiV1AccountsAccountidLoginMessagesRequestOpts(requestParameters: GetGwApiV1AccountsAccountidLoginMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getGwApiV1AccountsAccountidLoginMessages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gw/api/v1/accounts/{accountId}/login-messages`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Query login messages assigned by accountId<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Login Message By Account
     */
    async getGwApiV1AccountsAccountidLoginMessagesRaw(requestParameters: GetGwApiV1AccountsAccountidLoginMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginMessageResponse>> {
        const requestOptions = await this.getGwApiV1AccountsAccountidLoginMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginMessageResponseFromJSON(jsonValue));
    }

    /**
     * Query login messages assigned by accountId<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Login Message By Account
     */
    async getGwApiV1AccountsAccountidLoginMessages(requestParameters: GetGwApiV1AccountsAccountidLoginMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginMessageResponse> {
        const response = await this.getGwApiV1AccountsAccountidLoginMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGwApiV1AccountsAccountidStatus without sending the request
     */
    async getGwApiV1AccountsAccountidStatusRequestOpts(requestParameters: GetGwApiV1AccountsAccountidStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getGwApiV1AccountsAccountidStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gw/api/v1/accounts/{accountId}/status`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Query status of account by accountId<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Status By Account
     */
    async getGwApiV1AccountsAccountidStatusRaw(requestParameters: GetGwApiV1AccountsAccountidStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountStatusResponse>> {
        const requestOptions = await this.getGwApiV1AccountsAccountidStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountStatusResponseFromJSON(jsonValue));
    }

    /**
     * Query status of account by accountId<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Status By Account
     */
    async getGwApiV1AccountsAccountidStatus(requestParameters: GetGwApiV1AccountsAccountidStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountStatusResponse> {
        const response = await this.getGwApiV1AccountsAccountidStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGwApiV1AccountsAccountidTasks without sending the request
     */
    async getGwApiV1AccountsAccountidTasksRequestOpts(requestParameters: GetGwApiV1AccountsAccountidTasksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getGwApiV1AccountsAccountidTasks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gw/api/v1/accounts/{accountId}/tasks`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Query registration tasks assigned to account and pending tasks that are required for account approval<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Registration Tasks
     */
    async getGwApiV1AccountsAccountidTasksRaw(requestParameters: GetGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGwApiV1AccountsAccountidTasks200Response>> {
        const requestOptions = await this.getGwApiV1AccountsAccountidTasksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGwApiV1AccountsAccountidTasks200ResponseFromJSON(jsonValue));
    }

    /**
     * Query registration tasks assigned to account and pending tasks that are required for account approval<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Registration Tasks
     */
    async getGwApiV1AccountsAccountidTasks(requestParameters: GetGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGwApiV1AccountsAccountidTasks200Response> {
        const response = await this.getGwApiV1AccountsAccountidTasksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGwApiV1AccountsLoginMessages without sending the request
     */
    async getGwApiV1AccountsLoginMessagesRequestOpts(requestParameters: GetGwApiV1AccountsLoginMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'loginMessageRequest',
                'Required parameter "loginMessageRequest" was null or undefined when calling getGwApiV1AccountsLoginMessages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['loginMessageRequest'] != null) {
            queryParameters['loginMessageRequest'] = requestParameters['loginMessageRequest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gw/api/v1/accounts/login-messages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Query all accounts associated with ‘Client ID’ that have incomplete login message<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Login Messages
     */
    async getGwApiV1AccountsLoginMessagesRaw(requestParameters: GetGwApiV1AccountsLoginMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginMessageResponse>> {
        const requestOptions = await this.getGwApiV1AccountsLoginMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginMessageResponseFromJSON(jsonValue));
    }

    /**
     * Query all accounts associated with ‘Client ID’ that have incomplete login message<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Login Messages
     */
    async getGwApiV1AccountsLoginMessages(requestParameters: GetGwApiV1AccountsLoginMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginMessageResponse> {
        const response = await this.getGwApiV1AccountsLoginMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGwApiV1AccountsStatus without sending the request
     */
    async getGwApiV1AccountsStatusRequestOpts(requestParameters: GetGwApiV1AccountsStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'accountStatusRequest',
                'Required parameter "accountStatusRequest" was null or undefined when calling getGwApiV1AccountsStatus().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountStatusRequest'] != null) {
            queryParameters['accountStatusRequest'] = requestParameters['accountStatusRequest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gw/api/v1/accounts/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Query status of all accounts associated with ‘Client ID\'<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Status Of Accounts
     */
    async getGwApiV1AccountsStatusRaw(requestParameters: GetGwApiV1AccountsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountStatusBulkResponse>> {
        const requestOptions = await this.getGwApiV1AccountsStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountStatusBulkResponseFromJSON(jsonValue));
    }

    /**
     * Query status of all accounts associated with ‘Client ID\'<br><br>**Scope**: `accounts.read`<br>**Security Policy**: `HTTPS`
     * Get Status Of Accounts
     */
    async getGwApiV1AccountsStatus(requestParameters: GetGwApiV1AccountsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountStatusBulkResponse> {
        const response = await this.getGwApiV1AccountsStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchGwApiV1Accounts without sending the request
     */
    async patchGwApiV1AccountsRequestOpts(requestParameters: PatchGwApiV1AccountsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling patchGwApiV1Accounts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/gw/api/v1/accounts`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update information for an existing accountId<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Account
     */
    async patchGwApiV1AccountsRaw(requestParameters: PatchGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>> {
        const requestOptions = await this.patchGwApiV1AccountsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusResponseFromJSON(jsonValue));
    }

    /**
     * Update information for an existing accountId<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Account
     */
    async patchGwApiV1Accounts(requestParameters: PatchGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse> {
        const response = await this.patchGwApiV1AccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchGwApiV1AccountsAccountidStatus without sending the request
     */
    async patchGwApiV1AccountsAccountidStatusRequestOpts(requestParameters: PatchGwApiV1AccountsAccountidStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling patchGwApiV1AccountsAccountidStatus().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling patchGwApiV1AccountsAccountidStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/gw/api/v1/accounts/{accountId}/status`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Query status of account by accountId<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Status By Account
     */
    async patchGwApiV1AccountsAccountidStatusRaw(requestParameters: PatchGwApiV1AccountsAccountidStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountStatusResponse>> {
        const requestOptions = await this.patchGwApiV1AccountsAccountidStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountStatusResponseFromJSON(jsonValue));
    }

    /**
     * Query status of account by accountId<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Status By Account
     */
    async patchGwApiV1AccountsAccountidStatus(requestParameters: PatchGwApiV1AccountsAccountidStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountStatusResponse> {
        const response = await this.patchGwApiV1AccountsAccountidStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchGwApiV1AccountsAccountidTasks without sending the request
     */
    async patchGwApiV1AccountsAccountidTasksRequestOpts(requestParameters: PatchGwApiV1AccountsAccountidTasksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling patchGwApiV1AccountsAccountidTasks().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling patchGwApiV1AccountsAccountidTasks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/gw/api/v1/accounts/{accountId}/tasks`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Task status can be updated from this api<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Tasks Status
     */
    async patchGwApiV1AccountsAccountidTasksRaw(requestParameters: PatchGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskActionResponse>>> {
        const requestOptions = await this.patchGwApiV1AccountsAccountidTasksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskActionResponseFromJSON));
    }

    /**
     * Task status can be updated from this api<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Update Tasks Status
     */
    async patchGwApiV1AccountsAccountidTasks(requestParameters: PatchGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskActionResponse>> {
        const response = await this.patchGwApiV1AccountsAccountidTasksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postGwApiV1Accounts without sending the request
     */
    async postGwApiV1AccountsRequestOpts(requestParameters: PostGwApiV1AccountsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling postGwApiV1Accounts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/gw/api/v1/accounts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Submit account application. This will create brokerage account for the end user.<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Create Account
     */
    async postGwApiV1AccountsRaw(requestParameters: PostGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>> {
        const requestOptions = await this.postGwApiV1AccountsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusResponseFromJSON(jsonValue));
    }

    /**
     * Submit account application. This will create brokerage account for the end user.<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Create Account
     */
    async postGwApiV1Accounts(requestParameters: PostGwApiV1AccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse> {
        const response = await this.postGwApiV1AccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postGwApiV1AccountsAccountidTasks without sending the request
     */
    async postGwApiV1AccountsAccountidTasksRequestOpts(requestParameters: PostGwApiV1AccountsAccountidTasksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling postGwApiV1AccountsAccountidTasks().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling postGwApiV1AccountsAccountidTasks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/gw/api/v1/accounts/{accountId}/tasks`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Task can be assigned from this api<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Assign Tasks
     */
    async postGwApiV1AccountsAccountidTasksRaw(requestParameters: PostGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskActionResponse>>> {
        const requestOptions = await this.postGwApiV1AccountsAccountidTasksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskActionResponseFromJSON));
    }

    /**
     * Task can be assigned from this api<br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Assign Tasks
     */
    async postGwApiV1AccountsAccountidTasks(requestParameters: PostGwApiV1AccountsAccountidTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskActionResponse>> {
        const response = await this.postGwApiV1AccountsAccountidTasksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postGwApiV1AccountsDocuments without sending the request
     */
    async postGwApiV1AccountsDocumentsRequestOpts(requestParameters: PostGwApiV1AccountsDocumentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling postGwApiV1AccountsDocuments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/gw/api/v1/accounts/documents`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Provides mechanism to submit Agreements and Disclosures to IBKR once a day instead of with each application. We store these documents on the servers and will use them for new application requests submitted that day.<ul><li>Documents will need to be submitted once a day (before the Applications are submitted). PDFs will be displayed and submitted as is- no changes/edits will be made to the actual PDF files.</li><li>This end-point will not process any Tax Form Documents. Tax Form document should be submitted with every application</li><li>If submitted in the morning, you only need to include the Tax Form attachment for each applicant. Otherwise, you will need to include PDFs with each application (Create Account).</li></ul><br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Submit General Agreements And Disclosures
     */
    async postGwApiV1AccountsDocumentsRaw(requestParameters: PostGwApiV1AccountsDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>> {
        const requestOptions = await this.postGwApiV1AccountsDocumentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusResponseFromJSON(jsonValue));
    }

    /**
     * Provides mechanism to submit Agreements and Disclosures to IBKR once a day instead of with each application. We store these documents on the servers and will use them for new application requests submitted that day.<ul><li>Documents will need to be submitted once a day (before the Applications are submitted). PDFs will be displayed and submitted as is- no changes/edits will be made to the actual PDF files.</li><li>This end-point will not process any Tax Form Documents. Tax Form document should be submitted with every application</li><li>If submitted in the morning, you only need to include the Tax Form attachment for each applicant. Otherwise, you will need to include PDFs with each application (Create Account).</li></ul><br><br>**Scope**: `accounts.write`<br>**Security Policy**: `Signed JWT`
     * Submit General Agreements And Disclosures
     */
    async postGwApiV1AccountsDocuments(requestParameters: PostGwApiV1AccountsDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse> {
        const response = await this.postGwApiV1AccountsDocumentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetGwApiV1AccountsAccountidTasksTypeEnum = {
    Pending: 'pending',
    Registration: 'registration'
} as const;
export type GetGwApiV1AccountsAccountidTasksTypeEnum = typeof GetGwApiV1AccountsAccountidTasksTypeEnum[keyof typeof GetGwApiV1AccountsAccountidTasksTypeEnum];
