/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TokenResponse,
} from '../models/index';
import {
    TokenResponseFromJSON,
    TokenResponseToJSON,
} from '../models/index';

export interface GenerateTokenRequest {
    clientAssertion?: string;
    clientAssertionType?: string;
    clientAuthenticationMethod?: GenerateTokenClientAuthenticationMethodEnum;
    clientId?: string;
    clientSecret?: string;
}

/**
 * AuthorizationTokenApi - interface
 * 
 * @export
 * @interface AuthorizationTokenApiInterface
 */
export interface AuthorizationTokenApiInterface {
    /**
     * Creates request options for generateToken without sending the request
     * @param {string} [clientAssertion] 
     * @param {string} [clientAssertionType] 
     * @param {string} [clientAuthenticationMethod] 
     * @param {string} [clientId] 
     * @param {string} [clientSecret] 
     * @throws {RequiredError}
     * @memberof AuthorizationTokenApiInterface
     */
    generateTokenRequestOpts(requestParameters: GenerateTokenRequest): Promise<runtime.RequestOpts>;

    /**
     * Generate OAuth 2.0 access tokens based on request parameters.
     * @summary Create Access Token
     * @param {string} [clientAssertion] 
     * @param {string} [clientAssertionType] 
     * @param {string} [clientAuthenticationMethod] 
     * @param {string} [clientId] 
     * @param {string} [clientSecret] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorizationTokenApiInterface
     */
    generateTokenRaw(requestParameters: GenerateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>>;

    /**
     * Generate OAuth 2.0 access tokens based on request parameters.
     * Create Access Token
     */
    generateToken(requestParameters: GenerateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse>;

}

/**
 * 
 */
export class AuthorizationTokenApi extends runtime.BaseAPI implements AuthorizationTokenApiInterface {

    /**
     * Creates request options for generateToken without sending the request
     */
    async generateTokenRequestOpts(requestParameters: GenerateTokenRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['clientAssertion'] != null) {
            formParams.append('clientAssertion', requestParameters['clientAssertion'] as any);
        }

        if (requestParameters['clientAssertionType'] != null) {
            formParams.append('clientAssertionType', requestParameters['clientAssertionType'] as any);
        }

        if (requestParameters['clientAuthenticationMethod'] != null) {
            formParams.append('clientAuthenticationMethod', requestParameters['clientAuthenticationMethod'] as any);
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('clientId', requestParameters['clientId'] as any);
        }

        if (requestParameters['clientSecret'] != null) {
            formParams.append('clientSecret', requestParameters['clientSecret'] as any);
        }


        let urlPath = `/oauth2/api/v1/token`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Generate OAuth 2.0 access tokens based on request parameters.
     * Create Access Token
     */
    async generateTokenRaw(requestParameters: GenerateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.generateTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Generate OAuth 2.0 access tokens based on request parameters.
     * Create Access Token
     */
    async generateToken(requestParameters: GenerateTokenRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.generateTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GenerateTokenClientAuthenticationMethodEnum = {
    PrivateKeyJwt: 'private_key_jwt',
    ClientSecretBasic: 'client_secret_basic',
    ClientSecretPost: 'client_secret_post'
} as const;
export type GenerateTokenClientAuthenticationMethodEnum = typeof GenerateTokenClientAuthenticationMethodEnum[keyof typeof GenerateTokenClientAuthenticationMethodEnum];
