/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IserverScannerParams,
  IserverScannerRunRequest,
  IserverScannerRunResponse,
} from '../models/index';
import {
    IserverScannerParamsFromJSON,
    IserverScannerParamsToJSON,
    IserverScannerRunRequestFromJSON,
    IserverScannerRunRequestToJSON,
    IserverScannerRunResponseFromJSON,
    IserverScannerRunResponseToJSON,
} from '../models/index';

export interface GetScannerResultsRequest {
    iserverScannerRunRequest: IserverScannerRunRequest;
}

/**
 * TradingScannerApi - interface
 * 
 * @export
 * @interface TradingScannerApiInterface
 */
export interface TradingScannerApiInterface {
    /**
     * Creates request options for getScannerParameters without sending the request
     * @throws {RequiredError}
     * @memberof TradingScannerApiInterface
     */
    getScannerParametersRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns an xml file containing all available parameters to be sent for the Iserver scanner request.
     * @summary Get Valid IServer Scanner Parameters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingScannerApiInterface
     */
    getScannerParametersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IserverScannerParams>>;

    /**
     * Returns an xml file containing all available parameters to be sent for the Iserver scanner request.
     * Get Valid IServer Scanner Parameters
     */
    getScannerParameters(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IserverScannerParams>;

    /**
     * Creates request options for getScannerResults without sending the request
     * @param {IserverScannerRunRequest} iserverScannerRunRequest 
     * @throws {RequiredError}
     * @memberof TradingScannerApiInterface
     */
    getScannerResultsRequestOpts(requestParameters: GetScannerResultsRequest): Promise<runtime.RequestOpts>;

    /**
     * Searches for contracts according to the filters specified in /iserver/scanner/params endpoint.
     * @summary Run An IServer Market Scanner
     * @param {IserverScannerRunRequest} iserverScannerRunRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingScannerApiInterface
     */
    getScannerResultsRaw(requestParameters: GetScannerResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IserverScannerRunResponse>>;

    /**
     * Searches for contracts according to the filters specified in /iserver/scanner/params endpoint.
     * Run An IServer Market Scanner
     */
    getScannerResults(requestParameters: GetScannerResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IserverScannerRunResponse>;

}

/**
 * 
 */
export class TradingScannerApi extends runtime.BaseAPI implements TradingScannerApiInterface {

    /**
     * Creates request options for getScannerParameters without sending the request
     */
    async getScannerParametersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/iserver/scanner/params`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns an xml file containing all available parameters to be sent for the Iserver scanner request.
     * Get Valid IServer Scanner Parameters
     */
    async getScannerParametersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IserverScannerParams>> {
        const requestOptions = await this.getScannerParametersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IserverScannerParamsFromJSON(jsonValue));
    }

    /**
     * Returns an xml file containing all available parameters to be sent for the Iserver scanner request.
     * Get Valid IServer Scanner Parameters
     */
    async getScannerParameters(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IserverScannerParams> {
        const response = await this.getScannerParametersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getScannerResults without sending the request
     */
    async getScannerResultsRequestOpts(requestParameters: GetScannerResultsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['iserverScannerRunRequest'] == null) {
            throw new runtime.RequiredError(
                'iserverScannerRunRequest',
                'Required parameter "iserverScannerRunRequest" was null or undefined when calling getScannerResults().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/iserver/scanner/run`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IserverScannerRunRequestToJSON(requestParameters['iserverScannerRunRequest']),
        };
    }

    /**
     * Searches for contracts according to the filters specified in /iserver/scanner/params endpoint.
     * Run An IServer Market Scanner
     */
    async getScannerResultsRaw(requestParameters: GetScannerResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IserverScannerRunResponse>> {
        const requestOptions = await this.getScannerResultsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IserverScannerRunResponseFromJSON(jsonValue));
    }

    /**
     * Searches for contracts according to the filters specified in /iserver/scanner/params endpoint.
     * Run An IServer Market Scanner
     */
    async getScannerResults(requestParameters: GetScannerResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IserverScannerRunResponse> {
        const response = await this.getScannerResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
