/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BrokerageSessionInitRequest,
  BrokerageSessionStatus,
  Logout200Response,
  SsoValidateResponse,
  TickleResponse,
} from '../models/index';
import {
    BrokerageSessionInitRequestFromJSON,
    BrokerageSessionInitRequestToJSON,
    BrokerageSessionStatusFromJSON,
    BrokerageSessionStatusToJSON,
    Logout200ResponseFromJSON,
    Logout200ResponseToJSON,
    SsoValidateResponseFromJSON,
    SsoValidateResponseToJSON,
    TickleResponseFromJSON,
    TickleResponseToJSON,
} from '../models/index';

export interface InitializeSessionRequest {
    brokerageSessionInitRequest: BrokerageSessionInitRequest;
}

/**
 * TradingSessionApi - interface
 * 
 * @export
 * @interface TradingSessionApiInterface
 */
export interface TradingSessionApiInterface {
    /**
     * Creates request options for getBrokerageStatus without sending the request
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    getBrokerageStatusRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Current Authentication status to the Brokerage system. Market Data and Trading is not possible if not authenticated.
     * @summary Brokerage Session Status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    getBrokerageStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrokerageSessionStatus>>;

    /**
     * Current Authentication status to the Brokerage system. Market Data and Trading is not possible if not authenticated.
     * Brokerage Session Status
     */
    getBrokerageStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrokerageSessionStatus>;

    /**
     * Creates request options for getSessionToken without sending the request
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    getSessionTokenRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * If the gateway has not received any requests for several minutes an open session will automatically timeout. The tickle endpoint pings the server to prevent the session from ending. It is expected to call this endpoint approximately every 60 seconds to maintain the connection to the brokerage session.
     * @summary Brokerage Keep-Alive Ping
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    getSessionTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TickleResponse>>;

    /**
     * If the gateway has not received any requests for several minutes an open session will automatically timeout. The tickle endpoint pings the server to prevent the session from ending. It is expected to call this endpoint approximately every 60 seconds to maintain the connection to the brokerage session.
     * Brokerage Keep-Alive Ping
     */
    getSessionToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TickleResponse>;

    /**
     * Creates request options for getSessionValidation without sending the request
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    getSessionValidationRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Validates the current session for the SSO user.
     * @summary Validate SSO Web API Session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    getSessionValidationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SsoValidateResponse>>;

    /**
     * Validates the current session for the SSO user.
     * Validate SSO Web API Session
     */
    getSessionValidation(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SsoValidateResponse>;

    /**
     * Creates request options for initializeSession without sending the request
     * @param {BrokerageSessionInitRequest} brokerageSessionInitRequest 
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    initializeSessionRequestOpts(requestParameters: InitializeSessionRequest): Promise<runtime.RequestOpts>;

    /**
     * After retrieving the access token and subsequent Live Session Token, customers can initialize their brokerage session with the ssodh/init endpoint.
     * @summary Initialize Brokerage Session
     * @param {BrokerageSessionInitRequest} brokerageSessionInitRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    initializeSessionRaw(requestParameters: InitializeSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrokerageSessionStatus>>;

    /**
     * After retrieving the access token and subsequent Live Session Token, customers can initialize their brokerage session with the ssodh/init endpoint.
     * Initialize Brokerage Session
     */
    initializeSession(requestParameters: InitializeSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrokerageSessionStatus>;

    /**
     * Creates request options for logout without sending the request
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    logoutRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Logs the user out of the gateway session. Any further activity requires re-authentication. Discard client-side cookies upon logout. 
     * @summary Terminate Web API Session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingSessionApiInterface
     */
    logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>>;

    /**
     * Logs the user out of the gateway session. Any further activity requires re-authentication. Discard client-side cookies upon logout. 
     * Terminate Web API Session
     */
    logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response>;

}

/**
 * 
 */
export class TradingSessionApi extends runtime.BaseAPI implements TradingSessionApiInterface {

    /**
     * Creates request options for getBrokerageStatus without sending the request
     */
    async getBrokerageStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/iserver/auth/status`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Current Authentication status to the Brokerage system. Market Data and Trading is not possible if not authenticated.
     * Brokerage Session Status
     */
    async getBrokerageStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrokerageSessionStatus>> {
        const requestOptions = await this.getBrokerageStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrokerageSessionStatusFromJSON(jsonValue));
    }

    /**
     * Current Authentication status to the Brokerage system. Market Data and Trading is not possible if not authenticated.
     * Brokerage Session Status
     */
    async getBrokerageStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrokerageSessionStatus> {
        const response = await this.getBrokerageStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSessionToken without sending the request
     */
    async getSessionTokenRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tickle`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * If the gateway has not received any requests for several minutes an open session will automatically timeout. The tickle endpoint pings the server to prevent the session from ending. It is expected to call this endpoint approximately every 60 seconds to maintain the connection to the brokerage session.
     * Brokerage Keep-Alive Ping
     */
    async getSessionTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TickleResponse>> {
        const requestOptions = await this.getSessionTokenRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TickleResponseFromJSON(jsonValue));
    }

    /**
     * If the gateway has not received any requests for several minutes an open session will automatically timeout. The tickle endpoint pings the server to prevent the session from ending. It is expected to call this endpoint approximately every 60 seconds to maintain the connection to the brokerage session.
     * Brokerage Keep-Alive Ping
     */
    async getSessionToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TickleResponse> {
        const response = await this.getSessionTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSessionValidation without sending the request
     */
    async getSessionValidationRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sso/validate`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Validates the current session for the SSO user.
     * Validate SSO Web API Session
     */
    async getSessionValidationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SsoValidateResponse>> {
        const requestOptions = await this.getSessionValidationRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SsoValidateResponseFromJSON(jsonValue));
    }

    /**
     * Validates the current session for the SSO user.
     * Validate SSO Web API Session
     */
    async getSessionValidation(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SsoValidateResponse> {
        const response = await this.getSessionValidationRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for initializeSession without sending the request
     */
    async initializeSessionRequestOpts(requestParameters: InitializeSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['brokerageSessionInitRequest'] == null) {
            throw new runtime.RequiredError(
                'brokerageSessionInitRequest',
                'Required parameter "brokerageSessionInitRequest" was null or undefined when calling initializeSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/iserver/auth/ssodh/init`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BrokerageSessionInitRequestToJSON(requestParameters['brokerageSessionInitRequest']),
        };
    }

    /**
     * After retrieving the access token and subsequent Live Session Token, customers can initialize their brokerage session with the ssodh/init endpoint.
     * Initialize Brokerage Session
     */
    async initializeSessionRaw(requestParameters: InitializeSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrokerageSessionStatus>> {
        const requestOptions = await this.initializeSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrokerageSessionStatusFromJSON(jsonValue));
    }

    /**
     * After retrieving the access token and subsequent Live Session Token, customers can initialize their brokerage session with the ssodh/init endpoint.
     * Initialize Brokerage Session
     */
    async initializeSession(requestParameters: InitializeSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrokerageSessionStatus> {
        const response = await this.initializeSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Logs the user out of the gateway session. Any further activity requires re-authentication. Discard client-side cookies upon logout. 
     * Terminate Web API Session
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Logout200ResponseFromJSON(jsonValue));
    }

    /**
     * Logs the user out of the gateway session. Any further activity requires re-authentication. Discard client-side cookies upon logout. 
     * Terminate Web API Session
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

}
