/* tslint:disable */
/* eslint-disable */
/**
 * IB REST API
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.29.0
 * Contact: api@interactivebrokers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DetailedContractInformation,
  GetPerformanceAllPeriodsRequest,
  GetSinglePerformancePeriodRequest,
  GetTransactionsRequest,
  PerformanceResponse,
  TransactionsResponse,
} from '../models/index';
import {
    DetailedContractInformationFromJSON,
    DetailedContractInformationToJSON,
    GetPerformanceAllPeriodsRequestFromJSON,
    GetPerformanceAllPeriodsRequestToJSON,
    GetSinglePerformancePeriodRequestFromJSON,
    GetSinglePerformancePeriodRequestToJSON,
    GetTransactionsRequestFromJSON,
    GetTransactionsRequestToJSON,
    PerformanceResponseFromJSON,
    PerformanceResponseToJSON,
    TransactionsResponseFromJSON,
    TransactionsResponseToJSON,
} from '../models/index';

export interface GetPerformanceAllPeriodsOperationRequest {
    getPerformanceAllPeriodsRequest: GetPerformanceAllPeriodsRequest;
    param?: string;
}

export interface GetSinglePerformancePeriodOperationRequest {
    getSinglePerformancePeriodRequest: GetSinglePerformancePeriodRequest;
}

export interface GetTransactionsOperationRequest {
    getTransactionsRequest: GetTransactionsRequest;
}

/**
 * TradingPortfolioAnalystApi - interface
 * 
 * @export
 * @interface TradingPortfolioAnalystApiInterface
 */
export interface TradingPortfolioAnalystApiInterface {
    /**
     * Creates request options for getPerformanceAllPeriods without sending the request
     * @param {GetPerformanceAllPeriodsRequest} getPerformanceAllPeriodsRequest 
     * @param {string} [param] 
     * @throws {RequiredError}
     * @memberof TradingPortfolioAnalystApiInterface
     */
    getPerformanceAllPeriodsRequestOpts(requestParameters: GetPerformanceAllPeriodsOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * @summary Account Performance (All Time Periods)
     * @param {GetPerformanceAllPeriodsRequest} getPerformanceAllPeriodsRequest 
     * @param {string} [param] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingPortfolioAnalystApiInterface
     */
    getPerformanceAllPeriodsRaw(requestParameters: GetPerformanceAllPeriodsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailedContractInformation>>;

    /**
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * Account Performance (All Time Periods)
     */
    getPerformanceAllPeriods(requestParameters: GetPerformanceAllPeriodsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailedContractInformation>;

    /**
     * Creates request options for getSinglePerformancePeriod without sending the request
     * @param {GetSinglePerformancePeriodRequest} getSinglePerformancePeriodRequest 
     * @throws {RequiredError}
     * @memberof TradingPortfolioAnalystApiInterface
     */
    getSinglePerformancePeriodRequestOpts(requestParameters: GetSinglePerformancePeriodOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * @summary Account Performance
     * @param {GetSinglePerformancePeriodRequest} getSinglePerformancePeriodRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingPortfolioAnalystApiInterface
     */
    getSinglePerformancePeriodRaw(requestParameters: GetSinglePerformancePeriodOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceResponse>>;

    /**
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * Account Performance
     */
    getSinglePerformancePeriod(requestParameters: GetSinglePerformancePeriodOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceResponse>;

    /**
     * Creates request options for getTransactions without sending the request
     * @param {GetTransactionsRequest} getTransactionsRequest 
     * @throws {RequiredError}
     * @memberof TradingPortfolioAnalystApiInterface
     */
    getTransactionsRequestOpts(requestParameters: GetTransactionsOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Transaction history for a given number of conids and accounts. Types of transactions include dividend payments, buy and sell transactions, transfers.
     * @summary Transaction History
     * @param {GetTransactionsRequest} getTransactionsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TradingPortfolioAnalystApiInterface
     */
    getTransactionsRaw(requestParameters: GetTransactionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     * Transaction history for a given number of conids and accounts. Types of transactions include dividend payments, buy and sell transactions, transfers.
     * Transaction History
     */
    getTransactions(requestParameters: GetTransactionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

}

/**
 * 
 */
export class TradingPortfolioAnalystApi extends runtime.BaseAPI implements TradingPortfolioAnalystApiInterface {

    /**
     * Creates request options for getPerformanceAllPeriods without sending the request
     */
    async getPerformanceAllPeriodsRequestOpts(requestParameters: GetPerformanceAllPeriodsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getPerformanceAllPeriodsRequest'] == null) {
            throw new runtime.RequiredError(
                'getPerformanceAllPeriodsRequest',
                'Required parameter "getPerformanceAllPeriodsRequest" was null or undefined when calling getPerformanceAllPeriods().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['param'] != null) {
            queryParameters['param'] = requestParameters['param'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pa/allperiods`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetPerformanceAllPeriodsRequestToJSON(requestParameters['getPerformanceAllPeriodsRequest']),
        };
    }

    /**
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * Account Performance (All Time Periods)
     */
    async getPerformanceAllPeriodsRaw(requestParameters: GetPerformanceAllPeriodsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailedContractInformation>> {
        const requestOptions = await this.getPerformanceAllPeriodsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailedContractInformationFromJSON(jsonValue));
    }

    /**
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * Account Performance (All Time Periods)
     */
    async getPerformanceAllPeriods(requestParameters: GetPerformanceAllPeriodsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailedContractInformation> {
        const response = await this.getPerformanceAllPeriodsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSinglePerformancePeriod without sending the request
     */
    async getSinglePerformancePeriodRequestOpts(requestParameters: GetSinglePerformancePeriodOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getSinglePerformancePeriodRequest'] == null) {
            throw new runtime.RequiredError(
                'getSinglePerformancePeriodRequest',
                'Required parameter "getSinglePerformancePeriodRequest" was null or undefined when calling getSinglePerformancePeriod().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pa/performance`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetSinglePerformancePeriodRequestToJSON(requestParameters['getSinglePerformancePeriodRequest']),
        };
    }

    /**
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * Account Performance
     */
    async getSinglePerformancePeriodRaw(requestParameters: GetSinglePerformancePeriodOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceResponse>> {
        const requestOptions = await this.getSinglePerformancePeriodRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerformanceResponseFromJSON(jsonValue));
    }

    /**
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * Account Performance
     */
    async getSinglePerformancePeriod(requestParameters: GetSinglePerformancePeriodOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceResponse> {
        const response = await this.getSinglePerformancePeriodRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransactions without sending the request
     */
    async getTransactionsRequestOpts(requestParameters: GetTransactionsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getTransactionsRequest'] == null) {
            throw new runtime.RequiredError(
                'getTransactionsRequest',
                'Required parameter "getTransactionsRequest" was null or undefined when calling getTransactions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pa/transactions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetTransactionsRequestToJSON(requestParameters['getTransactionsRequest']),
        };
    }

    /**
     * Transaction history for a given number of conids and accounts. Types of transactions include dividend payments, buy and sell transactions, transfers.
     * Transaction History
     */
    async getTransactionsRaw(requestParameters: GetTransactionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        const requestOptions = await this.getTransactionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     * Transaction history for a given number of conids and accounts. Types of transactions include dividend payments, buy and sell transactions, transfers.
     * Transaction History
     */
    async getTransactions(requestParameters: GetTransactionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.getTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
